// Adds figures to the generated Physics 1 exam files (src/hubs/physics1/exams/examN.js).
// Usage (from project root): node tools/exam-authoring/addfigs.mjs [N ...]   (default: all exams that have a p1mapN.mjs)
// The figure data is stored on each question as `figures: [{svg, alt}]`. Re-running replaces existing figures.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";
const HERE = path.dirname(fileURLToPath(import.meta.url));
const EXAMS = path.resolve(HERE, "../../src/hubs/physics1/exams");

// Trim each figure's viewBox to its drawn content (measured in headless Chrome) so scenes stay large on phones,
// and record a suitable minimum display width (the engine scrolls sideways below this).
function cropFigures(figs) {
  const html = `<html><body>${figs.map((f, i) => `<div id="f${i}">${f.svg}</div>`).join("")}<pre id="out"></pre><script>
    const res = [];
    document.querySelectorAll("div[id^=f] > svg").forEach((s) => { const b = s.getBBox(); res.push([b.x, b.y, b.width, b.height]); });
    document.getElementById("out").textContent = JSON.stringify(res);
  </script></body></html>`;
  const tmp = path.join(HERE, "_crop.html");
  fs.writeFileSync(tmp, html);
  const dom = execFileSync("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", ["--headless=new", "--disable-gpu", "--dump-dom", "file://" + tmp], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
  fs.rmSync(tmp);
  const m = dom.match(/<pre id="out">([\s\S]*?)<\/pre>/);
  const boxes = JSON.parse(m[1].replace(/&quot;/g, '"'));
  return figs.map((f, i) => {
    const [x, y, w, h] = boxes[i], pad = 10;
    const vx = Math.floor(x - pad), vy = Math.floor(y - pad), vw = Math.ceil(w + 2 * pad), vh = Math.ceil(h + 2 * pad);
    const svg = f.svg.replace(/viewBox="[^"]*"/, `viewBox="${vx} ${vy} ${vw} ${vh}"`);
    return { ...f, svg, minWidth: Math.max(260, Math.min(440, Math.round(vw * 0.68))) };
  });
}
const ns = process.argv.slice(2).map(Number).filter(Boolean);
// The Sample Exam is defined inline in exams.js, so its figures live in exams/sample-figures.js (id -> figures).
const sampleMap = path.join(HERE, "p1map_sample.mjs");
if (!ns.length && fs.existsSync(sampleMap)) {
  const raw = (await import(sampleMap)).default;
  const flat = Object.entries(raw).flatMap(([id, figs]) => figs.map((f) => [id, f]));
  const cropped = cropFigures(flat.map(([, f]) => f));
  const map = {};
  flat.forEach(([id], i) => (map[id] ||= []).push(cropped[i]));
  fs.writeFileSync(path.join(EXAMS, "sample-figures.js"), `// AP Physics 1 Sample Exam figures (generated by tools/exam-authoring/addfigs.mjs).\nconst SAMPLE_FIGURES = ${JSON.stringify(map, null, 2)};\n\nexport default SAMPLE_FIGURES;\n`);
  Object.entries(map).forEach(([id, figs]) => figs.forEach((f) => {
    try { fs.writeFileSync(path.join(HERE, "_t.svg"), f.svg); execFileSync("xmllint", ["--noout", path.join(HERE, "_t.svg")], { stdio: "pipe" }); } catch (e) { console.log(`${id}: invalid SVG`); }
    if (!f.alt) console.log(`${id}: no alt text`);
  }));
  console.log(`sample: ${Object.values(map).reduce((n, f) => n + f.length, 0)} figures on ${Object.keys(map).length} questions`);
}
for (const N of ns.length ? ns : [1, 2, 3, 4]) {
  const mapFile = path.join(HERE, `p1map${N}.mjs`);
  if (!fs.existsSync(mapFile)) continue;
  const raw = (await import(mapFile)).default;
  const flat = Object.entries(raw).flatMap(([id, figs]) => figs.map((f) => [id, f]));
  const cropped = cropFigures(flat.map(([, f]) => f));
  const map = {};
  flat.forEach(([id], i) => (map[id] ||= []).push(cropped[i]));
  const file = path.join(EXAMS, `exam${N}.js`);
  const src = fs.readFileSync(file, "utf8");
  const header = src.split("\n")[0];
  const qs = new Function(src.replace(/export default[^;]*;?/, "") + `; return EXAM_${N}_QUESTIONS;`)();
  const problems = []; let count = 0;
  const ids = new Set(qs.map((q) => q.id));
  Object.keys(map).forEach((id) => { if (!ids.has(id)) problems.push(`${id}: no such question`); });
  const out = qs.map((q) => {
    const { figures, ...rest } = q;
    const figs = map[q.id];
    if (!figs) return rest;
    figs.forEach((f, i) => {
      if (!f.alt) problems.push(`${q.id}: figure ${i} has no alt text`);
      try { fs.writeFileSync(path.join(HERE, "_t.svg"), f.svg); execFileSync("xmllint", ["--noout", path.join(HERE, "_t.svg")], { stdio: "pipe" }); } catch (e) { problems.push(`${q.id}: invalid SVG: ${String(e.stderr || e.message).split("\n")[0]}`); }
      if (/NaN|undefined|Infinity/.test(f.svg)) problems.push(`${q.id}: bad number in SVG`);
    });
    count += figs.length;
    // keep the stem/choices/explanation keys in the same order, with figures after the stem
    const { id, unit, stem, ...tail } = rest;
    return { id, unit, stem, figures: figs, ...tail };
  });
  const body = `${header}\nconst EXAM_${N}_QUESTIONS = ${JSON.stringify(out, null, 2)};\n\nexport default EXAM_${N}_QUESTIONS;\n`;
  fs.writeFileSync(file, body);
  console.log(`exam${N}: ${count} figures on ${Object.keys(map).length} questions`, problems.length ? "\nPROBLEMS:\n" + problems.join("\n") : "- ok");
}
