import { S, M, G } from "./pool.mjs";
import * as B from "./biofigs.mjs";
const { fig, table, chart, barChart, curve, COL } = B;

export const config = { hub: "biology", prefix: "be", N: 1, file: "exam1.js", title: "AP Biology — Exam 1", seed: 5, units: { 1: 6, 2: 7, 3: 8, 4: 8, 5: 6, 6: 8, 7: 10, 8: 7 } };

const enzyme = chart({
  w: 520, h: 320, x: [0, 100, 20], y: [0, 1.1, 0.2], xLabel: "Temperature (°C)", yLabel: "Relative enzyme activity", legend: true, yFmt: (v) => v.toFixed(1),
  series: [
    { name: "Enzyme X", pts: curve((T) => (T <= 37 ? Math.exp(-(((T - 37) / 14) ** 2)) : Math.exp(-(((T - 37) / 5) ** 2))), 0, 100, 140), color: COL.a },
    { name: "Enzyme Y", pts: curve((T) => (T <= 75 ? Math.exp(-(((T - 75) / 22) ** 2)) : Math.exp(-(((T - 75) / 6) ** 2))), 0, 100, 140), color: COL.b },
  ],
});
const cellCycle = barChart({
  categories: ["G1", "S", "G2", "M"], w: 520, h: 320, y: [0, 70, 10], yLabel: "Cells in each phase (%)", xLabel: "Phase of the cell cycle",
  series: [{ name: "Control", vals: [60, 20, 12, 8], color: COL.a }, { name: "Drug X", vals: [20, 15, 55, 10], color: COL.b }],
});
const beaks = barChart({ categories: ["1976 (before drought)", "1978 (after drought)"], w: 480, h: 320, y: [0, 12, 2], yLabel: "Mean beak depth (mm)", series: [{ name: "Mean", vals: [9.2, 9.7], err: [0.1, 0.1], color: COL.a }] });
const predPrey = chart({
  w: 520, h: 320, x: [0, 30, 5], y: [0, 180, 30], xLabel: "Year", yLabel: "Population size (thousands)", legend: true,
  series: [
    { name: "Hare", pts: curve((t) => 100 + 60 * Math.sin((2 * Math.PI * t) / 10), 0, 30, 150), color: COL.a },
    { name: "Lynx", pts: curve((t) => 70 + 40 * Math.sin((2 * Math.PI * (t - 1.5)) / 10), 0, 30, 150), color: COL.b, dash: "6 4" },
  ],
});

export default [
  // ================= Unit 1 (6) =================
  M(1,
    "Some insects can walk across the surface of a pond without sinking. Which property of water best explains this?",
    ["Cohesion between water molecules, caused by hydrogen bonding, creates surface tension.",
     "Water is a universal solvent, so the insect's feet dissolve into the surface.",
     "Water has a high specific heat, which keeps the surface rigid.",
     "Water molecules are nonpolar and repel the insect's feet."],
    "Hydrogen bonds between neighboring water molecules make them cohesive, so the molecules at the surface are pulled inward and sideways, forming a film with surface tension that can support a small insect. Water is polar, not nonpolar."),
  M(1,
    "Which of the following classes of biological molecules always contains phosphorus?",
    ["Nucleic acids", "Proteins", "Carbohydrates", "Triglycerides"],
    "Each nucleotide in DNA and RNA contains a phosphate group, so nucleic acids contain phosphorus. Proteins contain C, H, O, and N (and sometimes S). Carbohydrates and triglycerides contain only C, H, and O."),
  G(1, {
    text: "A student tests four unknown solutions, A–D, with three reagents: Benedict's solution (blue; turns orange-red when heated with reducing sugars), biuret reagent (blue; turns purple with peptide bonds), and iodine solution (amber; turns blue-black with starch). The results are shown in the table.",
    figures: [table(["Solution", "Benedict's (after heating)", "Biuret", "Iodine"], [["A", "Blue", "Purple", "Amber"], ["B", "Orange-red", "Blue", "Amber"], ["C", "Blue", "Blue", "Blue-black"], ["D", "Blue", "Blue", "Amber"]])],
  }, [
    M(1, "Which solution most likely contains starch?",
      ["Solution C", "Solution A", "Solution B", "Solution D"],
      "Iodine turns blue-black in the presence of starch. Only solution C gave this result."),
    M(1, "Which solution most likely contains protein?",
      ["Solution A", "Solution B", "Solution C", "Solution D"],
      "The biuret reagent turns purple when it reacts with peptide bonds, so a positive result indicates protein. Only solution A turned purple."),
  ]),
  M(1,
    "Which level of protein structure is stabilized mainly by hydrogen bonds between atoms in the polypeptide backbone, forming α-helices and β-pleated sheets?",
    ["Secondary structure", "Primary structure", "Tertiary structure", "Quaternary structure"],
    "Secondary structure consists of local folding patterns (α-helices and β-sheets) held by hydrogen bonds between backbone atoms. Primary structure is the amino acid sequence (peptide bonds), tertiary structure is the 3-D shape stabilized by R-group interactions, and quaternary structure is the arrangement of multiple polypeptides."),
  S(1,
    "A solution with a pH of 5 has how many times the hydrogen ion concentration of a solution with a pH of 7?",
    ["10 times", "100 times", "1000 times", "10,000 times"], 1,
    "The pH scale is logarithmic. A difference of 2 pH units is a difference of 10² = 100 in [H⁺], and the lower pH has the higher [H⁺]. The solution with pH 5 has 100 times as much H⁺."),

  // ================= Unit 2 (7) =================
  M(2,
    "Which organelle is primarily responsible for modifying, sorting, and packaging proteins for secretion from the cell?",
    ["Golgi apparatus", "Smooth endoplasmic reticulum", "Lysosome", "Mitochondrion"],
    "The Golgi apparatus receives proteins from the rough ER, modifies them (for example, by adding carbohydrate groups), and packages them into vesicles for secretion or delivery to other organelles. Lysosomes digest materials, and mitochondria produce ATP."),
  S(2,
    "A cell is modeled as a cube with sides that are 2 μm long. What is the ratio of surface area to volume for the cell?",
    ["1.5 μm⁻¹", "3.0 μm⁻¹", "6.0 μm⁻¹", "12 μm⁻¹"], 1,
    "The surface area is 6 × (2 μm)² = 24 μm², and the volume is (2 μm)³ = 8 μm³. The ratio is 24/8 = 3.0 μm⁻¹. As cells grow larger, this ratio decreases, which limits how efficiently materials can be exchanged."),
  G(2, {
    text: "A U-shaped tube is divided into two sides by a membrane that is permeable to water but not to sucrose. At the start of the experiment, the two sides have equal volumes and contain sucrose solutions of different concentrations, as shown.",
    figures: [fig(B.uTube({ left: { label: "0.2 M sucrose", level: 0.6, dots: 4 }, right: { label: "0.6 M sucrose", level: 0.6, dots: 12 } }), "A U-shaped tube with a dashed membrane in the middle. The left side contains 0.2 molar sucrose with a few dots representing solute, and the right side contains 0.6 molar sucrose with many dots. Both sides start at the same liquid level.", { maxWidth: 380 })],
  }, [
    M(2, "In which direction is there a net movement of water across the membrane?",
      ["From the left side to the right side, because the right side has the lower water potential.",
       "From the right side to the left side, because the right side has more solute to dilute.",
       "There is no net movement, because the membrane is selectively permeable.",
       "Sucrose moves from the right side to the left side, followed by water."],
      "Water moves by osmosis from the region of higher water potential to the region of lower water potential. The right side has the higher solute concentration and therefore the lower (more negative) solute potential, so water moves toward it. Sucrose cannot cross the membrane."),
    M(2, "After the system reaches equilibrium, which statement describes the liquid levels?",
      ["The level on the right side is higher than the level on the left side.",
       "The level on the left side is higher than the level on the right side.",
       "The levels on both sides are equal, because the system is at equilibrium.",
       "The level on the right side is lower, because sucrose has moved across."],
      "Water has moved into the right side, raising its level. The rising pressure from the taller column (the pressure potential) eventually balances the difference in solute potential, so the system stops changing with the levels unequal."),
  ]),
  S(2,
    "A plant cell has a solute potential (Ψs) of −0.40 MPa and a pressure potential (Ψp) of +0.10 MPa. What is the water potential (Ψ) of the cell?",
    ["−0.50 MPa", "−0.30 MPa", "+0.30 MPa", "+0.50 MPa"], 1,
    "Water potential is the sum of the pressure potential and the solute potential: Ψ = Ψp + Ψs = (+0.10) + (−0.40) = −0.30 MPa."),
  M(2,
    "Which of the following processes requires the direct input of cellular energy (ATP)?",
    ["Movement of Na⁺ out of a cell and K⁺ into the cell by the sodium–potassium pump",
     "Diffusion of oxygen across the plasma membrane",
     "Movement of water through aquaporins",
     "Facilitated diffusion of glucose into a cell through a channel protein"],
    "The sodium–potassium pump moves ions against their concentration gradients, which is active transport and uses ATP. Diffusion, osmosis through aquaporins, and facilitated diffusion are all passive and move substances down their gradients."),
  M(2,
    "Which of the following structures is found in both prokaryotic and eukaryotic cells?",
    ["Ribosomes", "A nuclear envelope", "Mitochondria", "A Golgi apparatus"],
    "All cells contain ribosomes for protein synthesis. A nuclear envelope, mitochondria, and a Golgi apparatus are membrane-bound features of eukaryotic cells only."),

  // ================= Unit 3 (8) =================
  G(3, {
    text: "Two enzymes, X and Y, catalyze similar reactions in two different organisms. The activity of each enzyme was measured at several temperatures. The results are shown in the graph.",
    figures: [fig(enzyme, "A graph of relative enzyme activity against temperature. The curve for enzyme X peaks at 37 degrees Celsius and falls sharply above that. The curve for enzyme Y peaks near 75 degrees Celsius and falls sharply above that.")],
  }, [
    M(3, "Which organism is most likely the source of enzyme Y?",
      ["A bacterium that lives in a hot spring", "A human", "An Arctic fish", "A soil fungus that lives at 20 °C"],
      "Enzyme Y has its optimum near 75 °C, so it is adapted to function at high temperatures. This is characteristic of organisms that live in hot environments, such as bacteria in hot springs. Enzyme X, with an optimum at 37 °C, is consistent with a human enzyme."),
    M(3, "Which statement best explains the sharp decrease in the activity of enzyme X above 37 °C?",
      ["The high temperature disrupts the enzyme's three-dimensional shape and changes its active site.", "The enzyme runs out of substrate as the temperature rises, so the reaction slows.", "The high temperature breaks the peptide bonds that link the amino acids in the enzyme.", "The enzyme is converted into the product when the temperature exceeds its optimum."],
      "Heat disrupts the hydrogen bonds and other weak interactions that maintain the enzyme's tertiary structure, so the active site loses its shape and the enzyme is denatured. Peptide bonds are covalent and are not broken at these temperatures."),
  ]),
  M(3,
    "In many cells, energy released by the exergonic hydrolysis of ATP is used to drive endergonic reactions. Which statement best describes this process?",
    ["Energy coupling, in which an exergonic reaction powers an endergonic reaction", "Feedback inhibition, in which the product of a reaction inhibits an enzyme", "Allosteric activation, in which a bound molecule increases enzyme activity", "Fermentation, in which ATP is produced in the absence of any oxygen supply"],
    "Energy coupling links an exergonic reaction (ATP → ADP + Pᵢ) to an endergonic reaction, so that the overall free-energy change is negative and the process can proceed. The other terms describe regulation of enzymes or ATP production."),
  M(3,
    "In a plant cell, in which location do the light-dependent reactions of photosynthesis take place?",
    ["The thylakoid membranes of the chloroplast", "The stroma of the chloroplast", "The inner membrane of the mitochondrion", "The cytosol"],
    "The light-dependent reactions occur in the thylakoid membranes, where chlorophyll and the electron transport chain are located. The Calvin cycle takes place in the stroma."),
  S(3,
    "How many molecules of ATP are produced by substrate-level phosphorylation in glycolysis (a net gain) for each molecule of glucose that is converted to two molecules of pyruvate?",
    ["0", "2", "4", "36"], 1,
    "Glycolysis uses 2 ATP in the energy-investment phase and produces 4 ATP in the payoff phase, for a net gain of 2 ATP per glucose."),
  G(3, {
    text: "A student uses the floating leaf disk assay to investigate photosynthesis. Leaf disks are infiltrated with a bicarbonate solution so that they sink. When the disks photosynthesize, oxygen collects inside and the disks rise. The student measures the time for 50% of the disks to float under several different light intensities. The data are shown in the table.",
    figures: [table(["Light intensity (lux)", "Time for 50% of disks to float (min)"], [["0", "No disks floated"], ["100", "18"], ["400", "9"], ["800", "5"]])],
  }, [
    M(3, "Which of the following is the best conclusion from the data?",
      ["As the light intensity increases, the rate of photosynthesis increases.",
       "As the light intensity increases, the rate of cellular respiration decreases.",
       "Light intensity has no effect on photosynthesis.",
       "Photosynthesis requires more time when more light is present."],
      "A shorter time for the disks to float means that oxygen was produced faster, so the rate of photosynthesis was greater. The rate increased as the light intensity increased. With no light, no oxygen accumulated."),
    M(3, "Why did the disks in the 0 lux condition remain at the bottom?",
      ["Without light, the light-dependent reactions could not produce oxygen.",
       "Without light, the leaf cells cannot carry out cellular respiration.",
       "Without light, bicarbonate cannot be absorbed by the leaf cells.",
       "Without light, the density of the leaf tissue increases."],
      "The disks float because oxygen from the light-dependent reactions collects in the air spaces of the leaf. With no light, no oxygen is produced from photosynthesis, so the disks stay dense and remain sunk."),
  ]),
  S(3,
    "In the Calvin cycle, how many molecules of CO₂ must be fixed to produce one molecule of the three-carbon sugar glyceraldehyde-3-phosphate (G3P) that exits the cycle?",
    ["1", "2", "3", "6"], 2,
    "Each turn of the cycle fixes one CO₂ into a five-carbon molecule (RuBP). Three CO₂ must be fixed (three turns) to net one three-carbon G3P (3 carbons from 3 CO₂)."),

  // ================= Unit 4 (8) =================
  M(4,
    "A signaling molecule binds to a receptor on the surface of a target cell and triggers a series of phosphorylation reactions inside the cell. What is a major advantage of this type of signal transduction pathway?",
    ["The signal is amplified, so a few ligand molecules cause a large response", "The signaling molecule enters the nucleus and directly changes gene expression.", "The signal is passed from one cell to the next through gap junctions only", "The response occurs quickly because no enzymes are involved at any step"],
    "In a phosphorylation cascade, each activated enzyme can activate many molecules of the next enzyme, so the signal is amplified at every step. This allows a very low concentration of ligand to produce a large response."),
  M(4,
    "At the G₁ checkpoint of the cell cycle, a cell detects extensive DNA damage. Which of the following is the most likely outcome?",
    ["The cycle is halted for repair, or the cell undergoes apoptosis if repair fails", "The cell enters S phase immediately, and the damage is repaired during replication.", "The cell skips mitosis and enters G₀ permanently, where it never divides again.", "The damaged DNA is passed to both daughter cells without any change in the cell cycle."],
    "Checkpoints monitor the integrity of the cell and delay progress until problems are fixed. Proteins such as p53 halt the cycle for repair, and if the damage is too severe, they can trigger apoptosis to prevent the propagation of mutations."),
  G(4, {
    text: "Researchers treated cultured cells with Drug X and determined the percentage of cells in each phase of the cell cycle after 24 hours. Untreated cells were used as a control. The results are shown in the graph.",
    figures: [fig(cellCycle, "A bar graph of the percentage of cells in the G1, S, G2, and M phases for control cells and cells treated with Drug X. Control: G1 60, S 20, G2 12, M 8. Drug X: G1 20, S 15, G2 55, M 10.")],
  }, [
    M(4, "Which of the following is the best interpretation of the data?",
      ["Drug X causes cells to accumulate in the G₂ phase, so it likely blocks the transition into mitosis.",
       "Drug X causes cells to accumulate in the G₁ phase, so it likely blocks DNA replication.",
       "Drug X increases the rate of mitosis, because more cells are in M phase.",
       "Drug X has no effect on the cell cycle."],
      "The percentage of cells in G₂ increased from 12% in the control to 55% with Drug X, while the percentage in G₁ decreased. This pattern indicates that the cells are being held at the G₂/M transition, the point at which they would enter mitosis."),
    S(4, "What percentage of the control cells were in interphase?",
      ["8%", "60%", "80%", "92%"], 3,
      "Interphase consists of G₁, S, and G₂: 60 + 20 + 12 = 92%. The remaining 8% of cells were in mitosis (M phase)."),
  ]),
  S(4,
    "A diploid organism has 2n = 8 chromosomes in its somatic cells. How many chromosomes are in each of the cells produced at the end of meiosis?",
    ["2", "4", "8", "16"], 1,
    "Meiosis produces haploid cells, each with half the number of chromosomes of the parent cell: 8/2 = 4 chromosomes."),
  M(4,
    "A mutation in the p53 gene prevents the production of a functional p53 protein. Why does this mutation increase the risk of cancer?",
    ["The p53 protein normally halts the cell cycle or triggers apoptosis after DNA damage, so damaged cells keep dividing.", "The p53 protein is an enzyme that speeds up the cell cycle, so its absence causes cells to stop dividing.", "The p53 protein is a growth factor that stimulates division, so its absence slows the growth of tumors.", "The p53 protein repairs DNA by replacing damaged bases, so its absence prevents all DNA replication."],
    "p53 is a tumor suppressor. It activates repair, cell cycle arrest, or apoptosis when DNA is damaged. Without it, damaged cells can continue dividing and accumulate more mutations."),
  M(4,
    "Which of the following events during meiosis contributes most directly to genetic variation among the gametes of a single individual?",
    ["Crossing over and the independent assortment of homologous chromosomes", "The replication of the DNA during the S phase of the cell cycle", "The separation of sister chromatids during anaphase of meiosis II", "The attachment of spindle fibers to the kinetochores in prophase"],
    "Crossing over exchanges segments between homologous chromosomes, and independent assortment shuffles maternal and paternal chromosomes into gametes. Together they produce an enormous number of different gametes. DNA replication and spindle formation do not create variation."),
  S(4,
    "A culture of bacteria starts with one cell and the population doubles every 6 hours. Assuming no cells die, how many cells are present after 24 hours?",
    ["4", "8", "16", "24"], 2,
    "In 24 hours there are 24/6 = 4 doublings, so the population is 2⁴ = 16 cells."),

  // ================= Unit 5 (6) =================
  S(5,
    "Two pea plants that are heterozygous for two independently assorting genes (AaBb) are crossed. What is the probability that an offspring has the genotype aabb?",
    ["1/16", "1/8", "1/4", "9/16"], 0,
    "For each gene, the probability of the homozygous recessive genotype from an Aa × Aa cross is 1/4. Because the genes assort independently, the probability of aabb is (1/4)(1/4) = 1/16."),
  G(5, {
    text: "The pedigree shows the inheritance of a rare trait in a family. Filled symbols represent individuals who show the trait.",
    figures: [fig(B.pedigree({ people: [{ id: "a", x: 160, y: 50, sex: "M", aff: false, label: "I-1" }, { id: "b", x: 270, y: 50, sex: "F", aff: false, label: "I-2" }, { id: "c", x: 100, y: 160, sex: "F", aff: true, label: "II-1" }, { id: "d", x: 215, y: 160, sex: "M", aff: false, label: "II-2" }, { id: "e", x: 330, y: 160, sex: "F", aff: false, label: "II-3" }], couples: [["a", "b"]], kids: [{ parents: ["a", "b"], kids: ["c", "d", "e"] }], W: 440, H: 230 }), "A pedigree. Generation I has an unaffected father and an unaffected mother. Their three children in generation II are an affected daughter (II-1, filled circle), an unaffected son (II-2), and an unaffected daughter (II-3).", { maxWidth: 440 })],
  }, [
    M(5, "Which mode of inheritance is most consistent with this pedigree?",
      ["Autosomal recessive", "Autosomal dominant", "X-linked recessive", "Y-linked"],
      "Two unaffected parents had an affected daughter, so the trait must be recessive and both parents are carriers. An affected daughter of an unaffected father rules out X-linked recessive inheritance, because an affected daughter must receive a recessive X from her father."),
    S(5, "What is the probability that II-3, who does not show the trait, is a carrier of the allele?",
      ["1/4", "1/2", "2/3", "3/4"], 2,
      "Both parents are carriers (Aa × Aa). Among offspring who do not show the trait, the genotypes are AA (1/4) and Aa (2/4), so the probability of being a carrier is (2/4)/(3/4) = 2/3."),
  ]),
  M(5,
    "A recessive allele for color blindness is located on the X chromosome. A color-blind man and a woman who is homozygous for the normal allele have children. Which statement is correct?",
    ["All of their daughters will be carriers, and none of their sons will be color blind.",
     "All of their sons will be color blind, and none of their daughters will be carriers.",
     "Half of their sons and half of their daughters will be color blind.",
     "All of their children will be color blind."],
    "The father passes his X (with the recessive allele) to all of his daughters and his Y to all of his sons. The mother passes a normal X to every child. The daughters are therefore heterozygous carriers, and the sons receive a normal X from their mother and are not color blind."),
  S(5,
    "In a cross, a student expected a 3:1 phenotypic ratio among 120 offspring (90 dominant and 30 recessive). The student observed 84 dominant and 36 recessive offspring. What is the value of the chi-square statistic, χ² = Σ(o − e)²/e?",
    ["0.40", "1.20", "1.60", "3.84"], 2,
    "χ² = (84 − 90)²/90 + (36 − 30)²/30 = 36/90 + 36/30 = 0.40 + 1.20 = 1.60. With 1 degree of freedom the critical value at p = 0.05 is 3.84, so the null hypothesis is not rejected."),
  M(5,
    "Two genes are located on the same chromosome. In a testcross, the recombinant offspring make up 5% of the total in one cross involving genes A and B, and 30% in a cross involving genes A and C. What can be concluded?",
    ["Genes A and B are closer together on the chromosome than genes A and C.",
     "Genes A and C are closer together on the chromosome than genes A and B.",
     "Genes A and B are on different chromosomes.",
     "Genes A and C assort independently."],
    "Crossing over is more likely to occur between genes that are farther apart, so the recombination frequency increases with the distance between them. The lower frequency (5%) for A and B means they are closer together than A and C (30%). A frequency of 50% would indicate independent assortment."),

  // ================= Unit 6 (8) =================
  M(6,
    "RNA polymerase synthesizes an mRNA molecule by adding nucleotides in which direction, and using which strand as the template?",
    ["It adds nucleotides to the 3′ end of the growing mRNA, reading the template DNA strand 3′ to 5′.",
     "It adds nucleotides to the 5′ end of the growing mRNA, reading the template DNA strand 3′ to 5′.",
     "It adds nucleotides to the 3′ end of the growing mRNA, reading the template DNA strand 5′ to 3′.",
     "It adds nucleotides to either end, depending on the gene."],
    "Nucleic acids are always synthesized in the 5′ → 3′ direction, with new nucleotides added to the 3′ end. Because the strands are antiparallel, the polymerase must read the template strand in the 3′ → 5′ direction."),
  M(6,
    "In E. coli, the lac operon is regulated by a repressor protein. When lactose is present in the cell, what happens?",
    ["Allolactose binds the repressor, which releases the operator and allows transcription", "Lactose binds to the promoter and blocks the attachment of RNA polymerase", "Lactose binds directly to RNA polymerase and activates the enzyme", "The repressor binds more tightly to the operator and prevents transcription"],
    "The lac operon is an inducible operon. When lactose is present, allolactose binds to the repressor and changes its shape, so it can no longer bind to the operator. RNA polymerase can then transcribe the genes needed to metabolize lactose."),
  G(6, {
    text: "A circular plasmid was digested with a restriction enzyme. The undigested plasmid and the digested sample were separated by gel electrophoresis along with a DNA ladder of known fragment sizes. The gel is shown. The sizes of the ladder fragments are labeled in base pairs (bp).",
    figures: [fig(B.gel({ lanes: [{ label: "Ladder", bands: [0.1, 0.3, 0.5, 0.7, 0.9], sizes: ["5000", "3000", "2000", "1000", "500"] }, { label: "Undigested", bands: [0.2] }, { label: "Digested", bands: [0.5, 0.7] }] }), "A gel with three lanes. The ladder lane has bands at 5000, 3000, 2000, 1000, and 500 base pairs from top to bottom. The undigested lane has one band between 5000 and 3000. The digested lane has two bands, one at the 2000 base pair position and one at the 1000 base pair position.")],
  }, [
    S(6, "What is the approximate size of the plasmid?",
      ["1,000 bp", "2,000 bp", "3,000 bp", "6,000 bp"], 2,
      "The digested lane shows two fragments, at about 2000 bp and 1000 bp. The fragments from a circular plasmid with one cut for each of the two sites add up to the size of the plasmid: 2000 + 1000 = 3000 bp."),
    M(6, "Why do the smaller DNA fragments travel farther through the gel than the larger fragments?",
      ["Smaller fragments move more easily through the pores of the gel matrix.",
       "Smaller fragments carry a greater negative charge per unit length.",
       "Smaller fragments are attracted to the negative electrode.",
       "Smaller fragments are denatured by the electric current."],
      "DNA is negatively charged and migrates toward the positive electrode. The charge-to-mass ratio is the same for all fragment sizes, so the separation depends on how easily the fragments move through the gel: smaller fragments weave through the pores faster and travel farther."),
  ]),
  M(6,
    "A mutation results in the insertion of a single nucleotide in the middle of the coding sequence of a gene. Which of the following is the most likely result?",
    ["A frameshift mutation that changes the amino acids after the insertion", "A silent mutation that changes the DNA but not the protein sequence", "A missense mutation that replaces one amino acid in the protein", "A large deletion that removes the whole gene from the chromosome"],
    "The ribosome reads mRNA in groups of three nucleotides. Inserting one nucleotide shifts the reading frame for every codon that follows, changing all of the downstream amino acids and often introducing a premature stop codon."),
  S(6,
    "In a sample of double-stranded DNA, 30% of the nucleotides are adenine. What percentage of the nucleotides are cytosine?",
    ["20%", "30%", "40%", "70%"], 0,
    "Adenine pairs with thymine, so A = T = 30%, totaling 60%. The remaining 40% is divided equally between guanine and cytosine, so C = 20%."),
  M(6,
    "Which of the following best describes the role of an enhancer in the regulation of gene expression in eukaryotes?",
    ["A DNA sequence that binds activator proteins and increases transcription", "An RNA molecule that binds mRNA and destroys it before translation", "The region of the gene where the ribosome attaches to the mRNA", "An enzyme that adds the 5′ cap to the pre-mRNA in the nucleus"],
    "Enhancers are DNA regulatory sequences. When transcription factors (activators) bind to them, they promote the assembly of the transcription machinery at the promoter, increasing the rate of transcription of the associated gene."),
  M(6,
    "Which of the following events occurs during the processing of a eukaryotic pre-mRNA before the mRNA is translated?",
    ["Introns are spliced out, a 5′ cap is added, and a poly-A tail is added.", "Exons are removed from the transcript and the introns are joined together.", "The mRNA is converted into DNA by the enzyme reverse transcriptase.", "A ribosome attaches to the pre-mRNA while it is still in the nucleus."],
    "Eukaryotic pre-mRNA is modified in the nucleus. Introns (noncoding regions) are removed and the exons are spliced together, a modified guanine cap is added to the 5′ end, and a poly-A tail is added to the 3′ end. These modifications protect the mRNA and help in its export and translation."),

  // ================= Unit 7 (10) =================
  S(7,
    "In a population in Hardy–Weinberg equilibrium, the frequency of individuals with a recessive phenotype is 0.16. What is the frequency of heterozygous individuals in the population?",
    ["0.16", "0.36", "0.48", "0.60"], 2,
    "The frequency of the recessive phenotype is q² = 0.16, so q = 0.40 and p = 1 − 0.40 = 0.60. The frequency of heterozygotes is 2pq = 2(0.60)(0.40) = 0.48."),
  G(7, {
    text: "The cladogram shows the evolutionary relationships among five vertebrates. The table shows which of five characteristics are present (+) or absent (−) in each organism.",
    figures: [fig(B.cladogram({ tree: [[[["Mouse", "Lizard"], "Frog"], "Salmon"], "Lamprey"] }), "A cladogram of five vertebrates. Lamprey branches off first. Next to branch off is salmon, then frog. The last split separates mouse and lizard as sister groups."),
      table(["Organism", "Vertebral column", "Jaws", "Four limbs", "Amniotic egg", "Hair"], [["Lamprey", "+", "−", "−", "−", "−"], ["Salmon", "+", "+", "−", "−", "−"], ["Frog", "+", "+", "+", "−", "−"], ["Lizard", "+", "+", "+", "+", "−"], ["Mouse", "+", "+", "+", "+", "+"]])],
  }, [
    M(7, "Which organism is most closely related to the mouse?",
      ["Lizard", "Frog", "Salmon", "Lamprey"],
      "On a cladogram, relatedness is determined by recent common ancestry. The mouse and the lizard share the most recent common ancestor (they are sister taxa), so the lizard is the closest relative of the mouse in this tree."),
    M(7, "Which statement is best supported by the data?",
      ["The amniotic egg evolved once, in the common ancestor of the lizard and the mouse.", "The amniotic egg evolved independently in the lizard and in the mouse lineages.", "Four limbs evolved in the common ancestor of all five of the organisms shown.", "Jaws evolved once in the common ancestor of the lamprey and the salmon."],
      "The lizard and the mouse are the only organisms with the amniotic egg and they are sister taxa, so the most parsimonious explanation is that the trait evolved once in their common ancestor. Four limbs are absent in lamprey and salmon, and jaws are absent in the lamprey."),
  ]),
  M(7,
    "The forelimb of a human, the wing of a bat, and the flipper of a whale have similar bone arrangements but different functions. This is best explained by which of the following?",
    ["The structures are homologous, inherited with modification from a common ancestor.",
     "The structures are analogous, evolved independently to perform different functions.",
     "The structures are vestigial, having lost their function in each species.",
     "The structures result from convergent evolution in similar environments."],
    "Homologous structures share a similar underlying anatomy because they are inherited from a common ancestor, even though natural selection has modified them for different functions. Analogous structures, in contrast, have similar functions but different origins."),
  G(7, {
    text: "Beginning in 1977, a severe drought on an island greatly reduced the supply of small, soft seeds, leaving mostly large, hard seeds. Researchers measured the mean beak depth of a population of ground finches before and after the drought. Error bars show ±2 standard errors of the mean.",
    figures: [fig(beaks, "A bar graph of mean beak depth in millimeters. Before the drought in 1976 the mean is 9.2, and after the drought in 1978 it is 9.7. Each bar has small error bars of about 0.1.", { maxWidth: 460 })],
  }, [
    M(7, "Which statement best explains the change in mean beak depth?",
      ["Birds with deeper beaks cracked large seeds, survived, and reproduced more, so alleles for deeper beaks became more common.", "Individual birds grew deeper beaks during the drought because they needed to eat the large, hard seeds.", "The birds needed deeper beaks, so new mutations for deeper beaks appeared in response to the drought.", "Birds with shallow beaks moved to other islands, and their departure caused the remaining beaks to deepen."],
      "Natural selection acts on existing variation: during the drought, birds with deeper beaks had a survival and reproductive advantage because they could eat the available large seeds. If beak depth is heritable, the next generation has a higher mean beak depth. Individuals do not change their genes to meet a need."),
    M(7, "Which observation would be the best evidence that the change in beak depth is due to a change in allele frequencies rather than a direct effect of the environment?",
      ["The offspring of the surviving birds also have deeper beaks, even when raised in a different environment.", "The surviving birds spend most of their foraging time eating the large, hard seeds that remain.", "The mean beak depth was measured in the same year that the severe drought began on the island.", "The mean body mass of the birds decreased during the drought, along with the supply of seeds."],
      "If the trait is heritable, the deeper beaks should appear in offspring regardless of the environment in which they are raised. This would show that the change reflects a shift in the population's genes, not just an individual response to conditions."),
  ]),
  M(7,
    "Which of the following scenarios is an example of allopatric speciation?",
    ["A river changes course and splits a population of squirrels, and over many generations the two groups become reproductively isolated.",
     "A population of plants doubles its chromosome number in one generation and can no longer breed with the parent population.",
     "Two species of fruit flies interbreed and produce fertile hybrids.",
     "A population of birds slowly changes in beak size over time without splitting."],
    "Allopatric speciation occurs when a geographic barrier separates a population into two groups. Gene flow stops, and independent mutation, selection, and drift lead to divergence until the groups can no longer interbreed. The doubling of chromosome number is an example of sympatric speciation."),
  M(7,
    "A small number of individuals from a large population survive a natural disaster, and the allele frequencies in the surviving population differ from those in the original population. Which of the following best describes this event?",
    ["A population bottleneck, which is a type of genetic drift", "Natural selection, because the survivors had the fittest alleles", "Gene flow, because individuals moved between populations", "Sexual selection, because mates were chosen by a trait"],
    "A sharp reduction in population size by a random event (a bottleneck) causes the allele frequencies in the survivors to differ by chance from the original population. This is genetic drift. The survivors were not chosen because of their alleles, so it is not natural selection."),
  S(7,
    "In a population of 200 diploid individuals, 98 have the genotype AA, 84 have the genotype Aa, and 18 have the genotype aa. What is the frequency of the a allele in the population?",
    ["0.09", "0.21", "0.30", "0.42"], 2,
    "The population has 400 alleles. The number of a alleles is 84 (from Aa) + 2(18) (from aa) = 120. The frequency is 120/400 = 0.30."),
  M(7,
    "In the Miller–Urey experiment, a mixture of gases (methane, ammonia, hydrogen, and water vapor) was exposed to electrical sparks, and organic molecules, including amino acids, formed. What did this experiment demonstrate?",
    ["Organic molecules can form from simple inorganic substances on early Earth", "Living cells formed spontaneously from the simple gases in the apparatus", "Oxygen was abundant in Earth's early atmosphere and drove the reactions", "RNA was the first molecule that could replicate itself on early Earth"],
    "The experiment supports the hypothesis that the building blocks of life could have formed abiotically from simple molecules in an early atmosphere with an energy source, such as lightning. It did not produce cells and used an atmosphere without free oxygen."),

  // ================= Unit 8 (7) =================
  S(8,
    "A population of 500 mice has 60 births and 20 deaths in a year, with no immigration or emigration. What is the per capita population growth rate (r)?",
    ["0.04", "0.08", "0.12", "40"], 1,
    "The per capita growth rate is (births − deaths)/N = (60 − 20)/500 = 0.08 per individual per year."),
  G(8, {
    text: "The diagram shows the energy available at each trophic level of a food chain in an ecosystem. Energy values represent the energy stored in the biomass of each level.",
    figures: [fig(B.energyPyramid({ levels: [{ name: "Producers", value: "10,000 kJ" }, { name: "Primary consumers", value: "1,000 kJ" }, { name: "Secondary consumers", value: "100 kJ" }] }), "A pyramid with three levels. The bottom level, producers, has 10,000 kilojoules. The middle level, primary consumers, has 1,000 kilojoules. The top level, secondary consumers, has 100 kilojoules.", { maxWidth: 520 })],
  }, [
    M(8, "Which statement best explains why the energy decreases at each higher trophic level?",
      ["Most of the energy at each level is lost as heat or is not assimilated by the next level", "Consumers at higher trophic levels are less efficient at capturing the energy of sunlight directly", "Energy is converted into matter at each trophic level, so less remains available as energy", "Energy is recycled back to the producers by decomposers and is therefore not available above"],
      "At each transfer, most of the energy is used for the organism's own metabolism and is released as heat, and some biomass is not eaten or digested. Only about 10% of the energy is typically available to the next level. Energy flows through ecosystems and is not recycled."),
    S(8, "If the pattern shown continues, approximately how much energy would be available to tertiary consumers?",
      ["1 kJ", "10 kJ", "100 kJ", "1000 kJ"], 1,
      "Energy decreases by a factor of 10 at each level (10,000 → 1,000 → 100). The next level would have 100/10 = 10 kJ."),
  ]),
  M(8,
    "A forest is cleared by a fire, but the soil remains intact. Which of the following best describes the process by which the community recovers?",
    ["Secondary succession, which begins with soil that already has seeds", "Primary succession, which begins on bare rock with no soil present", "A climax community, which forms immediately after the fire ends", "Ecological equilibrium, which stops all further change in the forest"],
    "Secondary succession occurs in places where a community has been disturbed but the soil remains, so recovery is relatively fast. Primary succession begins in lifeless areas without soil, such as newly formed volcanic rock."),
  G(8, {
    text: "The graph shows changes in the sizes of a snowshoe hare population and a Canada lynx population over 30 years. Lynx are predators of hares.",
    figures: [fig(predPrey, "A graph of population size in thousands against time in years. Both the hare and lynx populations oscillate with a period of about 10 years. The lynx peaks occur slightly after the hare peaks.")],
  }, [
    M(8, "Which statement best explains why the lynx population peaks after the hare population?",
      ["An increase in the hare population provides more food, so the lynx population grows after a delay.",
       "The lynx population increases first and causes the hare population to increase.",
       "Lynx and hares compete for the same food, so their populations rise and fall independently.",
       "Hares are consumers of lynx, so the hare population controls the lynx population."],
      "The abundant prey (hares) support more lynx reproduction and survival, but it takes time for the predator population to respond, so its peak lags behind the prey peak. Then the high number of lynx reduces the hare population."),
    M(8, "Which concept is best illustrated by the cyclic pattern in the graph?",
      ["Negative feedback between predator and prey populations",
       "Exponential growth with no limiting factors",
       "Primary succession",
       "Positive feedback that increases both populations indefinitely"],
      "As the hare population rises, the lynx population rises and then reduces the hares, which in turn reduces the lynx. Each population's growth causes a change that opposes it, which is the essence of negative feedback and produces oscillations."),
  ]),
  S(8,
    "A community has three species with the following numbers of individuals: species 1 has 50, species 2 has 30, and species 3 has 20. What is the Simpson's diversity index, D = 1 − Σ(n/N)²?",
    ["0.38", "0.50", "0.62", "1.38"], 2,
    "The proportions are 0.50, 0.30, and 0.20. Σ(n/N)² = 0.25 + 0.09 + 0.04 = 0.38, so D = 1 − 0.38 = 0.62. A higher value indicates greater diversity."),
];
