import { S, M, G } from "./pool.mjs";
import * as B from "./biofigs.mjs";
const { fig, table, chart, barChart, curve, COL } = B;

export const config = { hub: "biology", prefix: "be", N: 2, file: "exam2.js", title: "AP Biology — Exam 2", seed: 15, units: { 1: 5, 2: 7, 3: 9, 4: 7, 5: 6, 6: 8, 7: 10, 8: 8 } };

const mm = chart({
  w: 520, h: 320, x: [0, 30, 5], y: [0, 10, 2], xLabel: "Substrate concentration (mM)", yLabel: "Reaction rate (μmol/min)", legend: true,
  series: [
    { name: "No inhibitor", pts: curve((s) => (10 * s) / (2 + s), 0, 30, 120), color: COL.a },
    { name: "With inhibitor", pts: curve((s) => (10 * s) / (6 + s), 0, 30, 120), color: COL.b, dash: "6 4" },
  ],
});
const resistance = chart({
  w: 520, h: 320, x: [0, 25, 5], y: [0, 100, 20], xLabel: "Days of antibiotic exposure", yLabel: "Resistant bacteria in culture (%)",
  series: [{ name: "Resistant", pts: curve((t) => 100 / (1 + 99 * Math.exp(-0.35 * t)), 0, 25, 100), color: COL.a }],
});
const logistic = chart({
  w: 520, h: 320, x: [0, 20, 4], y: [0, 600, 100], xLabel: "Time (weeks)", yLabel: "Population size",
  series: [{ name: "N", pts: curve((t) => 500 / (1 + 49 * Math.exp(-0.5 * t)), 0, 20, 120), color: COL.a }],
});

export default [
  // ================= Unit 1 (5) =================
  M(1,
    "Which pair of functional groups is found in every amino acid?",
    ["An amino group and a carboxyl group", "A hydroxyl group and a phosphate group", "A carbonyl group and a sulfhydryl group", "A methyl group and a carboxyl group"],
    "Every amino acid has a central carbon bonded to an amino group (–NH₂), a carboxyl group (–COOH), a hydrogen, and a variable R group. The R group is what differs among the 20 amino acids."),
  M(1,
    "Compared with a saturated fatty acid, an unsaturated fatty acid has which of the following features?",
    ["One or more carbon–carbon double bonds that put kinks in its tail", "Fewer carbon atoms in a straight, tightly packed chain", "A hydrophilic tail that dissolves easily in water", "A phosphate group in place of the carboxyl group"],
    "Unsaturated fatty acids contain at least one C=C double bond, which bends the hydrocarbon chain. The kinks keep the molecules from packing tightly, so unsaturated fats such as oils are usually liquid at room temperature."),
  S(1,
    "A polypeptide is built from 10 amino acids joined by dehydration synthesis reactions. How many water molecules are released as the polypeptide is formed?",
    ["8", "9", "10", "11"], 1,
    "Each peptide bond forms with the release of one water molecule. Joining 10 amino acids in a chain requires 10 − 1 = 9 peptide bonds, so 9 water molecules are released."),
  M(1,
    "Which end of a DNA strand has a free phosphate group attached to the 5′ carbon of the terminal sugar?",
    ["The 5′ end of the strand", "The 3′ end of the strand", "Both ends of the strand", "Neither end of the strand"],
    "A DNA strand has directionality. The 5′ end has a phosphate group on the 5′ carbon of the sugar, and the 3′ end has a free hydroxyl group on the 3′ carbon. New nucleotides are added to the 3′ end."),
  M(1,
    "In a folded protein, hydrophobic R groups tend to cluster in the interior of the molecule, away from water. Which type of interaction drives this clustering?",
    ["Hydrophobic interactions that exclude nonpolar groups from water", "Peptide bonds that form between the nonpolar R groups of the protein", "Ionic bonds between the nonpolar R groups and the surrounding water", "Covalent bonds that form between the nonpolar side chains in the interior"],
    "Nonpolar R groups cannot form hydrogen bonds with water, so the surrounding water molecules force them together in the interior of the protein. This hydrophobic effect is a major contributor to tertiary structure."),

  // ================= Unit 2 (7) =================
  M(2,
    "Which of the following structures is found in plant cells but not in animal cells?",
    ["Chloroplasts", "Mitochondria", "Ribosomes", "A nucleus"],
    "Plant cells contain chloroplasts, where photosynthesis occurs, along with a cell wall and a large central vacuole. Animal cells and plant cells both contain mitochondria, ribosomes, and a nucleus."),
  S(2,
    "Cell A is a sphere with a radius of 1 μm, and cell B is a sphere with a radius of 4 μm. How does the surface area-to-volume ratio of cell A compare with that of cell B? (For a sphere, SA/V = 3/r.)",
    ["1/4 as large", "The same", "4 times as large", "16 times as large"], 2,
    "SA/V = 3/r, so cell A has a ratio of 3/1 = 3 μm⁻¹ and cell B has 3/4 = 0.75 μm⁻¹. The ratio for cell A is 4 times as large. Smaller cells exchange materials more efficiently with their surroundings."),
  G(2, {
    text: "Pieces of onion epidermis were placed in sucrose solutions of different concentrations. After 20 minutes, the percentage of cells in which the cell membrane had pulled away from the cell wall (plasmolysis) was determined. The data are shown in the table.",
    figures: [table(["Sucrose concentration (M)", "Cells plasmolyzed (%)"], [["0.0", "0"], ["0.2", "10"], ["0.4", "45"], ["0.6", "95"]])],
  }, [
    S(2, "Based on the data, which concentration of sucrose is closest to the solute concentration inside the onion cells?",
      ["0.0 M", "0.2 M", "0.4 M", "0.6 M"], 2,
      "At a sucrose concentration equal to the solute concentration inside the cells, there is no net water movement and about half of the cells are at the point of plasmolysis. About 45% of the cells were plasmolyzed at 0.4 M, so that concentration is closest."),
    M(2, "Why were most of the cells plasmolyzed in the 0.6 M sucrose solution?",
      ["Water left the cells by osmosis because the solution had a lower water potential.", "Sucrose moved into the cells by diffusion and made the cells swell up.", "The cell walls dissolved when placed in the concentrated sucrose solution.", "The cells took up water from the solution by active transport."],
      "The 0.6 M solution has a lower water potential than the cells, so water moves out by osmosis. The cytoplasm shrinks and the membrane pulls away from the rigid cell wall. Sucrose does not move freely across the membrane."),
  ]),
  M(2,
    "Glucose enters a red blood cell through a carrier protein, moving from a region of high glucose concentration to a region of low concentration, without the use of ATP. This is an example of which process?",
    ["Facilitated diffusion", "Active transport", "Simple diffusion through the lipid bilayer", "Receptor-mediated endocytosis"],
    "Glucose is a polar molecule that cannot cross the lipid bilayer by itself. A carrier protein helps it move down its concentration gradient without energy input, which is facilitated diffusion, a form of passive transport."),
  M(2,
    "Mitochondria contain their own circular DNA, ribosomes similar to those of bacteria, and a double membrane. Which hypothesis do these features support?",
    ["Mitochondria originated from a prokaryote engulfed by an ancestral eukaryotic cell.", "Mitochondria developed from the folded inner membrane of the nucleus.", "Mitochondria were produced by the endoplasmic reticulum.", "Mitochondria are viruses that infect eukaryotic cells."],
    "The endosymbiotic theory proposes that mitochondria (and chloroplasts) were once free-living prokaryotes engulfed by a host cell. Their prokaryote-like DNA, ribosomes, and double membrane are evidence for this origin."),
  S(2,
    "The solute potential of a 0.20 M sucrose solution at 300 K is calculated using Ψs = −iCRT, where i = 1 for sucrose, R = 0.0831 L·bar/(mol·K), and C is the molar concentration. What is the solute potential?",
    ["−4.99 bar", "−2.49 bar", "+2.49 bar", "+4.99 bar"], 0,
    "Ψs = −iCRT = −(1)(0.20 mol/L)(0.0831 L·bar/(mol·K))(300 K) = −4.99 bar. The solute potential of a solution is always negative (or zero for pure water)."),

  // ================= Unit 3 (9) =================
  G(3, {
    text: "The graph shows the rate of an enzyme-catalyzed reaction at different substrate concentrations, with and without a competitive inhibitor present.",
    figures: [fig(mm, "A graph of reaction rate in micromoles per minute against substrate concentration in millimolar. The curve without inhibitor rises steeply and levels off near 10. The curve with the inhibitor rises more slowly but also approaches 10 at high substrate concentrations.")],
  }, [
    M(3, "Which statement best explains why the two curves approach the same maximum rate at very high substrate concentrations?",
      ["At high concentrations, the substrate outcompetes the inhibitor for active sites", "The inhibitor is destroyed once the substrate concentration becomes high", "The inhibitor changes the shape of the enzyme at all concentrations", "The substrate is converted into more inhibitor at high concentrations"],
      "A competitive inhibitor binds to the active site and competes with the substrate. When the substrate concentration is very high, substrate molecules occupy almost all of the active sites, so the maximum rate is the same. The inhibitor lowers the apparent affinity of the enzyme but not its maximum rate."),
    M(3, "Where would a competitive inhibitor most likely bind to the enzyme?",
      ["At the active site, which has a shape similar to the substrate", "At a separate allosteric site far from the active site", "To the product after the reaction occurs", "To the substrate in the solution"],
      "Competitive inhibitors resemble the substrate and bind to the active site, preventing the substrate from binding. Binding at an allosteric site would be noncompetitive inhibition, which would lower the maximum rate at any substrate concentration."),
  ]),
  M(3,
    "In some metabolic pathways, the final product binds to the first enzyme in the pathway and decreases its activity. What is this type of regulation called?",
    ["Feedback inhibition", "Competitive inhibition", "Substrate-level phosphorylation", "Positive feedback"],
    "When the end product inhibits an earlier enzyme in its own pathway, the cell avoids wasting resources by making more than it needs. This is feedback (end-product) inhibition, a form of negative feedback."),
  S(3,
    "During the complete aerobic respiration of one molecule of glucose (C₆H₁₂O₆), how many molecules of CO₂ are released?",
    ["2", "4", "6", "36"], 2,
    "The six carbons of glucose are all released as CO₂: two from the conversion of pyruvate to acetyl CoA (two pyruvates) and four from the citric acid cycle, for a total of 6 CO₂."),
  M(3,
    "What is the primary role of the proton (H⁺) gradient that is established across the inner mitochondrial membrane during aerobic respiration?",
    ["It provides the energy that drives ATP synthase to make ATP", "It transports glucose into the mitochondrial matrix for breakdown", "It carries electrons directly from NADH to molecular oxygen", "It breaks pyruvate down into carbon dioxide and water"],
    "The electron transport chain pumps protons into the intermembrane space, creating a gradient. Protons flow back into the matrix through ATP synthase, and this flow drives the phosphorylation of ADP to ATP (chemiosmosis)."),
  G(3, {
    text: "A student measured the rate of oxygen consumption (a measure of cellular respiration) in germinating pea seeds and in non-germinating pea seeds at two temperatures. The data are shown in the table.",
    figures: [table(["Seeds", "Temperature (°C)", "O₂ consumed (mL/min)"], [["Germinating", "10", "1.2"], ["Germinating", "25", "3.6"], ["Non-germinating", "10", "0.1"], ["Non-germinating", "25", "0.1"]])],
  }, [
    M(3, "Which statement best explains why the germinating seeds consumed more oxygen at 25 °C than at 10 °C?",
      ["The enzymes of respiration are more active at the higher temperature.", "The seeds produce more oxygen at the higher temperature.", "The seeds stop respiring at the lower temperature.", "Oxygen is less soluble in water at the lower temperature."],
      "Metabolic reaction rates generally increase with temperature (up to an optimum) because molecules move faster and the enzymes are more active. The higher oxygen consumption reflects a higher rate of aerobic respiration."),
    M(3, "What is the purpose of including the non-germinating seeds in the experiment?",
      ["They show the baseline oxygen use of seeds that are not actively metabolizing", "They demonstrate that temperature has no effect on the rate of respiration", "They produce the oxygen that the germinating seeds need to respire", "They are the only seeds in the experiment that contain mitochondria"],
      "The dormant seeds have very low metabolic activity, so they show that the change in oxygen consumption in the germinating seeds is due to their growth and respiration, not to the setup or to the temperature alone."),
  ]),
  M(3,
    "In the Calvin cycle, which of the following molecules from the light-dependent reactions provides the energy and reducing power needed to make sugar?",
    ["ATP and NADPH", "Oxygen and water", "Pyruvate and NADH", "Glucose and CO₂"],
    "The light-dependent reactions produce ATP and NADPH, which are used in the Calvin cycle to reduce the fixed CO₂ into three-carbon sugars. Oxygen is released as a by-product of the light reactions."),
  S(3,
    "Approximately how many molecules of ATP are produced from one molecule of glucose during complete aerobic cellular respiration in a eukaryotic cell?",
    ["2", "4", "30", "90"], 2,
    "Glycolysis and the citric acid cycle produce a few ATP directly, and the electron transport chain and chemiosmosis produce most of the rest. The total is approximately 30–32 ATP per glucose, compared with 2 ATP from fermentation."),

  // ================= Unit 4 (7) =================
  M(4,
    "A growth factor released by one cell diffuses a short distance and stimulates the division of nearby cells. Which type of signaling is this?",
    ["Paracrine signaling", "Endocrine signaling", "Signaling through gap junctions", "Direct contact signaling"],
    "In paracrine signaling, the signal molecules act on nearby cells in the immediate vicinity. In endocrine signaling, hormones travel through the bloodstream to distant cells."),
  S(4,
    "In a sample of 200 cultured cells observed under a microscope, 20 cells are in mitosis. If the entire cell cycle takes 24 hours, approximately how long does the average cell spend in mitosis?",
    ["0.24 h", "1.2 h", "2.4 h", "10 h"], 2,
    "The fraction of cells in mitosis is 20/200 = 0.10, so the cells spend about 10% of the cycle in mitosis: (0.10)(24 h) = 2.4 h."),
  G(4, {
    text: "A student examined 400 cells from an onion root tip under a microscope and recorded the phase of the cell cycle for each cell. The data are shown in the table.",
    figures: [table(["Phase", "Number of cells"], [["Interphase", "340"], ["Prophase", "40"], ["Metaphase", "10"], ["Anaphase", "5"], ["Telophase", "5"]])],
  }, [
    S(4, "What percentage of the cells were in mitosis?",
      ["5%", "15%", "60%", "85%"], 1,
      "The cells in mitosis are those in prophase, metaphase, anaphase, and telophase: 40 + 10 + 5 + 5 = 60 of 400 cells, or 15%."),
    S(4, "If the cell cycle for these cells takes 24 hours, approximately how long does a cell spend in prophase?",
      ["0.60 h", "2.4 h", "3.6 h", "12 h"], 1,
      "The fraction of cells in prophase is 40/400 = 0.10, so the time spent in prophase is (0.10)(24 h) = 2.4 h."),
  ]),
  M(4,
    "During the development of a human embryo, the tissue between the fingers is removed by programmed cell death. Which process is responsible?",
    ["Apoptosis", "Necrosis", "Mitosis", "Meiosis"],
    "Apoptosis is a regulated, orderly process of cell death that eliminates unneeded cells during development, such as the webbing between developing fingers. Necrosis is uncontrolled cell death caused by injury."),
  M(4,
    "Down syndrome is most commonly caused by an extra copy of chromosome 21. Which event during meiosis most likely resulted in the extra chromosome?",
    ["Nondisjunction, in which chromosomes fail to separate normally", "Crossing over between two chromosomes that are not homologous", "Independent assortment of the chromosomes during anaphase II", "Deletion of a large segment of one of the chromosomes"],
    "Nondisjunction produces gametes with an extra or missing chromosome. If a gamete with two copies of chromosome 21 is fertilized by a normal gamete, the zygote has three copies (trisomy 21)."),
  M(4,
    "Which of the following events occurs during meiosis I but not during mitosis?",
    ["Homologous chromosomes pair up and then separate into different cells", "Sister chromatids separate from each other during anaphase", "The nuclear envelope breaks down in prophase of the division", "Chromosomes line up along the middle of the cell before separating"],
    "In meiosis I, homologous chromosomes pair (synapsis) and are separated, which reduces the chromosome number by half. In mitosis, homologous chromosomes do not pair; sister chromatids separate."),

  // ================= Unit 5 (6) =================
  S(5,
    "A heterozygous plant (Aa) is crossed with a homozygous recessive plant (aa). What is the probability that an offspring has the genotype aa?",
    ["0", "1/4", "1/2", "3/4"], 2,
    "The Aa parent produces A and a gametes in equal proportions, and the aa parent produces only a gametes. Half of the offspring are Aa and half are aa."),
  G(5, {
    text: "A student crossed two pea plants that were both heterozygous for seed shape and seed color (RrYy × RrYy) and recorded the phenotypes of 556 offspring. The observed and expected numbers (based on a 9:3:3:1 ratio) are shown in the table.",
    figures: [table(["Phenotype", "Observed", "Expected"], [["Round, yellow", "315", "312.75"], ["Round, green", "108", "104.25"], ["Wrinkled, yellow", "101", "104.25"], ["Wrinkled, green", "32", "34.75"]])],
  }, [
    S(5, "What is the value of the chi-square statistic for these data?",
      ["0.47", "1.5", "7.81", "15.7"], 0,
      "χ² = Σ(o − e)²/e = (2.25)²/312.75 + (3.75)²/104.25 + (3.25)²/104.25 + (2.75)²/34.75 = 0.016 + 0.135 + 0.101 + 0.218 = 0.47."),
    M(5, "The critical value for 3 degrees of freedom at p = 0.05 is 7.81. What conclusion should the student draw?",
      ["Fail to reject the null hypothesis; the differences are likely due to chance.", "Reject the null hypothesis; the differences show that the genes are linked.", "Reject the null hypothesis; the traits do not follow Mendelian inheritance.", "The data cannot be analyzed, because the observed numbers are not whole numbers."],
      "The calculated χ² (0.47) is smaller than the critical value (7.81), so the difference between the observed and expected numbers is not statistically significant. The data are consistent with the 9:3:3:1 ratio expected for independently assorting genes."),
  ]),
  M(5,
    "A person with blood type AB has the genotype IᴬIᴮ. Which pattern of inheritance does the AB blood type illustrate?",
    ["Codominance, in which both alleles are fully expressed", "Incomplete dominance, in which the phenotype is a blend", "Epistasis, in which one gene masks another", "Complete dominance, in which one allele masks the other"],
    "In codominance, the heterozygote shows the phenotypes of both alleles at the same time. A person with type AB blood has red blood cells that carry both the A and B antigens."),
  M(5,
    "In Labrador retrievers, one gene determines whether black or brown pigment is produced, and a second gene determines whether any pigment is deposited in the fur at all. Dogs that are homozygous recessive for the second gene are yellow, regardless of the first gene. Which term describes this interaction?",
    ["Epistasis", "Incomplete dominance", "Codominance", "Polygenic inheritance"],
    "Epistasis occurs when the alleles of one gene affect the expression of another gene. Here the genotype at the second gene masks the effect of the pigment-type gene."),
  S(5,
    "A man and a woman who are both unaffected have a child with cystic fibrosis, an autosomal recessive disorder. They have a second child who is unaffected. What is the probability that the second child is a carrier?",
    ["1/4", "1/2", "2/3", "3/4"], 2,
    "The parents must both be carriers (Cc). Among unaffected children, the genotypes are CC (1/3) and Cc (2/3), so the probability the unaffected child is a carrier is 2/3."),

  // ================= Unit 6 (8) =================
  M(6,
    "During DNA replication, which enzyme joins the Okazaki fragments on the lagging strand?",
    ["DNA ligase", "DNA helicase", "Primase", "RNA polymerase"],
    "On the lagging strand, DNA polymerase synthesizes short Okazaki fragments, and DNA ligase seals the gaps between them to form a continuous strand. Helicase unwinds the DNA, and primase lays down the RNA primers."),
  S(6,
    "The coding region of a gene contains 900 nucleotides, not counting the stop codon. Assuming no introns, how many amino acids are in the polypeptide that the gene specifies?",
    ["100", "300", "450", "900"], 1,
    "Each amino acid is specified by a codon of three nucleotides, so 900 nucleotides code for 900/3 = 300 amino acids."),
  M(6,
    "During translation, the anticodon of a tRNA molecule base pairs with which of the following?",
    ["A codon in the mRNA", "A sequence in the DNA template", "The large ribosomal subunit", "The poly-A tail of the mRNA"],
    "Each tRNA carries a specific amino acid and has an anticodon that is complementary to an mRNA codon. This pairing in the ribosome ensures that the correct amino acid is added to the growing polypeptide."),
  G(6, {
    text: "A normal gene produces an mRNA containing the codon GAA, which codes for glutamic acid (Glu). Three different mutations change this codon. The codons and the amino acids they specify are shown in the table.",
    figures: [table(["Mutant", "Altered codon", "Result"], [["1", "GAG", "Glu (glutamic acid)"], ["2", "GAC", "Asp (aspartic acid)"], ["3", "UAA", "Stop"]])],
  }, [
    M(6, "Which mutation is a silent mutation?",
      ["Mutant 1", "Mutant 2", "Mutant 3", "None of the mutations"],
      "A silent mutation changes the DNA sequence but not the amino acid, because of the redundancy of the genetic code. GAG, like GAA, codes for glutamic acid, so the protein is unchanged."),
    M(6, "Which mutation is most likely to have the most severe effect on the function of the protein?",
      ["Mutant 3, because a premature stop codon shortens the protein", "Mutant 1, because it changes the sequence of the nucleotides in the gene", "Mutant 2, because it changes one amino acid in the polypeptide", "All three mutations have equal effects on the function of the protein"],
      "A nonsense mutation creates a stop codon, so translation ends early and the protein is truncated, usually losing its function. A missense mutation changes a single amino acid, which may or may not affect function."),
  ]),
  S(6,
    "In the polymerase chain reaction (PCR), the amount of DNA doubles with each cycle. Starting with a single DNA molecule, how many copies are present after 5 cycles?",
    ["10", "25", "32", "64"], 2,
    "The number of copies doubles each cycle, so after 5 cycles there are 2⁵ = 32 copies."),
  M(6,
    "In the CRISPR-Cas9 system, a guide RNA directs the Cas9 enzyme to a specific location in the genome. What does the Cas9 enzyme do at that location?",
    ["It cuts the DNA at the target sequence.", "It adds a methyl group to the RNA.", "It translates the guide RNA into a protein.", "It seals the gaps between Okazaki fragments."],
    "The guide RNA base pairs with a complementary DNA sequence, and Cas9 acts as a nuclease that makes a double-stranded break there. The cell's repair processes can then disable the gene or incorporate a new sequence."),
  M(6,
    "In eukaryotic cells, the addition of methyl groups to DNA in a region of a chromosome is often associated with which of the following effects?",
    ["Reduced transcription of the genes in that region", "Increased transcription of the genes in that region", "A change in the sequence of the genes", "Degradation of the mRNA in the cytoplasm"],
    "DNA methylation is an epigenetic modification that does not change the DNA sequence. It typically promotes a tightly packed chromatin structure that makes genes less accessible to transcription machinery, so gene expression is silenced."),

  // ================= Unit 7 (10) =================
  S(7,
    "In a population in Hardy–Weinberg equilibrium for a gene with two alleles, the frequency of the dominant allele (p) is 0.7. What is the frequency of individuals with the homozygous recessive genotype?",
    ["0.09", "0.21", "0.42", "0.49"], 0,
    "Since p + q = 1, q = 0.3. The frequency of the homozygous recessive genotype is q² = (0.3)² = 0.09."),
  G(7, {
    text: "Bacteria were grown in a culture and exposed to an antibiotic. The graph shows the percentage of bacteria in the culture that were resistant to the antibiotic over 25 days.",
    figures: [fig(resistance, "A graph of the percentage of resistant bacteria against days of antibiotic exposure. The percentage starts near 1 percent, rises slowly for the first 5 days, then rises rapidly between days 10 and 20, and levels off near 100 percent.")],
  }, [
    M(7, "Which statement best explains the increase in the percentage of resistant bacteria?",
      ["Bacteria with resistance alleles survived and reproduced while others were killed.", "The antibiotic caused the bacteria to develop resistance alleles on purpose.", "The bacteria learned how to resist the antibiotic during the experiment.", "The antibiotic increased the mutation rate of all genes in the bacterial cells."],
      "The antibiotic is a selective pressure. A few bacteria already carried alleles for resistance (from random mutation). They survived and reproduced, so the proportion of resistant bacteria increased over generations."),
    M(7, "Which of the following statements about the origin of the resistance alleles is most accurate?",
      ["The alleles arose by random mutation before exposure, and the antibiotic selected for them.", "The antibiotic directed specific mutations to arise in the bacteria.", "The resistance alleles arose only after the antibiotic had been added.", "All of the bacteria in the culture carried the resistance alleles at the start."],
      "Mutations occur randomly and are not directed by the environment. The resistant bacteria were present at a low frequency (about 1%) at the start, and selection increased the frequency of resistance."),
  ]),
  M(7,
    "Two closely related species of birds live in the same area but do not interbreed because the males of each species sing a different song that the females of the other species do not respond to. Which type of reproductive barrier is this?",
    ["Prezygotic isolation (behavioral isolation)", "Postzygotic isolation (hybrid sterility)", "Geographic isolation", "Postzygotic isolation (hybrid breakdown)"],
    "Behavioral isolation is a prezygotic barrier: differences in courtship signals prevent mating, so no zygote is formed. Postzygotic barriers act after fertilization, for example when hybrids are sterile."),
  G(7, {
    text: "The table shows the number of amino acid differences in the cytochrome c protein between humans and four other organisms.",
    figures: [table(["Organism compared with humans", "Amino acid differences in cytochrome c"], [["Chimpanzee", "0"], ["Rhesus monkey", "1"], ["Horse", "12"], ["Yeast", "44"]])],
  }, [
    M(7, "Which organism is most closely related to humans, according to these data?",
      ["Chimpanzee", "Rhesus monkey", "Horse", "Yeast"],
      "Fewer differences in a conserved protein sequence indicate a more recent common ancestor, because fewer mutations have accumulated. The chimpanzee has no differences from humans."),
    M(7, "Which statement is best supported by the data?",
      ["Related organisms have similar proteins because of common ancestry.", "Yeast is the ancestor of all of the other organisms in the table.", "Evolution has occurred only in the lineage that leads to humans.", "Cytochrome c has not changed in any of the organisms that were compared."],
      "Similarity in homologous molecules, which decreases as the evolutionary distance between organisms increases, is evidence for common ancestry and descent with modification. A larger number of differences indicates a more distant common ancestor."),
  ]),
  M(7,
    "A few individuals from a mainland population colonize an island. The allele frequencies in the island population differ from those of the mainland population, mainly because of the small number of founders. This is an example of which of the following?",
    ["The founder effect, a type of genetic drift", "Directional selection, a type of natural selection", "Gene flow, the movement of alleles between populations", "Stabilizing selection, which favors intermediate phenotypes"],
    "When a new population is established by a small number of individuals, its gene pool contains only a fraction of the variation of the source population, and the allele frequencies can differ by chance. This is the founder effect."),
  S(7,
    "In a population of 500 individuals in Hardy–Weinberg equilibrium, the frequency of the recessive allele q is 0.20. How many individuals are expected to be heterozygous?",
    ["16", "80", "160", "320"], 2,
    "With q = 0.20, p = 0.80. The frequency of heterozygotes is 2pq = 2(0.80)(0.20) = 0.32, so the number of heterozygotes is 0.32 × 500 = 160."),
  M(7,
    "Which of the following is a condition that must be met for a population to remain in Hardy–Weinberg equilibrium?",
    ["The population is very large, so genetic drift has a negligible effect.", "Individuals mate preferentially with similar phenotypes.", "Mutations occur at a high rate.", "Individuals frequently migrate in and out of the population."],
    "The Hardy–Weinberg model assumes a large population (no genetic drift), random mating, no mutation, no gene flow, and no natural selection. A small population would experience genetic drift that changes the allele frequencies."),
  S(7,
    "A fossil contains one-eighth of the amount of carbon-14 that was present in the organism when it died. The half-life of carbon-14 is 5,730 years. What is the approximate age of the fossil?",
    ["5,730 years", "11,460 years", "17,190 years", "45,840 years"], 2,
    "One-eighth is (1/2)³, so three half-lives have passed: 3 × 5,730 = 17,190 years."),

  // ================= Unit 8 (8) =================
  S(8,
    "A population of 100 rabbits is growing exponentially with a per capita growth rate of r = 0.20 per year. What is the approximate increase in the population during the first year (dN/dt = rN)?",
    ["2 rabbits", "20 rabbits", "100 rabbits", "120 rabbits"], 1,
    "dN/dt = rN = (0.20)(100) = 20 rabbits per year at the start. The population is 120 after one year, but the question asks for the increase."),
  G(8, {
    text: "The graph shows the growth of a population of insects introduced into a new habitat over 20 weeks.",
    figures: [fig(logistic, "A graph of population size against time in weeks. The population starts near 10 and increases slowly at first, then rapidly between about weeks 5 and 10, and levels off near 500 after week 14.")],
  }, [
    S(8, "What is the approximate carrying capacity of the habitat for this population?",
      ["50", "250", "500", "1000"], 2,
      "The carrying capacity is the maximum population size that the environment can sustain. The graph levels off at approximately 500 individuals."),
    S(8, "At approximately what population size is the growth rate of the population the greatest?",
      ["50", "250", "500", "1000"], 1,
      "In logistic growth, the growth rate dN/dt = rN(K − N)/K is greatest when N = K/2. With K ≈ 500, the maximum growth rate occurs at about 250 individuals."),
  ]),
  M(8,
    "The removal of sea otters from a kelp forest ecosystem leads to a large increase in sea urchins and the destruction of the kelp. Which term describes the sea otter in this ecosystem?",
    ["Keystone species", "Invasive species", "Primary producer", "Decomposer"],
    "A keystone species has an effect on its community that is much larger than its abundance would suggest. Sea otters keep urchin populations in check, which protects the kelp that supports many other species."),
  M(8,
    "Certain bacteria in the soil and in the roots of legumes convert atmospheric nitrogen gas (N₂) into ammonia. What is this process called, and why is it important?",
    ["Nitrogen fixation, which makes nitrogen available to plants in a usable form", "Denitrification, which returns nitrogen to the atmosphere", "Nitrification, which converts nitrate to nitrogen gas", "Decomposition, which converts organic matter to carbon dioxide"],
    "Most organisms cannot use N₂ directly. Nitrogen-fixing bacteria convert it to ammonia, which can be taken up by plants and incorporated into amino acids and nucleotides."),
  G(8, {
    text: "Two communities of the same four species of insects were sampled in a field. The numbers of individuals of each species are shown in the table. Simpson's diversity index is D = 1 − Σ(n/N)².",
    figures: [table(["Species", "Community 1", "Community 2"], [["A", "25", "85"], ["B", "25", "5"], ["C", "25", "5"], ["D", "25", "5"]])],
  }, [
    S(8, "What is the value of Simpson's diversity index for community 2?",
      ["0.27", "0.50", "0.73", "0.85"], 0,
      "The proportions in community 2 are 0.85, 0.05, 0.05, and 0.05. Σ(n/N)² = 0.7225 + 3(0.0025) = 0.73, so D = 1 − 0.73 = 0.27."),
    M(8, "Which statement correctly compares the two communities?",
      ["Community 1 has greater diversity because the species are equally abundant.", "Community 2 has greater diversity because one species is very abundant.", "The two communities have the same diversity because they have the same number of species.", "Community 2 has greater diversity because it has a higher total population."],
      "Both communities have four species (equal species richness), but diversity also depends on evenness. Community 1 has the higher Simpson's index (0.75) because the species are equally abundant; community 2 is dominated by species A."),
  ]),
  M(8,
    "A species of predatory fish is introduced into a lake, and the population of small fish that it feeds on declines sharply. As a result, the amount of algae in the lake increases. Which concept does this sequence of events illustrate?",
    ["A trophic cascade", "Primary succession", "Genetic drift", "Biomagnification"],
    "A trophic cascade occurs when a change at one trophic level has indirect effects on other trophic levels. Here the predator reduces the small fish, which allows the populations that the small fish feed on (zooplankton, which graze on algae) to increase, and algae growth leads to changes down the chain."),
];
