import { S, M, G } from "./pool.mjs";
import * as B from "./biofigs.mjs";
const { fig, table, chart, barChart, curve, COL } = B;

export const config = { hub: "biology", prefix: "be", N: 3, file: "exam3.js", title: "AP Biology — Exam 3", seed: 25, units: { 1: 6, 2: 6, 3: 8, 4: 8, 5: 6, 6: 9, 7: 10, 8: 7 } };

const buffer = chart({
  w: 520, h: 320, x: [0, 10, 2], y: [0, 8, 1], xLabel: "Volume of 0.1 M HCl added (mL)", yLabel: "pH of the solution", legend: true,
  series: [
    { name: "Solution X", pts: curve((v) => 7 - 5 * (1 - Math.exp(-0.45 * v)), 0, 10, 80), color: COL.a },
    { name: "Solution Y", pts: curve((v) => 7 - 0.06 * v, 0, 10, 20), color: COL.b, dash: "6 4" },
  ],
});
const photoLight = chart({
  w: 520, h: 320, x: [0, 100, 20], y: [0, 18, 3], xLabel: "Light intensity (% of full sunlight)", yLabel: "Rate of CO₂ uptake (μmol/m²/s)", legend: true,
  series: [
    { name: "0.04% CO₂", pts: curve((L) => (10 * L) / (15 + L), 0, 100, 100), color: COL.a },
    { name: "0.10% CO₂", pts: curve((L) => (16 * L) / (15 + L), 0, 100, 100), color: COL.b },
  ],
});
const cyclin = chart({
  w: 520, h: 300, x: [0, 48, 8], y: [0, 1.0, 0.2], xLabel: "Time (hours)", yLabel: "Relative cyclin B level", yFmt: (v) => v.toFixed(1),
  series: [{ name: "Cyclin B", pts: curve((t) => 0.5 + 0.5 * Math.sin((2 * Math.PI * (t - 14)) / 24), 0, 48, 150), color: COL.a }],
});
const moths = barChart({ categories: ["1850", "1895", "1990"], w: 480, h: 320, y: [0, 100, 20], yLabel: "Dark-colored moths in population (%)", xLabel: "Year", series: [{ name: "Dark morph", vals: [5, 95, 10], color: COL.a }] });

export default [
  // ================= Unit 1 (6) =================
  M(1,
    "Large bodies of water such as lakes and oceans moderate the temperature of nearby land. Which property of water is mainly responsible for this effect?",
    ["Its high specific heat, caused by hydrogen bonding between its molecules", "Its low density as a solid, which allows ice to float on the liquid", "Its ability to dissolve a wide variety of ionic compounds in solution", "Its cohesion between molecules, which produces a high surface tension"],
    "Water absorbs or releases a large amount of heat for a small temperature change because heat must first break hydrogen bonds. This high specific heat lets large bodies of water warm and cool slowly, which stabilizes the temperature of the surrounding region."),
  M(1,
    "Two glucose molecules are joined to form a disaccharide. Which type of bond links the two monosaccharides?",
    ["A glycosidic bond formed by dehydration synthesis", "A peptide bond formed by hydrolysis", "A phosphodiester bond formed by dehydration synthesis", "An ester bond formed by hydrolysis"],
    "Monosaccharides are joined by glycosidic linkages that form when a water molecule is removed (dehydration synthesis). Peptide bonds join amino acids, and phosphodiester bonds join nucleotides."),
  S(1,
    "A triglyceride is broken down by hydrolysis. How many fatty acid molecules are released from each molecule of triglyceride, along with one molecule of glycerol?",
    ["1", "2", "3", "4"], 2,
    "A triglyceride is made of one glycerol molecule joined to three fatty acids by ester linkages. Hydrolysis of all three bonds releases three fatty acids and one glycerol."),
  M(1,
    "Starch and cellulose are both polymers of glucose, but humans can digest starch and not cellulose. Which statement best explains this?",
    ["The glycosidic linkages differ in orientation, and human enzymes cannot break those in cellulose", "Cellulose is made of a different monosaccharide than starch, which human enzymes cannot recognize", "Starch contains peptide bonds that human enzymes can break, while cellulose does not", "Cellulose is too small to be digested, since human enzymes act only on large polymers"],
    "Starch has α-glycosidic linkages, whereas cellulose has β-glycosidic linkages, which give the polymer a straight, rigid structure. Human digestive enzymes recognize the α-linkages but not the β-linkages."),
  G(1, {
    text: "A student added drops of 0.1 M HCl to two solutions, X and Y, that both started at pH 7.0, and measured the pH after each addition. One solution was pure water and the other was a buffer. The results are shown in the graph.",
    figures: [fig(buffer, "A graph of pH against volume of HCl added. Solution X falls quickly from pH 7 to about pH 2. Solution Y falls only slightly, from pH 7 to about pH 6.4, over 10 milliliters.")],
  }, [
    M(1, "Identify the solution that is acting as a buffer.",
      ["Solution Y, because its pH changed only slightly", "Solution X, because its pH changed the most", "Both solutions, because both started at pH 7", "Neither solution, because the pH changed in both"],
      "A buffer resists changes in pH when small amounts of acid or base are added. Solution Y shows only a small decrease in pH, so it is the buffer. Pure water has no buffering capacity, and its pH drops sharply."),
    M(1, "Which statement best explains how the buffer minimizes the change in pH?",
      ["It contains a weak acid and its conjugate base that bind or release H⁺ ions", "It contains a strong acid that neutralizes the added HCl", "It prevents H⁺ from dissolving in water", "It converts the added H⁺ into hydroxide ions by a covalent reaction"],
      "A buffer includes a weak acid–conjugate base pair. When acid is added, the base form combines with the extra H⁺; when base is added, the acid form releases H⁺. This keeps the H⁺ concentration nearly constant."),
  ]),

  // ================= Unit 2 (6) =================
  M(2,
    "Cells that specialize in secreting large amounts of protein, such as the cells of the pancreas that make digestive enzymes, contain an abundance of which organelle?",
    ["Rough endoplasmic reticulum", "Smooth endoplasmic reticulum", "Peroxisomes", "Chloroplasts"],
    "Ribosomes attached to the rough ER synthesize proteins that are destined for secretion or for membranes. A cell that makes and secretes many proteins therefore has an extensive rough ER."),
  M(2,
    "In the plasma membrane, phospholipids are arranged in a bilayer. Which statement best explains this arrangement?",
    ["The hydrophilic heads face the aqueous environments and the hydrophobic tails face each other.", "The hydrophobic heads face the aqueous environments and the hydrophilic tails face each other.", "The phospholipids are covalently bonded in two layers.", "The cholesterol molecules hold the layers together by hydrogen bonds."],
    "Phospholipids are amphipathic. In water, the polar heads interact with the water on both sides of the membrane, while the nonpolar fatty acid tails cluster together in the interior, away from water."),
  S(2,
    "Calculate the water potential of a plant cell whose solute potential is −0.60 MPa and whose pressure potential is +0.35 MPa.",
    ["−0.95 MPa", "−0.25 MPa", "+0.25 MPa", "+0.95 MPa"], 1,
    "Ψ = Ψp + Ψs = (+0.35) + (−0.60) = −0.25 MPa."),
  G(2, {
    text: "A U-shaped tube is separated into two sides by a membrane that is permeable to water but not to solutes. The left side is filled with a 0.5 M NaCl solution (each NaCl dissociates into two ions) and the right side with a 0.8 M glucose solution (glucose does not dissociate). Both sides start at the same level.",
    figures: [fig(B.uTube({ left: { label: "0.5 M NaCl", level: 0.6, dots: 8 }, right: { label: "0.8 M glucose", level: 0.6, dots: 6 } }), "A U-shaped tube with a dashed membrane in the middle. The left side contains 0.5 molar NaCl with several dots representing dissolved ions, and the right side contains 0.8 molar glucose with slightly fewer dots. Both sides start at the same level.", { maxWidth: 380 })],
  }, [
    M(2, "In which direction will there be a net movement of water?",
      ["From the right side to the left side, because the left side has the higher total solute concentration", "From the left side to the right side, because the right side has the higher molarity", "There will be no net movement, because the molarities are similar", "From the left side to the right side, because NaCl is a smaller molecule"],
      "Water potential depends on the total number of dissolved particles. The 0.5 M NaCl solution produces about 1.0 M of particles (two ions per formula unit), which is more than the 0.8 M of glucose particles. The left side has the lower water potential, so water moves into it."),
    M(2, "After the system reaches equilibrium, which side will have the higher liquid level?",
      ["The left side", "The right side", "Both sides will be equal", "It cannot be determined"],
      "Water moves toward the left side, which has the higher solute concentration, so the liquid level on the left rises. The level continues to rise until the pressure from the extra column of liquid balances the difference in solute potential."),
  ]),
  M(2,
    "Which structure of the cytoskeleton forms the spindle fibers that separate chromosomes during cell division?",
    ["Microtubules", "Microfilaments", "Intermediate filaments", "Cell wall fibers"],
    "Microtubules, made of tubulin, assemble into the spindle apparatus that attaches to chromosomes and moves them. Microfilaments are involved in cell movement and cytokinesis, and intermediate filaments provide structural support."),

  // ================= Unit 3 (8) =================
  G(3, {
    text: "The graph shows the rate of CO₂ uptake by a plant's leaves at different light intensities under two atmospheric CO₂ concentrations.",
    figures: [fig(photoLight, "A graph of CO2 uptake rate against light intensity. Both curves rise and then level off. The curve at 0.04 percent CO2 levels off near 10 and the curve at 0.10 percent CO2 levels off near 16.")],
  }, [
    M(3, "What is the factor that limits the rate of photosynthesis in the plant at high light intensity under 0.04% CO₂?",
      ["The concentration of CO₂", "The intensity of the light", "The concentration of chlorophyll", "The temperature of the leaves"],
      "At high light intensities, increasing the light does not increase the rate (the curve levels off). The rate is higher at 0.10% CO₂, which shows that the CO₂ concentration is limiting the rate at 0.04%."),
    M(3, "Which statement best explains why the rate increases with the light intensity at low light?",
      ["More light increases the rate of the light reactions that supply ATP and NADPH", "More light increases the amount of CO₂ available inside the leaf for fixation", "More light causes the stomata to close, which increases the concentration of CO₂", "More light reduces the need for chlorophyll, so the leaf can make more sugar"],
      "At low intensities, the light reactions are limited by the supply of photons. More light produces more ATP and NADPH for the Calvin cycle, so more CO₂ is fixed."),
  ]),
  M(3,
    "In the light-dependent reactions, photosystem II splits water. What is the primary role of this reaction?",
    ["It replaces the electrons lost from the reaction center of photosystem II", "It provides the carbon atoms that are used to build sugars in the Calvin cycle", "It produces the CO₂ that is later fixed by rubisco in the stroma", "It generates ATP directly by substrate-level phosphorylation in the thylakoid"],
    "Water is split into electrons, protons, and oxygen. The electrons replace those that photosystem II passes to the electron transport chain, the protons add to the thylakoid gradient, and oxygen is released as a by-product."),
  S(3,
    "How many molecules of NADH are produced by glycolysis from one molecule of glucose?",
    ["0", "2", "4", "10"], 1,
    "In the energy-payoff phase of glycolysis, two molecules of NAD⁺ are reduced to NADH per glucose (one for each G3P). Glycolysis also produces a net of 2 ATP."),
  M(3,
    "When yeast cells carry out fermentation in the absence of oxygen, which products are formed?",
    ["Ethanol and carbon dioxide", "Lactic acid and water", "Oxygen and glucose", "Carbon dioxide and water"],
    "In alcohol fermentation, pyruvate is converted to ethanol with the release of CO₂, which regenerates the NAD⁺ needed for glycolysis to continue. Lactic acid fermentation occurs in animal muscle cells."),
  G(3, {
    text: "A student measured the activity of the enzyme catalase, which breaks down hydrogen peroxide into water and oxygen, at different pH values. The volume of O₂ produced in 2 minutes is shown in the table.",
    figures: [table(["pH", "Volume of O₂ produced (mL)"], [["3", "1"], ["5", "6"], ["7", "10"], ["9", "5"], ["11", "1"]])],
  }, [
    M(3, "What is the optimum pH of the enzyme, based on the data?",
      ["About pH 7", "About pH 3", "About pH 11", "The enzyme works equally well at all pH values"],
      "The enzyme produced the greatest volume of oxygen at pH 7, so this is the pH at which its activity is highest."),
    M(3, "Which statement best explains why the activity is low at pH 3?",
      ["The low pH alters the charges on R groups, changing the enzyme's shape and active site.", "The low pH removes the substrate from the solution so the enzyme cannot bind it.", "The low pH breaks the peptide bonds that link the amino acids in the enzyme.", "The low pH makes the substrate too large to fit into the active site of the enzyme."],
      "Changes in pH alter the charges on amino acid side chains, which disrupts the hydrogen bonds and ionic interactions that maintain the enzyme's tertiary structure. The active site is distorted and the enzyme becomes less effective or is denatured."),
  ]),
  M(3,
    "A chemical reaction has a negative change in free energy (ΔG < 0). Which statement is correct?",
    ["The reaction is exergonic and spontaneous, although it may be slow without a catalyst.", "The reaction is endergonic, so it requires a continuous input of energy to proceed.", "The reaction is at equilibrium, so the forward and reverse rates are exactly equal.", "The reaction will occur quickly, because a negative ΔG always means a fast reaction."],
    "A negative ΔG means the products have less free energy than the reactants, so the reaction is exergonic and thermodynamically favorable. The rate of the reaction depends on the activation energy, not on ΔG."),

  // ================= Unit 4 (8) =================
  M(4,
    "Which of the following regulates the progression of a cell through the cell cycle?",
    ["Cyclins that activate cyclin-dependent kinases", "Ribosomes that attach to the spindle", "DNA ligase that joins Okazaki fragments", "Centrioles that produce ATP"],
    "Cyclin levels rise and fall through the cycle. Cyclins bind to and activate cyclin-dependent kinases (CDKs), which phosphorylate target proteins that drive the cell from one phase of the cycle to the next."),
  M(4,
    "Normal cells in culture stop dividing when they come in contact with neighboring cells, but cancer cells continue to divide and pile up. What does this observation indicate about cancer cells?",
    ["They have lost the normal response to signals that regulate the cell cycle.", "They have lost the ability to carry out mitosis, so they divide in a different way.", "They contain far more DNA than normal cells, which causes them to divide.", "They are unable to respond to any chemical signals from neighboring cells."],
    "In normal cells, contact with neighbors sends signals that halt the cycle (contact inhibition). Cancer cells ignore these signals, because the pathways that control the cycle have been altered by mutations."),
  G(4, {
    text: "The graph shows the level of cyclin B in a population of cells over 48 hours. The cells divide every 24 hours, and the cells enter mitosis when the cyclin B level reaches its peak.",
    figures: [fig(cyclin, "A graph of relative cyclin B level against time in hours. The level oscillates, with peaks at about 20 hours and 44 hours and low points at about 8 hours and 32 hours.")],
  }, [
    M(4, "At approximately what time do the cells enter mitosis?",
      ["20 hours and 44 hours", "8 hours and 32 hours", "0 hours and 24 hours", "14 hours and 38 hours"],
      "The cells enter mitosis when cyclin B reaches its peak, which the graph shows at about 20 hours and again at about 44 hours (24 hours later)."),
    M(4, "Which statement best explains the rise and fall in the level of cyclin B?",
      ["Cyclin is synthesized during the cycle and degraded after mitosis, which resets the cycle", "Cyclin is a permanent part of the nuclear envelope and moves in and out of view", "Cyclin is produced only when the cells are in the G₀ phase of the cell cycle", "Cyclin is made only after cell division is complete and is never broken down"],
      "Cyclin B accumulates and activates CDK to trigger mitosis, and it is then degraded as the cell exits mitosis. The periodic synthesis and breakdown of cyclin help produce the oscillations that drive the cell cycle."),
  ]),
  S(4,
    "How many chromatids are in a human somatic cell at metaphase of mitosis? (A human somatic cell has 46 chromosomes.)",
    ["23", "46", "92", "184"], 2,
    "After the S phase, each of the 46 chromosomes consists of two sister chromatids, so a cell in metaphase contains 46 × 2 = 92 chromatids (still 46 chromosomes)."),
  M(4,
    "Many signal transduction pathways are turned off when the signal is no longer present. Which type of enzyme is involved in reversing the effects of protein kinases?",
    ["Protein phosphatases, which remove phosphate groups from proteins", "DNA polymerases, which add nucleotides to a growing DNA strand", "Proteases, which join amino acids into longer polypeptide chains", "Ligases, which seal gaps between fragments of a DNA strand"],
    "Kinases add phosphate groups to proteins, which activates or inactivates them. Phosphatases remove the phosphates, which returns the proteins to their original state and ends the response."),
  M(4,
    "Bacteria in a biofilm release signaling molecules and respond when the concentration of these molecules reaches a threshold, which tells the bacteria how many of them are present. What is this process called?",
    ["Quorum sensing", "Apoptosis", "Endocrine signaling", "Meiosis"],
    "In quorum sensing, bacteria secrete and detect small signaling molecules, so they can coordinate behaviors such as bioluminescence or biofilm formation when the population density is high enough."),
  S(4,
    "A cell has 2n = 6 chromosomes. Ignoring crossing over, how many different combinations of chromosomes can be present in the gametes produced by this organism through independent assortment?",
    ["3", "6", "8", "64"], 2,
    "The number of possible combinations is 2ⁿ, where n is the haploid number. With n = 3, there are 2³ = 8 possible combinations."),

  // ================= Unit 5 (6) =================
  S(5,
    "Hemophilia is caused by a recessive allele on the X chromosome. A woman who is a carrier of the allele has children with a man who does not have hemophilia. What is the probability that a son of this couple will have hemophilia?",
    ["0", "1/4", "1/2", "3/4"], 2,
    "The mother passes either the normal X or the X with the hemophilia allele with equal probability. A son receives his X from his mother, so he has a 1/2 chance of inheriting the allele and having the disorder."),
  G(5, {
    text: "The pedigree shows a rare trait in three generations of a family. Filled symbols represent individuals who show the trait.",
    figures: [fig(B.pedigree({ people: [{ id: "a", x: 120, y: 40, sex: "M", aff: false, label: "I-1" }, { id: "b", x: 220, y: 40, sex: "F", aff: false, label: "I-2" }, { id: "c", x: 90, y: 135, sex: "M", aff: true, label: "II-1" }, { id: "d", x: 250, y: 135, sex: "F", aff: false, label: "II-2" }, { id: "e", x: 350, y: 135, sex: "M", aff: false, label: "II-3" }, { id: "f", x: 270, y: 230, sex: "M", aff: true, label: "III-1" }, { id: "g", x: 380, y: 230, sex: "F", aff: false, label: "III-2" }], couples: [["a", "b"], ["d", "e"]], kids: [{ parents: ["a", "b"], kids: ["c", "d"] }, { parents: ["d", "e"], kids: ["f", "g"] }], W: 460, H: 290 }), "A three-generation pedigree. In generation I, an unaffected father and mother have an affected son (II-1) and an unaffected daughter (II-2). II-2 marries an unaffected man (II-3), and they have an affected son (III-1) and an unaffected daughter (III-2).", { maxWidth: 460 })],
  }, [
    M(5, "How is the trait in this pedigree most likely inherited?",
      ["X-linked recessive", "Autosomal dominant", "Autosomal recessive", "Y-linked"],
      "Only males are affected, and the trait passes from an unaffected mother (a carrier) to an affected son in each generation, skipping through unaffected females. This pattern is characteristic of X-linked recessive inheritance. Y-linked traits pass from father to son."),
    S(5, "What is the probability that III-2 is a carrier of the trait allele?",
      ["0", "1/4", "1/2", "3/4"], 2,
      "II-2 must be a carrier, because she has an affected son. Her husband is unaffected (X^A Y), so a daughter receives his normal X and has a 1/2 chance of receiving her mother's X with the trait allele."),
  ]),
  M(5,
    "A breeder crosses a pea plant that has the dominant phenotype with a plant that has the recessive phenotype. Half of the offspring have the dominant phenotype and half have the recessive phenotype. What is the genotype of the dominant parent?",
    ["Heterozygous", "Homozygous dominant", "Homozygous recessive", "It cannot be determined"],
    "This testcross reveals the genotype of the unknown parent. If the dominant parent were homozygous dominant, all offspring would show the dominant phenotype. A 1:1 ratio means the dominant parent is heterozygous (Aa × aa)."),
  M(5,
    "Human skin color varies continuously from light to dark, rather than falling into distinct categories. Which pattern of inheritance best explains this?",
    ["Polygenic inheritance, with several genes contributing to the phenotype", "Complete dominance at a single gene with two alleles that are expressed", "Codominance of two alleles, both of which are fully expressed in heterozygotes", "X-linked inheritance, in which the gene is carried on the X chromosome"],
    "Traits that show continuous variation are usually determined by many genes, each making a small contribution, and are also influenced by the environment. Such traits are described as polygenic."),
  S(5,
    "Three genes assort independently. Two individuals that are both heterozygous for all three genes (AaBbCc × AaBbCc) are crossed. What is the probability that an offspring shows the dominant phenotype for all three traits?",
    ["1/64", "9/64", "27/64", "3/4"], 2,
    "For each gene, the probability of the dominant phenotype in an Aa × Aa cross is 3/4. For the three independent genes: (3/4)³ = 27/64."),

  // ================= Unit 6 (9) =================
  M(6,
    "Ribosomal RNA (rRNA) is a major component of the ribosome. Which statement best describes the function of rRNA?",
    ["It helps catalyze the formation of peptide bonds during translation.", "It carries the code for a protein from the nucleus to the cytoplasm.", "It carries amino acids to the ribosome.", "It is the template for the synthesis of DNA."],
    "The ribosome's catalytic activity is performed by rRNA, which acts as a ribozyme to join amino acids by peptide bonds. mRNA carries the genetic message, and tRNA brings amino acids."),
  S(6,
    "How many different codons are possible if each codon is a sequence of three nucleotides, and each position can be occupied by any of the four RNA bases?",
    ["16", "20", "61", "64"], 3,
    "Each of the three positions can be filled in 4 ways, so there are 4³ = 64 possible codons. Of these, 61 code for amino acids and 3 are stop codons."),
  M(6,
    "In humans, one gene can produce several different proteins through alternative splicing. How does alternative splicing produce different proteins from the same pre-mRNA?",
    ["Different combinations of exons are joined to form different mature mRNAs.", "Different DNA strands are used as the template.", "The ribosome reads the mRNA in a different direction each time.", "Different introns are translated into proteins."],
    "In alternative splicing, exons from the same pre-mRNA are included or skipped in different combinations, producing mRNAs with different coding sequences. This greatly increases the number of proteins that the genome can produce."),
  G(6, {
    text: "A DNA fingerprinting analysis was used to determine the father of a child. DNA from the mother, the child, and two possible fathers (A and B) was cut with restriction enzymes and separated by gel electrophoresis. The gel is shown.",
    figures: [fig(B.gel({ lanes: [{ label: "Mother", bands: [0.2, 0.5] }, { label: "Child", bands: [0.2, 0.7] }, { label: "Man A", bands: [0.3, 0.5] }, { label: "Man B", bands: [0.7, 0.4] }] }), "A gel with four lanes. The mother has bands at positions 0.2 and 0.5. The child has bands at 0.2 and 0.7. Man A has bands at 0.3 and 0.5. Man B has bands at 0.7 and 0.4.")],
  }, [
    M(6, "Which man is the most likely father of the child?",
      ["Man B, because he has a band that matches the child's non-maternal band", "Man A, because he shares a band of the same size with the mother", "Man A, because the pattern of his bands is the same as the mother's pattern", "Neither man, because neither man's bands match all of the child's bands"],
      "A child inherits half of the bands from each parent. The child's band at position 0.2 matches the mother, so the other band, at 0.7, must come from the father. Man B has a band at 0.7 and Man A does not."),
    M(6, "Why do DNA fragments of the same size appear at the same position on the gel?",
      ["Fragments of the same size move through the gel at the same rate.", "Fragments of the same size have the same sequence.", "All fragments are attracted to the same electrode.", "The electric current stops each fragment at a specific position."],
      "In gel electrophoresis, DNA moves toward the positive electrode at a rate that depends on its size, so fragments of equal length travel the same distance. (Fragments of the same length may still have different sequences.)"),
  ]),
  M(6,
    "The trp operon in E. coli is a repressible operon. What happens to the expression of the trp genes when tryptophan is abundant in the cell?",
    ["Tryptophan binds the repressor, which then binds the operator and blocks transcription.", "Tryptophan binds the promoter and activates RNA polymerase.", "Tryptophan removes the repressor from the operator, so transcription increases.", "Tryptophan is converted into lactose."],
    "In a repressible operon, the end product (tryptophan) acts as a corepressor. When it binds the repressor, the complex binds the operator and blocks RNA polymerase, so the cell stops making tryptophan when enough is present."),
  S(6,
    "A linear DNA molecule 6,000 base pairs long is digested with a restriction enzyme that cuts the DNA at two different sites. How many fragments are produced?",
    ["2", "3", "4", "6,000"], 1,
    "Each cut in a linear DNA molecule divides it into one more fragment than the number of cuts: 2 cuts produce 3 fragments."),
  M(6,
    "Bacteria are transformed with a plasmid that carries a gene for ampicillin resistance, and are then spread on plates that contain ampicillin. What is the purpose of the ampicillin in this procedure?",
    ["It selects for the bacteria that have taken up the plasmid.", "It causes the bacteria to take up the plasmid.", "It increases the rate at which the bacteria divide.", "It cuts the plasmid DNA at specific sites."],
    "Only bacteria that took up the plasmid and express the resistance gene can grow in the presence of ampicillin. The antibiotic therefore acts as a selective agent, and the colonies that grow are the transformed cells."),
  M(6,
    "A mutation deletes exactly three consecutive nucleotides from within the coding region of a gene. Which result is most likely?",
    ["One amino acid is missing, but the rest of the sequence is unchanged", "Every amino acid after the deletion is changed because the reading frame shifts", "No protein is produced because translation cannot begin without the codon", "A single amino acid in the protein is replaced by a different amino acid"],
    "Deleting three nucleotides removes one codon (or parts of two codons) and keeps the reading frame intact for the rest of the message. The protein therefore lacks one amino acid (or changes one), but the remainder is unchanged, unlike a frameshift."),

  // ================= Unit 7 (10) =================
  S(7,
    "A genetic disorder caused by a recessive allele affects 1 in 10,000 people in a population that is in Hardy–Weinberg equilibrium. What is the approximate frequency of carriers in the population?",
    ["0.01", "0.02", "0.10", "0.20"], 1,
    "q² = 1/10,000 = 0.0001, so q = 0.01 and p ≈ 0.99. The frequency of carriers is 2pq ≈ 2(0.99)(0.01) ≈ 0.02, which is about 2%."),
  G(7, {
    text: "The cladogram shows relationships among four groups of plants. The table shows whether each trait is present (+) or absent (−) in each group.",
    figures: [fig(B.cladogram({ tree: [[["Flowering plants", "Conifers"], "Ferns"], "Mosses"] }), "A cladogram of four plant groups. Mosses branch off first, then ferns, and the last split separates conifers and flowering plants as sister groups."),
      table(["Group", "Vascular tissue", "Seeds", "Flowers"], [["Mosses", "−", "−", "−"], ["Ferns", "+", "−", "−"], ["Conifers", "+", "+", "−"], ["Flowering plants", "+", "+", "+"]])],
  }, [
    M(7, "Which statement is best supported by the cladogram and the table?",
      ["Seeds evolved after vascular tissue in the lineage leading to flowering plants.", "Seeds evolved before vascular tissue in the lineage leading to flowering plants.", "Flowers evolved independently in the conifers and in the flowering plants.", "Mosses evolved from flowering plants that lost their vascular tissue."],
      "Ferns have vascular tissue but not seeds, and conifers and flowering plants, which branch later, have both. Vascular tissue therefore appeared before seeds in this lineage."),
    M(7, "Which group is most closely related to the conifers?",
      ["Flowering plants", "Ferns", "Mosses", "All three groups are equally related to the conifers"],
      "Conifers and flowering plants are sister groups, which means they share a more recent common ancestor with each other than either does with ferns or mosses."),
  ]),
  M(7,
    "Whales have small pelvic bones that are not attached to the backbone and have no apparent function in swimming. How are these structures best described, and what do they suggest?",
    ["They are vestigial structures that suggest whales descended from land mammals.", "They are analogous structures that evolved in response to a similar environment.", "They are homoplasies that arose independently in whales and fish.", "They are adaptations that provide support during swimming."],
    "Vestigial structures are reduced remnants of features that were functional in ancestors. The whale pelvis is evidence that whales evolved from four-legged land mammals."),
  G(7, {
    text: "Before the Industrial Revolution, most of the peppered moths in a region were light-colored, which camouflaged them on lichen-covered tree bark. As air pollution darkened the bark, the frequency of dark-colored moths changed. After clean air laws were passed, the lichens returned. The graph shows the percentage of dark moths in the population in three years.",
    figures: [fig(moths, "A bar graph of the percentage of dark-colored moths in the population. In 1850 it is 5 percent, in 1895 it is 95 percent, and in 1990 it is 10 percent.", { maxWidth: 460 })],
  }, [
    M(7, "Which statement best explains the increase in the frequency of dark moths between 1850 and 1895?",
      ["Dark moths were better camouflaged on dark bark, so they left more offspring", "Light-colored moths changed into dark-colored moths as a response to pollution", "The pollution caused new dark-colored alleles to arise in the moth population", "Dark moths migrated into the region from other places where bark was dark"],
      "When the bark darkened, birds more easily found and ate the light moths, so dark moths survived and reproduced more. The frequency of the allele for dark color increased in the population, which is natural selection."),
    M(7, "Which of the following best explains the decrease in the percentage of dark moths by 1990?",
      ["The environment changed again, and selection favored the light-colored moths", "The dark-colored allele was lost from the population by new mutations", "Dark moths stopped reproducing for several generations after the clean air laws", "Natural selection ended once the air became clean and the lichens returned"],
      "Natural selection depends on the environment. As lichens returned, light moths were again better camouflaged, so their reproductive success increased and the frequency of the light allele rose."),
  ]),
  M(7,
    "The long, colorful tail of a male peacock makes it more visible to predators but increases the number of mates he attracts. Which process best explains the evolution of this trait?",
    ["Sexual selection, in which traits that increase mating success are favored", "Genetic drift, in which random events change allele frequencies", "The founder effect, in which a few individuals establish a new population", "Stabilizing selection, in which extreme traits are removed"],
    "Sexual selection favors traits that increase an individual's ability to obtain mates, even if the traits reduce survival. Females choosing males with elaborate tails results in more offspring for those males, so the trait becomes more exaggerated."),
  S(7,
    "In a population of 300 plants in Hardy–Weinberg equilibrium, the frequency of the dominant allele is p = 0.6. How many plants are expected to be heterozygous?",
    ["36", "72", "144", "180"], 2,
    "q = 1 − 0.6 = 0.4. The frequency of heterozygotes is 2pq = 2(0.6)(0.4) = 0.48, so the number of heterozygous plants is 0.48 × 300 = 144."),
  M(7,
    "A population of wild wheat suddenly produces a new species when an error in meiosis doubles the number of chromosomes, so that the new plants can reproduce with each other but not with the parent species. What type of speciation does this describe?",
    ["Sympatric speciation by polyploidy", "Allopatric speciation by geographic isolation", "Adaptive radiation after a mass extinction", "Gradual speciation by genetic drift"],
    "Polyploidy can produce reproductive isolation in a single generation without a geographic barrier, which is sympatric speciation. It is especially common in plants."),
  M(7,
    "Some RNA molecules, called ribozymes, can catalyze chemical reactions. Why is this finding significant for hypotheses about the origin of life?",
    ["It suggests that early life used RNA both to store information and to catalyze reactions", "It shows that proteins were the first molecules to store genetic information in cells", "It proves that DNA was already present before RNA appeared in early cells", "It shows that RNA can function only inside intact, membrane-bound living cells"],
    "The RNA world hypothesis proposes that RNA, which can both carry genetic information and act as an enzyme, preceded DNA and proteins. The discovery of ribozymes provides support for this idea."),

  // ================= Unit 8 (7) =================
  S(8,
    "In an ecosystem, the gross primary productivity (GPP) is 12,000 kcal/m²/yr, and the producers use 4,000 kcal/m²/yr in cellular respiration. What is the net primary productivity (NPP)?",
    ["3,000 kcal/m²/yr", "8,000 kcal/m²/yr", "12,000 kcal/m²/yr", "16,000 kcal/m²/yr"], 1,
    "NPP = GPP − energy used in respiration = 12,000 − 4,000 = 8,000 kcal/m²/yr. This is the energy that is available to consumers."),
  G(8, {
    text: "A pesticide that persists in the environment was sprayed on a lake. The table shows the concentration of the pesticide in the organisms at each trophic level.",
    figures: [table(["Organism", "Pesticide concentration (ppm)"], [["Producers (algae)", "0.04"], ["Zooplankton", "0.23"], ["Small fish", "2.07"], ["Large fish", "13.8"], ["Fish-eating birds", "25"]])],
  }, [
    M(8, "Which process is shown by the data?",
      ["Biomagnification, in which a substance becomes more concentrated at higher trophic levels", "Primary succession, in which a new community develops on bare rock over time", "Nitrogen fixation, in which bacteria convert atmospheric nitrogen into ammonia", "Eutrophication, in which excess nutrients cause a bloom of algae in the lake"],
      "The pesticide is not easily broken down or excreted, so it accumulates in the tissues of organisms. Consumers at each higher level eat many organisms from the level below, so the concentration increases up the food chain."),
    S(8, "How many times greater is the concentration of the pesticide in the fish-eating birds than in the algae?",
      ["25", "60", "625", "1000"], 2,
      "The ratio is 25 ppm ÷ 0.04 ppm = 625."),
  ]),
  M(8,
    "Which of the following processes removes carbon dioxide from the atmosphere and incorporates the carbon into organic molecules?",
    ["Photosynthesis", "Cellular respiration", "Combustion of fossil fuels", "Decomposition"],
    "Photosynthetic organisms take in CO₂ and fix the carbon into sugars. Respiration, combustion, and decomposition all release CO₂ back into the atmosphere."),
  M(8,
    "Which of the following is an example of a density-dependent factor that limits the size of a population?",
    ["The spread of a disease among crowded animals", "A volcanic eruption", "A severe drought that kills most plants", "A flood that destroys a nesting area"],
    "Density-dependent factors, such as competition, predation, parasitism, and disease, have a greater effect as the population density increases. Disasters such as eruptions, droughts, and floods affect populations regardless of their density."),
  S(8,
    "A researcher captures and marks 50 fish in a pond and releases them. Later, the researcher captures 40 fish, 10 of which are marked. Using the mark–recapture method, what is the estimated size of the fish population?",
    ["100", "200", "250", "500"], 1,
    "The proportion of marked fish in the second sample (10/40) estimates the proportion of marked fish in the whole population (50/N). N = (50 × 40)/10 = 200."),
  M(8,
    "Mycorrhizal fungi grow in association with plant roots, increasing the plant's absorption of water and minerals, while the fungi receive sugars from the plant. What type of relationship is this?",
    ["Mutualism", "Parasitism", "Commensalism", "Competition"],
    "In mutualism, both species benefit. The fungi extend the effective absorbing area of the roots, and the plant provides the fungi with organic carbon from photosynthesis."),
];
