import { S, M, G } from "./pool.mjs";
import * as B from "./biofigs.mjs";
const { fig, table, chart, barChart, curve, COL } = B;

export const config = { hub: "biology", prefix: "be", N: 4, file: "exam4.js", title: "AP Biology — Exam 4", seed: 35, units: { 1: 5, 2: 7, 3: 8, 4: 7, 5: 6, 6: 8, 7: 11, 8: 8 } };

const uptake = chart({
  w: 520, h: 320, x: [0, 10, 2], y: [0, 10, 2], xLabel: "Concentration of molecule outside the cell (mM)", yLabel: "Rate of uptake (relative units)", legend: true,
  series: [
    { name: "Molecule A", pts: curve((c) => 0.9 * c, 0, 10, 40), color: COL.a },
    { name: "Molecule B", pts: curve((c) => (9 * c) / (1.5 + c), 0, 10, 80), color: COL.b },
  ],
});
const drift = chart({
  w: 520, h: 320, x: [0, 50, 10], y: [0, 1, 0.2], xLabel: "Generation", yLabel: "Frequency of allele A", legend: true, yFmt: (v) => v.toFixed(1),
  series: [
    { name: "Population X", pts: [[0, 0.5], [10, 0.52], [20, 0.48], [30, 0.51], [40, 0.5], [50, 0.52]], color: COL.a, markers: true },
    { name: "Population Y", pts: [[0, 0.5], [10, 0.65], [20, 0.4], [30, 0.75], [40, 0.9], [50, 1.0]], color: COL.b, markers: true },
  ],
});
const survivorship = chart({
  w: 520, h: 320, x: [0, 100, 20], y: [0, 1000, 200], xLabel: "Percentage of maximum life span", yLabel: "Number of survivors", legend: true,
  series: [
    { name: "Curve 1", pts: curve((x) => 1000 * (1 - Math.pow(x / 100, 4)), 0, 100, 80), color: COL.a },
    { name: "Curve 2", pts: curve((x) => 1000 * Math.exp(-0.025 * x), 0, 100, 80), color: COL.c },
    { name: "Curve 3", pts: curve((x) => 1000 * Math.exp(-0.065 * x), 0, 100, 80), color: COL.b },
  ],
});

export default [
  // ================= Unit 1 (5) =================
  M(1,
    "Water can travel from the roots to the top of a tall tree. Which properties of water are most important in this process?",
    ["Cohesion between water molecules and adhesion to the walls of the xylem", "High specific heat and the ability to dissolve ionic compounds", "Low density as a solid and a high heat of vaporization", "Nonpolarity and the ability to form micelles in cells"],
    "Water molecules cohere to one another through hydrogen bonds, and they adhere to the polar walls of xylem vessels. Together these forces let transpiration pull a continuous column of water upward against gravity."),
  M(1,
    "A phospholipid molecule has both a hydrophilic region and a hydrophobic region. Which term describes a molecule with these two types of regions?",
    ["Amphipathic", "Nonpolar", "Hydrophobic", "Denatured"],
    "A molecule that has a polar (hydrophilic) head and nonpolar (hydrophobic) tails is amphipathic. This property lets phospholipids form the bilayer of cell membranes."),
  S(1,
    "A protein consists of a single polypeptide chain of 150 amino acids. How many peptide bonds are in the protein?",
    ["148", "149", "150", "151"], 1,
    "A chain of n amino acids is joined by n − 1 peptide bonds, so 150 amino acids have 149 peptide bonds."),
  G(1, {
    text: "The table shows the elements found in three biological macromolecules, X, Y, and Z, isolated from a cell.",
    figures: [table(["Macromolecule", "Elements present"], [["X", "C, H, O"], ["Y", "C, H, O, N, S"], ["Z", "C, H, O, N, P"]])],
  }, [
    M(1, "Which macromolecule is most likely a nucleic acid?",
      ["Z, because phosphorus is found in the backbone of nucleic acids", "X, because it contains carbon, hydrogen, and oxygen", "Y, because it contains sulfur", "None of them, because nucleic acids contain only C, H, and O"],
      "Nucleic acids are made of nucleotides, which contain phosphate groups (phosphorus) and nitrogenous bases (nitrogen). Macromolecule Z contains both N and P, so it is the nucleic acid."),
    M(1, "Which macromolecule is most likely a protein?",
      ["Y, because it contains nitrogen and sulfur found in amino acids", "X, because it contains no nitrogen", "Z, because it contains phosphorus", "None of them, because proteins contain only C, H, and O"],
      "Proteins contain nitrogen in the amino group of every amino acid, and some amino acids (cysteine and methionine) contain sulfur. Macromolecule X, with only C, H, and O, is most likely a carbohydrate or a lipid."),
  ]),

  // ================= Unit 2 (7) =================
  M(2,
    "Lysosomes contain hydrolytic enzymes that function best at an acidic pH. Why does a lysosomal enzyme cause little damage if it leaks into the cytosol, which has a nearly neutral pH?",
    ["The enzyme is much less active at the neutral pH of the cytosol.", "The cytosol contains inhibitors that break down all enzymes quickly.", "The enzymes cannot be made unless the pH is acidic.", "Cytosolic enzymes destroy the lysosomal enzymes at once."],
    "An enzyme's shape and activity depend on the pH of its surroundings. The lysosomal hydrolases are adapted to an acidic environment, so at the pH of the cytosol they have little activity, which protects the cell."),
  S(2,
    "Each side of a cube-shaped cell measures 3 μm. Determine the ratio of the cell's surface area to its volume.",
    ["0.67 μm⁻¹", "1.0 μm⁻¹", "2.0 μm⁻¹", "6.0 μm⁻¹"], 2,
    "The surface area is 6 × (3 μm)² = 54 μm², and the volume is (3 μm)³ = 27 μm³. The ratio is 54/27 = 2.0 μm⁻¹."),
  M(2,
    "Which statement best describes the function of the nuclear pores in the nuclear envelope?",
    ["They regulate the movement of mRNA and proteins between the nucleus and cytoplasm.", "They allow the DNA to leave the nucleus and enter the cytoplasm freely.", "They are the sites where proteins are made on the surface of the envelope.", "They block every kind of molecule from crossing the nuclear envelope."],
    "Nuclear pore complexes are channels that allow the controlled passage of molecules, such as mRNA and ribosomal subunits leaving the nucleus, and proteins (such as transcription factors) entering the nucleus."),
  G(2, {
    text: "A researcher measured the rate at which two molecules, A and B, are taken up by cells as the concentration of each molecule outside the cell was increased. The results are shown in the graph.",
    figures: [fig(uptake, "A graph of the rate of uptake against concentration outside the cell. The curve for molecule A increases in a straight line. The curve for molecule B rises steeply and then levels off near 9.")],
  }, [
    M(2, "Which of the following best describes the uptake of molecule B?",
      ["It enters by facilitated diffusion through a limited number of carrier proteins.", "It enters by simple diffusion through the lipid bilayer of the membrane.", "It enters by osmosis through water channels called aquaporins in the membrane.", "It enters by a process that is not affected by the outside concentration."],
      "The uptake rate of molecule B levels off, which shows that the process becomes saturated. This is characteristic of transport that depends on a limited number of carrier proteins, such as facilitated diffusion or active transport."),
    M(2, "Which statement best explains why the uptake of molecule A does not level off?",
      ["Molecule A crosses by simple diffusion, which has no limited set of proteins.", "Molecule A is actively pumped across the membrane by using ATP as energy.", "Molecule A is too large to enter the cell through the membrane at all.", "Molecule A is taken up only when its outside concentration is very high."],
      "The rate of simple diffusion is proportional to the concentration gradient, so it keeps increasing as the concentration increases. There are no protein carriers that can become saturated."),
  ]),
  M(2,
    "A plant cell is placed in distilled water. Which of the following will happen to the cell?",
    ["Water enters by osmosis until the cell becomes turgid and the cell wall prevents bursting.", "Water leaves the cell until the cell becomes plasmolyzed.", "The cell bursts, because the cell wall cannot withstand pressure.", "There is no net movement of water, because the cell wall is impermeable."],
    "Distilled water has a higher water potential than the cell, so water enters by osmosis. The pressure potential from the rigid cell wall rises until it balances the solute potential, and the cell becomes firm (turgid) without bursting."),
  S(2,
    "A potato core gains 8% of its mass in a 0.4 M sucrose solution and loses 6% of its mass in a 0.6 M sucrose solution. Assuming a linear change between these two values, what is the approximate sucrose concentration at which the potato core would show no change in mass?",
    ["0.40 M", "0.51 M", "0.60 M", "1.0 M"], 1,
    "The mass change goes from +8% to −6% (a 14% change) over a 0.2 M interval. The zero point is (8/14)(0.2) = 0.114 M above 0.4 M, or about 0.51 M. At that concentration the water potential of the solution equals that of the potato cells."),

  // ================= Unit 3 (8) =================
  G(3, {
    text: "Researchers added two chemicals to separate samples of isolated mitochondria and measured the oxygen consumption and the ATP production. The results are shown in the table. Cyanide blocks the transfer of electrons to oxygen at the end of the electron transport chain. DNP makes the inner mitochondrial membrane permeable to protons.",
    figures: [table(["Condition", "O₂ consumption", "ATP production"], [["No chemical added", "High", "High"], ["Cyanide added", "Very low", "Very low"], ["DNP added", "High", "Very low"]])],
  }, [
    M(3, "Which statement best explains the effect of cyanide?",
      ["Electrons cannot reach oxygen, so the chain stops and no proton gradient is kept", "Cyanide makes the membrane permeable to protons, so the gradient is lost entirely", "Cyanide supplies extra electrons to the chain, which quickly uses up all the oxygen", "Cyanide destroys the ATP that is produced by the mitochondria as soon as it forms"],
      "With the last step blocked, electrons cannot flow through the chain, so no more protons are pumped and oxygen is not consumed. Without the proton gradient, ATP synthase cannot make ATP."),
    M(3, "Which statement best explains why ATP production is low when DNP is added, even though oxygen consumption is high?",
      ["Protons leak across the membrane, so the gradient that powers ATP synthase is lost", "The electron transport chain stops working in the presence of DNP, so no ATP forms", "DNP prevents oxygen from entering the mitochondria, so no proton gradient can form", "DNP breaks down the ATP synthase enzyme, so the gradient cannot be put to use"],
      "DNP is an uncoupler: it allows protons to cross the membrane without going through ATP synthase. The chain keeps running (and oxygen is consumed), but the energy of the gradient is released as heat instead of being used to make ATP."),
  ]),
  M(3,
    "In the Calvin cycle, which enzyme catalyzes the attachment of CO₂ to ribulose bisphosphate (RuBP)?",
    ["Rubisco", "ATP synthase", "DNA polymerase", "Catalase"],
    "Rubisco catalyzes the fixation of CO₂ to the five-carbon sugar RuBP, forming an unstable six-carbon intermediate that splits into two molecules of 3-phosphoglycerate."),
  M(3,
    "A pigment extract from a leaf absorbs red and blue light strongly but reflects green light. Which statement is the best interpretation of this observation?",
    ["The pigment is chlorophyll, and the leaf appears green because green light is reflected.", "The pigment cannot be used for photosynthesis, because it does not absorb green light.", "The pigment absorbs green light, which is why the leaf looks green.", "The pigment is a carbohydrate that stores energy from red and blue light."],
    "Chlorophyll absorbs mainly the red and blue-violet wavelengths and reflects or transmits green, which is why leaves look green. The absorbed wavelengths provide the energy for the light-dependent reactions."),
  S(3,
    "For the Calvin cycle to produce one net molecule of the three-carbon sugar G3P, how many molecules of ATP and NADPH are required?",
    ["3 ATP and 2 NADPH", "6 ATP and 4 NADPH", "9 ATP and 6 NADPH", "18 ATP and 12 NADPH"], 2,
    "Fixing three CO₂ molecules to make one G3P requires 9 ATP and 6 NADPH. These energy carriers are supplied by the light-dependent reactions."),
  M(3,
    "A molecule that is not a substrate binds to an enzyme at a site other than the active site, and the enzyme's activity increases. What type of regulation is this?",
    ["Allosteric activation", "Competitive inhibition", "Feedback inhibition", "Denaturation"],
    "In allosteric regulation, a molecule binds at a regulatory site distinct from the active site and changes the enzyme's shape. An activator stabilizes the active form and increases the enzyme's activity."),
  M(3,
    "Which of the following correctly describes the structure of an ATP molecule?",
    ["Adenine, the sugar ribose, and three phosphate groups", "Thymine, the sugar deoxyribose, and one phosphate group", "Adenine, the sugar glucose, and two phosphate groups", "Guanine, the sugar ribose, and three carboxyl groups"],
    "ATP is a nucleotide that consists of the base adenine, the five-carbon sugar ribose, and a chain of three phosphate groups. The release of the terminal phosphate by hydrolysis provides energy for cellular work."),
  M(3,
    "Some bacteria that live in the digestive systems of animals cannot survive in the presence of oxygen. How do these obligate anaerobes obtain ATP?",
    ["By fermentation or anaerobic respiration, using a molecule other than oxygen", "By aerobic respiration, using oxygen as the terminal electron acceptor", "By photosynthesis, using sunlight in the gut", "They do not need ATP, because they are dormant"],
    "Obligate anaerobes rely on glycolysis followed by fermentation, or on anaerobic respiration with an electron acceptor other than oxygen (such as sulfate). Both produce much less ATP per glucose than aerobic respiration."),

  // ================= Unit 4 (7) =================
  M(4,
    "Epinephrine binds to a G protein-coupled receptor on a liver cell, which leads to the production of cAMP inside the cell. What is the role of cAMP in this pathway?",
    ["A second messenger that relays the signal inside the cell", "The ligand that binds to the receptor on the cell surface", "The receptor protein that binds the epinephrine molecule", "The final product that the liver cell secretes into the blood"],
    "Epinephrine is the first messenger. After it binds to the receptor, a G protein activates adenylyl cyclase, which makes the second messenger cAMP. The cAMP spreads in the cytoplasm and activates protein kinases that carry out the response."),
  S(4,
    "A cell cycle lasts 20 hours, and the cell spends 4 hours in S phase. What is the fraction of the cycle spent in S phase?",
    ["4%", "20%", "40%", "80%"], 1,
    "The fraction is 4 h ÷ 20 h = 0.20, or 20% of the cycle."),
  M(4,
    "Which of the following correctly distinguishes homologous chromosomes from sister chromatids?",
    ["Homologous chromosomes are a maternal and a paternal copy of the same chromosome, while sister chromatids are identical copies produced by DNA replication.", "Homologous chromosomes are identical copies produced by replication, while sister chromatids are maternal and paternal chromosomes.", "Homologous chromosomes are found only in mitosis, and sister chromatids only in meiosis.", "Homologous chromosomes contain different genes, and sister chromatids contain the same genes."],
    "A homologous pair consists of two chromosomes of the same type, one inherited from each parent, carrying the same genes (possibly with different alleles). Sister chromatids are the two identical DNA molecules produced during the S phase and joined at the centromere."),
  G(4, {
    text: "The table shows the number of chromosomes per cell and the number of chromatids per chromosome at different stages in the life of a human cell that undergoes meiosis.",
    figures: [table(["Stage", "Chromosomes per cell", "Chromatids per chromosome"], [["G₁ of interphase", "46", "1"], ["After the S phase", "46", "2"], ["After meiosis I", "23", "2"], ["After meiosis II", "23", "1"]])],
  }, [
    S(4, "How many chromosomes are in each cell at the end of meiosis I?",
      ["12", "23", "46", "92"], 1,
      "Meiosis I separates the homologous chromosomes into two daughter cells, so the chromosome number is halved: 46/2 = 23 chromosomes per cell, each still made of two chromatids."),
    M(4, "Which event in meiosis II explains the change from two chromatids to one chromatid per chromosome?",
      ["The separation of sister chromatids", "The separation of homologous chromosomes", "The replication of DNA", "Crossing over between homologous chromosomes"],
      "In meiosis II, the sister chromatids of each chromosome separate, so that each of the four resulting cells has chromosomes composed of a single chromatid. DNA is not replicated between meiosis I and meiosis II."),
  ]),
  M(4,
    "The Ras protein normally helps relay growth signals and turns off when the signal ends. A mutation that keeps Ras permanently active is found in many cancers. Which term describes the mutated gene?",
    ["An oncogene", "A tumor suppressor gene", "A pseudogene", "A housekeeping gene"],
    "An oncogene is a mutated version of a normal gene (a proto-oncogene) that promotes cell division. A permanently active Ras sends a continuous signal to divide, even in the absence of growth factors."),
  M(4,
    "A cell in culture is deprived of the growth factors that it needs, and it stops dividing in the G₁ phase and enters a nondividing state. What is the name of this state?",
    ["The G₀ phase", "The S phase", "Anaphase", "Cytokinesis"],
    "Cells that do not receive the signals required to pass the G₁ checkpoint can leave the cycle and enter the G₀ phase, where they remain active but do not divide. Many specialized cells, such as neurons, remain in G₀."),

  // ================= Unit 5 (6) =================
  S(5,
    "Two parents are both carriers of a recessive allele (Aa). What is the probability that at least one of their two children will have the recessive disorder?",
    ["1/16", "3/8", "7/16", "9/16"], 2,
    "The probability that one child does not have the disorder is 3/4, so the probability that neither of the two children has it is (3/4)² = 9/16. The probability that at least one does is 1 − 9/16 = 7/16."),
  G(5, {
    text: "In a testcross, a plant that is heterozygous for two linked genes (AaBb, with the dominant alleles on the same chromosome) is crossed with a plant that is homozygous recessive (aabb). The numbers of offspring with each phenotype are shown in the table.",
    figures: [table(["Offspring phenotype", "Number"], [["Dominant for both traits (AB)", "440"], ["Recessive for both traits (ab)", "410"], ["Dominant A, recessive b (Ab)", "80"], ["Recessive a, dominant B (aB)", "70"]])],
  }, [
    S(5, "What is the recombination frequency between the two genes (in map units, where 1% = 1 map unit)?",
      ["7.5", "15", "30", "85"], 1,
      "The recombinant offspring are the ones with new allele combinations (Ab and aB): 80 + 70 = 150 of 1000 offspring. The recombination frequency is 15%, which corresponds to 15 map units."),
    M(5, "Which of the following best explains why most of the offspring are not recombinant?",
      ["The genes are close together on one chromosome, so crossing over between them is rare.", "The genes are on different chromosomes and therefore assort independently of each other.", "The genes are located on the sex chromosomes, which do not undergo crossing over.", "The parents were both homozygous for the alleles of the two genes in the cross."],
      "Genes that are physically close on a chromosome tend to be inherited together, and crossing over between them is uncommon. If they were on different chromosomes, independent assortment would produce about 25% of each phenotype."),
  ]),
  M(5,
    "Mitochondria contain their own DNA. In humans, how are mitochondrial genes inherited?",
    ["They are inherited from the mother, because the egg supplies the mitochondria to the zygote.", "They are inherited from the father, because the sperm supplies the mitochondria.", "They are inherited equally from both parents.", "They are not inherited, because mitochondria form from new DNA in each zygote."],
    "The cytoplasm of the zygote comes almost entirely from the egg, and the mitochondria in the sperm are usually not passed on. Mitochondrial traits therefore show maternal inheritance."),
  M(5,
    "Mendel's law of independent assortment states that alleles for different genes are distributed to gametes independently of one another. Which condition must be met for this law to apply?",
    ["The genes are on different chromosomes or far apart on the same chromosome.", "The genes are located right next to each other on the same chromosome.", "The genes are both carried on the X chromosome of the individual.", "The alleles of the two genes must both be codominant with each other."],
    "Alleles of genes on different chromosomes separate independently during meiosis I. Genes that are very far apart on the same chromosome behave in the same way because crossing over between them is frequent. Closely linked genes do not assort independently."),
  S(5,
    "A student performs a chi-square test on the offspring of a cross that has four possible phenotypes. How many degrees of freedom should be used to find the critical value?",
    ["1", "2", "3", "4"], 2,
    "The degrees of freedom are the number of categories minus one: 4 − 1 = 3."),

  // ================= Unit 6 (8) =================
  M(6,
    "During DNA replication, which enzyme synthesizes a short RNA primer that provides a starting point for DNA polymerase?",
    ["Primase", "DNA ligase", "Helicase", "Topoisomerase"],
    "DNA polymerase can add nucleotides only to an existing 3′ end, so primase first synthesizes a short RNA primer. Helicase unwinds the double helix and ligase joins Okazaki fragments."),
  M(6,
    "The template strand of a gene has the sequence 3′-TACGGATT-5′. Which of the following is the sequence of the mRNA that is transcribed from this template?",
    ["5′-AUGCCUAA-3′", "5′-ATGCCTAA-3′", "5′-UACGGAUU-3′", "5′-AUGCCUAA-5′"],
    "The mRNA is complementary and antiparallel to the template strand, with uracil replacing thymine: 3′-TACGGATT-5′ pairs to give 5′-AUGCCUAA-3′. The mRNA sequence is the same as the coding strand but with U in place of T."),
  M(6,
    "HIV is a retrovirus. Which enzyme does HIV carry that allows it to make a DNA copy of its RNA genome?",
    ["Reverse transcriptase", "DNA polymerase III", "RNA polymerase", "Helicase"],
    "A retrovirus uses reverse transcriptase to synthesize DNA from its RNA genome. The DNA copy is then integrated into the host cell's chromosomes."),
  G(6, {
    text: "A circular plasmid was digested with two restriction enzymes, EcoRI and BamHI, in separate reactions, and the products were analyzed by gel electrophoresis along with a DNA ladder. The gel is shown. The sizes of the ladder fragments are labeled in base pairs (bp).",
    figures: [fig(B.gel({ lanes: [{ label: "Ladder", bands: [0.1, 0.25, 0.4, 0.55, 0.7, 0.85], sizes: ["3000", "2500", "2000", "1500", "1000", "500"] }, { label: "EcoRI", bands: [0.25, 0.7] }, { label: "BamHI", bands: [0.4, 0.55] }] }), "A gel with three lanes. The ladder lane has bands at 3000, 2500, 2000, 1500, 1000, and 500 base pairs. The EcoRI lane has two bands at the 2500 and 1000 base pair positions. The BamHI lane has two bands at the 2000 and 1500 base pair positions.")],
  }, [
    S(6, "What is the total size of the plasmid?",
      ["1,000 bp", "2,500 bp", "3,500 bp", "5,000 bp"], 2,
      "The EcoRI fragments are 2500 and 1000 bp, which add up to 3500 bp. The BamHI fragments, 2000 and 1500 bp, also add up to 3500 bp, which confirms the plasmid size. (Each enzyme cuts the circular plasmid twice, producing two fragments.)"),
    M(6, "A different circular plasmid has only one recognition site for a restriction enzyme. What would the digestion of this plasmid with the enzyme produce?",
      ["One linear DNA fragment as long as the original plasmid", "Two linear fragments that are exactly equal in length", "No fragments at all, because a circular DNA cannot be cut", "Many small fragments of random lengths from the plasmid"],
      "Cutting a circular DNA molecule once opens the circle into one linear molecule of the same total length. A circular DNA with n sites produces n fragments."),
  ]),
  M(6,
    "The promoter of a eukaryotic gene contains a sequence called the TATA box. What is the function of this sequence?",
    ["It is a binding site for transcription factors that help start transcription.", "It is the site where the ribosome attaches to the mRNA before translation.", "It codes for the first amino acid of the protein that the gene specifies.", "It is the site where the pre-mRNA is cut and spliced to remove introns."],
    "The TATA box is part of the promoter. General transcription factors bind to it first and recruit RNA polymerase II to start transcription at the correct location."),
  S(6,
    "In a sample of double-stranded DNA, 20% of the nucleotides are thymine. What percentage of the nucleotides are guanine?",
    ["20%", "30%", "40%", "60%"], 1,
    "T = 20% means A = 20%, so A + T = 40%. The remaining 60% is split equally between G and C, so G = 30%."),
  M(6,
    "Small RNA molecules called microRNAs (miRNAs) can bind to complementary sequences in the mRNA of target genes. What is the effect of this binding?",
    ["It blocks translation or leads to mRNA degradation, reducing gene expression.", "It increases the rate of DNA replication of the target gene in the nucleus.", "It attaches a protective cap to the 5′ end of the target mRNA molecule.", "It converts the target mRNA into a double-stranded DNA copy of the gene."],
    "miRNAs are part of RNA interference. When a miRNA pairs with a target mRNA, it can inhibit translation or promote degradation of the message, which lowers the amount of protein made from that gene."),

  // ================= Unit 7 (11) =================
  S(7,
    "In a population in Hardy–Weinberg equilibrium, the frequency of the recessive allele q is 0.3. What is the frequency of heterozygous individuals?",
    ["0.09", "0.21", "0.42", "0.49"], 2,
    "With q = 0.3, p = 0.7. The frequency of heterozygotes is 2pq = 2(0.7)(0.3) = 0.42."),
  G(7, {
    text: "The cladogram shows the evolutionary relationships among four animals. The table shows which of the traits are present (+) or absent (−) in each animal.",
    figures: [fig(B.cladogram({ tree: [[["Crab", "Fly"], "Snail"], "Sponge"] }), "A cladogram of four animals. Sponge branches off first, then snail. The last split separates crab and fly as sister groups."),
      table(["Animal", "True tissues", "Bilateral symmetry", "Segmented body", "Jointed legs"], [["Sponge", "−", "−", "−", "−"], ["Snail", "+", "+", "−", "−"], ["Crab", "+", "+", "+", "+"], ["Fly", "+", "+", "+", "+"]])],
  }, [
    M(7, "Which animal is most closely related to the fly?",
      ["Crab", "Snail", "Sponge", "All of the other animals are equally related to the fly"],
      "The crab and the fly are sister taxa: they share a more recent common ancestor with each other than either shares with the snail or the sponge."),
    M(7, "Which statement is best supported by the data?",
      ["A segmented body evolved in the common ancestor of the crab and the fly.", "A segmented body evolved independently in the crab and in the fly.", "Bilateral symmetry evolved in the common ancestor of the sponge and the snail.", "Jointed legs evolved before true tissues."],
      "Segmentation is found only in the crab and the fly, which are sister taxa, so the most parsimonious explanation is a single origin in their common ancestor. Sponges lack both bilateral symmetry and true tissues."),
  ]),
  M(7,
    "Genes called Hox genes, which control the body plan of the embryo, are very similar in organisms as different as flies and mice. What does this similarity suggest?",
    ["The genes were inherited from a common ancestor and have been conserved.", "The genes evolved independently in the flies and in the mice.", "The genes are not important for the development of the embryo.", "Flies and mice have identical body plans, so the genes are identical."],
    "A high degree of similarity in genes with basic developmental functions across distantly related animals is evidence of common ancestry. Because these genes are so important, mutations in them are strongly selected against, and they have been conserved."),
  G(7, {
    text: "Computer simulations tracked the frequency of an allele (A) over 50 generations in two populations that started with an allele frequency of 0.5. There was no selection, mutation, or migration. Population X has 10,000 individuals, and population Y has 20 individuals. The results are shown in the graph.",
    figures: [fig(drift, "A graph of the frequency of allele A against generation. Population X stays close to 0.5 throughout. Population Y fluctuates widely, rising and falling, and reaches 1.0 by generation 50.")],
  }, [
    M(7, "Which process best explains the different results for the two populations?",
      ["Genetic drift, which has a larger effect in small populations", "Natural selection, which is stronger in large populations", "Gene flow, which is greater in the small population", "Mutation, which is more frequent in the small population"],
      "With no selection or migration, random changes in allele frequency from generation to generation (genetic drift) are much larger in a small population. The large population shows only small fluctuations."),
    M(7, "What is the most likely effect of continued drift on population Y?",
      ["The allele will become fixed, and genetic variation will be lost.", "The allele will stay near 0.5.", "Both alleles will be maintained at equal frequencies.", "The population will adapt to its environment."],
      "Drift can eliminate one allele and fix the other (frequency of 1.0), which reduces the genetic variation in the population. Drift is random and does not produce adaptations."),
  ]),
  M(7,
    "Antibiotic resistance genes can be transferred between bacterial cells by a process in which a plasmid is passed through a connection from one cell to another. Which term describes this process?",
    ["Conjugation, a type of horizontal gene transfer between cells", "Binary fission, in which one cell divides to form two new cells", "Vertical gene transmission from a parent cell to its offspring", "Meiosis, in which a cell produces gametes with half the chromosomes"],
    "In conjugation, one bacterium transfers a copy of a plasmid to another bacterium through a pilus. Because the genes pass between existing cells rather than from parent to offspring, this is horizontal gene transfer."),
  S(7,
    "Uranium-238 has a half-life of 4.5 billion years. A rock sample contains 25% of the uranium-238 that it originally contained. What is the approximate age of the rock?",
    ["2.25 billion years", "4.5 billion years", "9.0 billion years", "18 billion years"], 2,
    "25% is (1/2)², so two half-lives have passed: 2 × 4.5 = 9.0 billion years."),
  M(7,
    "In some regions of Africa, people who are heterozygous for the sickle-cell allele are more resistant to malaria than people who are homozygous for the normal allele. What effect does this have on the sickle-cell allele?",
    ["Heterozygote advantage maintains the allele in the population at a significant frequency.", "The allele is eliminated by natural selection, because homozygotes have a severe disease.", "The allele becomes fixed in the population.", "The allele frequency does not change."],
    "Heterozygotes have a higher fitness than either type of homozygote in areas with malaria, so selection favors the heterozygotes and keeps both alleles in the population, even though homozygous recessive individuals have sickle-cell disease."),
  M(7,
    "Two species of frogs live in the same pond and can mate, but the eggs of one species are not fertilized by the sperm of the other species. Which type of reproductive barrier is this?",
    ["Gametic isolation, a prezygotic barrier", "Hybrid sterility, a postzygotic barrier", "Habitat isolation, a prezygotic barrier", "Temporal isolation, a prezygotic barrier"],
    "Gametic isolation prevents fertilization because the sperm and egg of different species are not compatible. It acts before a zygote is formed, so it is a prezygotic barrier."),
  S(7,
    "A population has an allele frequency of p = 0.8 for allele A. Each generation, 10% of the individuals in the population are immigrants from another population in which p = 0.2. Assuming no other evolutionary forces, what is the allele frequency of A after one generation of migration?",
    ["0.70", "0.74", "0.80", "0.86"], 1,
    "The new frequency is the weighted average: (0.90)(0.8) + (0.10)(0.2) = 0.72 + 0.02 = 0.74. Gene flow makes the allele frequencies of populations more similar."),

  // ================= Unit 8 (8) =================
  S(8,
    "A population of mice grows at a constant rate of 7% per year. Using the rule of 70, what is the approximate doubling time of the population?",
    ["5 years", "10 years", "14 years", "70 years"], 1,
    "The doubling time is approximately 70 divided by the percentage growth rate: 70/7 = 10 years."),
  G(8, {
    text: "The graph shows the survivorship (the number of individuals surviving at each age) of three species in a hypothetical group of 1000 newborns. The horizontal axis shows age as a percentage of the maximum life span.",
    figures: [fig(survivorship, "A graph of the number of survivors against age as a percentage of maximum life span. Curve 1 stays high and then drops sharply near the end. Curve 2 falls steadily at a constant rate. Curve 3 falls steeply early in life and then flattens out at a low level.")],
  }, [
    M(8, "Which curve is most likely to represent a species that produces many offspring and provides little or no parental care?",
      ["Curve 3, because most offspring die at a young age", "Curve 1, because most individuals survive to old age", "Curve 2, because the death rate is constant", "None of the curves, because all species provide parental care"],
      "Species with many offspring and little parental care, such as oysters or many fish, experience high mortality early in life, followed by lower mortality for the few survivors. This corresponds to curve 3."),
    M(8, "Which curve would best describe a species in which individuals receive extensive parental care and most survive to old age?",
      ["Curve 1", "Curve 2", "Curve 3", "All of the curves"],
      "In curve 1, mortality is low until late in life. This pattern is found in species that produce few offspring and invest heavily in each, such as humans and large mammals."),
  ]),
  M(8,
    "A bare rock is exposed when a glacier retreats. Which organisms would most likely be the first to colonize the rock?",
    ["Lichens and other pioneer species", "Large trees", "Grazing mammals", "Flowering shrubs"],
    "Primary succession begins on rock with no soil. Pioneer species such as lichens and mosses can survive there, and they help break down the rock and add organic matter that forms soil for later species."),
  M(8,
    "Two species of barnacles that live on the same rocky shore compete for space. One species lives in the upper zone and the other in the lower zone, but the lower species excludes the upper species when the upper species is placed in the lower zone. What does this illustrate?",
    ["The fundamental niche versus the realized niche, as shaped by competition", "Mutualism between the two species of barnacles on the shore", "Primary succession on the bare rock of the shoreline over time", "Biomagnification of a toxin in the food web of the intertidal zone"],
    "The upper species can survive in the lower zone (part of its fundamental niche), but competition with the other species restricts it to the upper zone (its realized niche)."),
  S(8,
    "A herbivore population has 2000 kJ of energy in its biomass, and the carnivores that eat the herbivores have 180 kJ in their biomass. What is the approximate efficiency of energy transfer from the herbivores to the carnivores?",
    ["0.9%", "9%", "18%", "90%"], 1,
    "The efficiency is (180 kJ/2000 kJ) × 100 = 9%, which is close to the typical 10% rule."),
  S(8,
    "A population has a carrying capacity of K = 800 and an intrinsic growth rate of r = 0.4 per week. Using the logistic growth equation dN/dt = rN(K − N)/K, what is the population growth rate when N = 200?",
    ["20 per week", "60 per week", "80 per week", "120 per week"], 1,
    "dN/dt = (0.4)(200)(800 − 200)/800 = (0.4)(200)(0.75) = 60 individuals per week. This is less than the exponential rate rN = 80 because the population is approaching its carrying capacity."),
  M(8,
    "A lake receives large amounts of nitrogen and phosphorus fertilizer in runoff from nearby farms. Which sequence of events is most likely to occur?",
    ["Algae grow rapidly, die, and are decomposed by bacteria that consume oxygen, so fish may die from low oxygen levels.", "Algae decline because nutrients are toxic, and oxygen levels in the water rise.", "Fish populations grow quickly because there are more nutrients, and oxygen levels remain constant.", "The lake becomes more acidic, but the algae are not affected."],
    "Excess nutrients cause an algal bloom (eutrophication). When the algae die, decomposing bacteria use large amounts of dissolved oxygen, creating a hypoxic zone that can kill fish and other aquatic organisms."),
];
