import { S, M, G } from "./pool.mjs";
import * as C from "./chemfigs.mjs";
const { fig, table } = C;

export const config = { hub: "chemistry", prefix: "ce", N: 1, file: "exam1.js", title: "AP Chemistry — Exam 1", seed: 11, units: { 1: 6, 2: 5, 3: 13, 4: 6, 5: 5, 6: 5, 7: 6, 8: 8, 9: 6 } };

const beer = C.chart({ w: 480, h: 320, x: [0, 0.5, 0.1], y: [0, 0.8, 0.2], xLabel: "Concentration (M)", yLabel: "Absorbance", xFmt: (v) => v.toFixed(1), yFmt: (v) => v.toFixed(1), series: [{ name: "standards", pts: [[0, 0], [0.1, 0.15], [0.2, 0.3], [0.3, 0.45], [0.4, 0.6]], color: C.COL.a, markers: true }] });

export default [
  // ================= Unit 1 (6) =================
  S(1,
    "How many moles of aluminum atoms are in an 8.1 g sample of aluminum? (The molar mass of Al is 27.0 g/mol.)",
    ["0.030 mol", "0.30 mol", "3.0 mol", "30 mol"], 1,
    "n = mass/molar mass = 8.1 g ÷ 27.0 g/mol = 0.30 mol."),
  G(1, {
    text: "The mass spectrum of a sample of copper is shown. All of the ions detected have a charge of +1.",
    figures: [fig(C.massSpectrum({ peaks: [{ mz: 63, ab: 69 }, { mz: 65, ab: 31 }], mzMin: 60, mzMax: 68 }), "A mass spectrum with two peaks. The peak at mass-to-charge ratio 63 has a relative abundance of 69 percent and the peak at 65 has a relative abundance of 31 percent.")],
  }, [
    S(1, "What is the average atomic mass of this sample of copper?",
      ["63.0 amu", "63.6 amu", "64.0 amu", "64.6 amu"], 1,
      "The average atomic mass is the abundance-weighted average: (0.69)(63) + (0.31)(65) = 43.47 + 20.15 = 63.6 amu. The simple average of 63 and 65, 64.0, ignores that the lighter isotope is more abundant."),
    M(1, "Which statement best explains why the spectrum shows two peaks?",
      ["The sample contains two isotopes of copper that differ in their number of neutrons.",
       "The sample contains copper atoms with two different numbers of protons.",
       "Some of the copper atoms in the sample have lost two electrons instead of one.",
       "Some of the copper atoms in the sample are in an excited electronic state."],
      "Isotopes of an element have the same number of protons but different numbers of neutrons, so they have different masses and appear at different mass-to-charge ratios. Both peaks are for singly charged ions, so the difference in m/z comes from mass, not charge."),
  ]),
  G(1, {
    text: "The photoelectron spectrum of a neutral atom of an element in the second period is shown.",
    figures: [fig(C.pesSpectrum({ peaks: [{ E: 40.6, n: 2, label: "1s" }, { E: 3.05, n: 2, label: "2s" }, { E: 1.4, n: 3, label: "2p" }], xMax: 100, xTicks: [0.1, 1, 10, 100] }), "A photoelectron spectrum with three peaks on a logarithmic binding energy axis. The peak at 40.6 megajoules per mole has a relative height of 2, the peak at 3.05 has a height of 2, and the peak at 1.40 has a height of 3.")],
  }, [
    M(1, "Which element produced this spectrum?",
      ["Nitrogen", "Carbon", "Boron", "Oxygen"],
      "The relative peak heights show the number of electrons in each subshell: 2 in the first peak (1s), 2 in the second (2s), and 3 in the third (2p). The configuration 1s²2s²2p³ has 7 electrons, so the element has 7 protons and is nitrogen."),
    M(1, "Why does the 1s peak occur at a much greater binding energy than the 2p peak?",
      ["The 1s electrons are closer to the nucleus and feel a greater effective nuclear charge.", "The 1s electrons are farther from the nucleus, so they are held more tightly by it.", "The 1s subshell holds more electrons than the 2p subshell does, so it binds more.", "The 1s electrons are shielded from the nucleus by the electrons in the 2p subshell."],
      "Binding energy depends on how strongly an electron is attracted to the nucleus. 1s electrons are the closest to the nucleus and are shielded the least, so they feel the greatest effective nuclear charge and require the most energy to remove. Inner electrons shield outer ones, not the reverse."),
  ]),
  M(1,
    "Which of the following correctly compares the atomic radii of magnesium and chlorine?",
    ["Magnesium has the larger radius, because it has fewer protons pulling on the same shell.", "Chlorine has the larger radius, because it has more electrons than magnesium has.", "Chlorine has the larger radius, because it has a greater nuclear charge than magnesium.", "The two atoms have equal radii, because they are in the same period of the table."],
    "Mg and Cl are both in the third period, so their valence electrons are in the same energy level and shielding is similar. Chlorine has 17 protons and magnesium has 12, so chlorine's valence electrons feel a greater effective nuclear charge and are pulled closer. The radius therefore decreases from left to right across a period."),

  // ================= Unit 2 (5) =================
  M(2,
    "Which of the following molecules has a trigonal pyramidal molecular geometry?",
    ["NH₃", "CH₄", "H₂O", "BF₃"],
    "In NH₃, nitrogen has four electron domains (three bonding pairs and one lone pair). The electron geometry is tetrahedral, and the molecular geometry, with the lone pair not counted, is trigonal pyramidal. CH₄ is tetrahedral, H₂O is bent, and BF₃ is trigonal planar."),
  M(2,
    "Which of the following bonds is the most polar?",
    ["C–F", "C–O", "C–N", "C–H"],
    "Bond polarity increases with the difference in electronegativity. Electronegativity rises across a period, so fluorine (4.0) differs from carbon (2.5) by the most. The C–F bond is the most polar."),
  G(2, {
    text: "The graph shows the potential energy of two bonded atoms as a function of the distance between their nuclei for the H–H bond and the Cl–Cl bond.",
    figures: [fig(C.bondCurve({ cases: 2, labelA: "H–H", labelB: "Cl–Cl" }), "A graph of potential energy in kilojoules per mole against internuclear distance in picometers for two bonds. The H–H curve has a deep minimum of about minus 435 at 74 picometers. The Cl–Cl curve has a shallower minimum of about minus 240 at about 199 picometers.")],
  }, [
    M(2, "Which bond is stronger?",
      ["The H–H bond, because its potential energy well is deeper.",
       "The Cl–Cl bond, because its minimum occurs at a greater distance.",
       "The bonds are equally strong, because both curves approach zero at large distances.",
       "The Cl–Cl bond, because its curve is wider."],
      "The depth of the potential energy well is the bond energy, the energy needed to separate the atoms completely. The H–H well is deeper (about 435 kJ/mol compared with about 240 kJ/mol), so the H–H bond is stronger."),
    M(2, "Which bond has the greater bond length?",
      ["Cl–Cl, because the minimum of its curve is at the greater internuclear distance.", "H–H, because the minimum of its curve is at the lower potential energy.", "The bond lengths are equal, because both of the bonds are single bonds.", "H–H, because its curve rises more steeply at short internuclear distances."],
      "The bond length is the internuclear distance at the minimum of the potential energy curve. The Cl–Cl minimum is at about 199 pm and the H–H minimum is at about 74 pm, so the Cl–Cl bond is longer. Chlorine atoms are larger than hydrogen atoms."),
  ]),
  M(2,
    "What is the hybridization of the carbon atom in a molecule of CO₂?",
    ["sp", "sp²", "sp³", "sp³d"],
    "In CO₂ the carbon atom has two electron domains (two double bonds, no lone pairs), so the electron geometry is linear and the carbon is sp hybridized. Each double bond consists of one sigma bond and one pi bond."),

  // ================= Unit 3 (13) =================
  M(3,
    "In which of the following substances does hydrogen bonding occur between molecules?",
    ["CH₃CH₂OH", "CH₃OCH₃", "CH₃CH₃", "CH₃Cl"],
    "Hydrogen bonding requires a hydrogen atom bonded to N, O, or F in one molecule and a lone pair on N, O, or F in a neighboring molecule. Ethanol has an O–H bond. Dimethyl ether has oxygen but no O–H bond, so its molecules cannot donate hydrogen bonds to each other."),
  M(3,
    "The boiling point of HF (20 °C) is much higher than that of HCl (−85 °C), even though HCl has the larger molar mass. Which statement best explains this?",
    ["HF molecules form hydrogen bonds with each other, which are stronger than the forces between HCl molecules.",
     "HF has stronger London dispersion forces because it has more electrons than HCl.",
     "The H–F bond is stronger than the H–Cl bond, so HF molecules are harder to break apart.",
     "HF is an ionic compound, and HCl is a covalent compound."],
    "Boiling depends on the strength of the intermolecular forces, not on the strength of the covalent bonds inside the molecules. Fluorine is highly electronegative and small, so HF molecules form strong hydrogen bonds. HCl molecules have weaker dipole–dipole and dispersion forces."),
  S(3,
    "A sample of gas occupies 4.0 L at a pressure of 2.0 atm. The pressure is changed to 8.0 atm at constant temperature. What is the new volume of the gas?",
    ["0.50 L", "1.0 L", "4.0 L", "16 L"], 1,
    "At constant temperature, P₁V₁ = P₂V₂, so V₂ = (2.0)(4.0)/8.0 = 1.0 L."),
  S(3,
    "How many moles of an ideal gas are in a 2.00 L container at a pressure of 1.50 atm and a temperature of 300. K? (R = 0.0821 L·atm/(mol·K))",
    ["0.0122 mol", "0.122 mol", "1.22 mol", "8.21 mol"], 1,
    "n = PV/(RT) = (1.50)(2.00)/((0.0821)(300.)) = 3.00/24.6 = 0.122 mol."),
  M(3,
    "The temperature of a fixed amount of an ideal gas in a rigid container is increased. Which of the following explains, on the molecular level, why the pressure increases?",
    ["The molecules collide with the walls more frequently and with greater force.",
     "The molecules become larger and take up more of the container's volume.",
     "The attractions between the molecules become stronger.",
     "The number of molecules in the container increases."],
    "Raising the temperature increases the average kinetic energy and speed of the molecules. They hit the walls more often and with greater force per collision, so the pressure increases. The number of molecules and the volume do not change."),
  G(3, {
    text: "The graph shows the distribution of molecular speeds for a sample of gas at two different temperatures, T₁ and T₂.",
    figures: [fig(C.maxwell({}), "Two curves of fraction of molecules against molecular speed. Curve T1 has a tall, narrow peak at a lower speed. Curve T2 has a lower, broader peak at a higher speed with a longer tail.")],
  }, [
    M(3, "Which statement about the two temperatures is correct?",
      ["T₂ is higher than T₁, because the distribution is shifted to higher speeds and is broader.",
       "T₁ is higher than T₂, because its peak is taller.",
       "The temperatures are equal, because the areas under the curves are equal.",
       "T₂ is lower than T₁, because its peak is lower."],
      "At a higher temperature the average speed and the spread of speeds increase, so the peak shifts to the right and becomes lower and broader. The area under each curve is the same (it represents all the molecules), so equal areas do not imply equal temperatures."),
    M(3, "Which statement best explains why a reaction between gases usually proceeds faster at T₂ than at T₁?",
      ["A greater fraction of the molecules has enough energy to overcome the activation energy.",
       "The activation energy of the reaction is lower at the higher temperature.",
       "The molecules collide less often, so each collision is more effective.",
       "The number of molecules increases at the higher temperature."],
      "In the T₂ distribution the high-speed tail is larger, so more molecules have kinetic energy at or above the activation energy. The activation energy itself does not change with temperature, and the molecules collide more, not less, often."),
  ]),
  S(3,
    "A 4.0 L container holds 0.50 mol of N₂ and 1.5 mol of O₂ at a total pressure of 4.0 atm. What is the partial pressure of O₂?",
    ["1.0 atm", "2.0 atm", "3.0 atm", "4.0 atm"], 2,
    "The partial pressure equals the mole fraction times the total pressure: X(O₂) = 1.5/2.0 = 0.75, so P(O₂) = (0.75)(4.0) = 3.0 atm."),
  S(3,
    "What mass of NaCl (molar mass 58.5 g/mol) is needed to prepare 500. mL of a 0.200 M solution?",
    ["0.585 g", "5.85 g", "11.7 g", "58.5 g"], 1,
    "Moles = (0.200 mol/L)(0.500 L) = 0.100 mol, and the mass is (0.100 mol)(58.5 g/mol) = 5.85 g."),
  S(3,
    "A 50.0 mL sample of 6.0 M HCl is diluted with water to a final volume of 250. mL. What is the concentration of the diluted solution?",
    ["0.24 M", "1.2 M", "6.0 M", "30. M"], 1,
    "The moles of HCl do not change: M₁V₁ = M₂V₂, so M₂ = (6.0)(50.0)/250. = 1.2 M."),
  G(3, {
    text: "A student measures the absorbance of several standard solutions of a colored compound at its wavelength of maximum absorption, using a cuvette with a path length of 1.0 cm. The calibration data are plotted in the graph.",
    figures: [fig(beer, "A graph of absorbance against concentration in molar showing five data points on a straight line through the origin: 0.15 at 0.10 M, 0.30 at 0.20 M, 0.45 at 0.30 M, and 0.60 at 0.40 M.")],
  }, [
    S(3, "A solution of the same compound has an absorbance of 0.36. What is its concentration?",
      ["0.12 M", "0.24 M", "0.36 M", "0.54 M"], 1,
      "The line has a slope of 0.15/0.10 = 1.5 M⁻¹ (A = εbc with b = 1.0 cm). Then c = A/1.5 = 0.36/1.5 = 0.24 M."),
    S(3, "The student measures the 0.20 M standard in a cuvette with a path length of 2.0 cm. What absorbance should the student expect?",
      ["0.15", "0.30", "0.60", "1.2"], 2,
      "By the Beer–Lambert law, A = εbc, so doubling the path length doubles the absorbance. The 0.20 M solution has A = 0.30 in a 1.0 cm cuvette, so in a 2.0 cm cuvette A = 0.60."),
  ]),
  M(3,
    "Which of the following solids conducts electricity when it is molten but not when it is solid?",
    ["NaCl", "Cu", "C (diamond)", "I₂"],
    "NaCl is an ionic solid: its ions are held in fixed positions in the solid and cannot carry charge, but they can move when the solid melts. Copper conducts in both states because of its mobile electrons. Diamond and I₂ do not conduct in either state."),

  // ================= Unit 4 (6) =================
  S(4,
    "In the reaction 2 H₂(g) + O₂(g) → 2 H₂O(g), how many grams of water (molar mass 18.0 g/mol) can be produced from 4.0 g of H₂ (molar mass 2.0 g/mol) with excess O₂?",
    ["18 g", "36 g", "72 g", "144 g"], 1,
    "4.0 g of H₂ is 2.0 mol. The mole ratio H₂ : H₂O is 1 : 1, so 2.0 mol of H₂O forms, which has a mass of (2.0)(18.0) = 36 g."),
  G(4, {
    text: "The particle diagrams show a mixture of A₂ and B₂ molecules before and after the reaction A₂ + B₂ → 2 AB goes to completion.",
    figures: [fig(C.particleBoxes({ boxes: [{ title: "Before reaction", parts: [{ kind: "A2", n: 4 }, { kind: "B2", n: 2 }] }, { title: "After reaction", parts: [{ kind: "AB", n: 4 }, { kind: "A2", n: 2 }] }], seed: 11 }), "Two boxes of particles. Before the reaction the box contains four A2 molecules and two B2 molecules. After the reaction it contains four AB molecules and two A2 molecules.")],
  }, [
    M(4, "Which reactant is the limiting reactant?",
      ["B₂, because it is completely consumed.", "A₂, because it is present in the greater amount.", "AB, because it is the only product.", "Neither, because both A₂ and B₂ appear in the reaction equation."],
      "The limiting reactant is the one that is used up first. After the reaction no B₂ molecules remain, so B₂ limited the amount of product, and some A₂ is left over."),
    S(4, "How many molecules of the excess reactant remain after the reaction is complete?",
      ["0", "1", "2", "4"], 2,
      "The two B₂ molecules react with two A₂ molecules (1 : 1 ratio), producing four AB molecules. Of the original four A₂ molecules, 4 − 2 = 2 remain unreacted."),
  ]),
  M(4,
    "When aqueous silver nitrate is mixed with aqueous sodium chloride, a white precipitate forms. Which of the following is the net ionic equation for the reaction?",
    ["Ag⁺(aq) + Cl⁻(aq) → AgCl(s)",
     "AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq)",
     "Na⁺(aq) + NO₃⁻(aq) → NaNO₃(s)",
     "Ag⁺(aq) + NO₃⁻(aq) → AgNO₃(s)"],
    "Silver chloride is insoluble, so it forms a precipitate, while sodium nitrate remains dissolved as Na⁺ and NO₃⁻ ions. The net ionic equation shows only the species that actually change: Ag⁺ and Cl⁻ combine to form AgCl(s). Na⁺ and NO₃⁻ are spectator ions."),
  S(4,
    "A 25.0 mL sample of HCl solution is neutralized by 20.0 mL of 0.100 M NaOH. What is the concentration of the HCl solution?",
    ["0.0500 M", "0.0800 M", "0.125 M", "0.500 M"], 1,
    "At the equivalence point, moles of H⁺ equal moles of OH⁻: (0.100 M)(0.0200 L) = 2.00 × 10⁻³ mol. The HCl concentration is 2.00 × 10⁻³ mol/0.0250 L = 0.0800 M."),
  S(4,
    "What is the oxidation number of manganese in the permanganate ion, MnO₄⁻?",
    ["+2", "+4", "+6", "+7"], 3,
    "The oxygen atoms are each −2, for a total of −8. The ion's charge is −1, so Mn must be +7 (since +7 − 8 = −1)."),

  // ================= Unit 5 (5) =================
  G(5, {
    text: "The initial rate of the reaction A + B → products was measured in three experiments. The data are shown in the table.",
    figures: [table(["Experiment", "[A] (M)", "[B] (M)", "Initial rate (M/s)"], [["1", "0.10", "0.10", "2.0 × 10⁻³"], ["2", "0.20", "0.10", "4.0 × 10⁻³"], ["3", "0.10", "0.20", "8.0 × 10⁻³"]])],
  }, [
    M(5, "What is the order of the reaction with respect to B?",
      ["Second order", "First order", "Zero order", "Third order"],
      "Compare experiments 1 and 3: [A] is constant and [B] doubles, while the rate increases by a factor of 4. A doubling of concentration that quadruples the rate means the rate is proportional to [B]², so the reaction is second order in B."),
    S(5, "What is the value of the rate constant, k, for this reaction?",
      ["0.20 M⁻² s⁻¹", "2.0 M⁻² s⁻¹", "20 M⁻² s⁻¹", "200 M⁻² s⁻¹"], 1,
      "Experiments 1 and 2 show the rate doubles when [A] doubles, so the reaction is first order in A. The rate law is rate = k[A][B]². Using experiment 1: k = (2.0 × 10⁻³)/((0.10)(0.10)²) = 2.0 M⁻² s⁻¹."),
  ]),
  M(5,
    "Which statement best describes how a catalyst increases the rate of a chemical reaction?",
    ["It provides an alternative reaction pathway with a lower activation energy.",
     "It increases the average kinetic energy of the reactant molecules.",
     "It shifts the equilibrium position toward the products.",
     "It increases the energy difference between the reactants and the products."],
    "A catalyst speeds up a reaction by providing a different mechanism with a lower activation energy, so a greater fraction of collisions are effective. It is not consumed, and it does not change the temperature, the equilibrium position, or the overall enthalpy change."),
  G(5, {
    text: "The energy profile for a reaction is shown for the uncatalyzed pathway (solid line) and for a catalyzed pathway (dashed line). Energies are in kJ.",
    figures: [fig(C.energyProfile({ r: 50, p: 20, peak: 120, catPeak: 85, values: true }), "An energy profile. The reactants are at 50 kilojoules, the products at 20 kilojoules, and the uncatalyzed transition state peak at 120. A dashed catalyzed pathway has a lower peak at 85 kilojoules.")],
  }, [
    S(5, "What is the activation energy of the uncatalyzed forward reaction?",
      ["35 kJ", "70 kJ", "100 kJ", "120 kJ"], 1,
      "The activation energy is the energy difference between the reactants and the top of the barrier: 120 − 50 = 70 kJ. The value 120 kJ is the energy of the transition state, not the barrier height."),
    S(5, "What is the enthalpy change, ΔH, for the forward reaction?",
      ["−70 kJ", "−30 kJ", "+30 kJ", "+70 kJ"], 1,
      "ΔH = H(products) − H(reactants) = 20 − 50 = −30 kJ. The reaction is exothermic. A catalyst does not change ΔH."),
  ]),

  // ================= Unit 6 (5) =================
  S(6,
    "A reaction takes place in 50.0 g of water, and the temperature of the water rises from 22.0 °C to 26.0 °C. How much thermal energy was absorbed by the water? (The specific heat of water is 4.18 J/(g·°C).)",
    ["209 J", "418 J", "836 J", "1670 J"], 2,
    "q = mcΔT = (50.0 g)(4.18 J/(g·°C))(4.0 °C) = 836 J."),
  S(6,
    "For the reaction A → B, ΔH = +100 kJ. For the reaction B → C, ΔH = −250 kJ. What is ΔH for the reaction A → C?",
    ["−350 kJ", "−150 kJ", "+150 kJ", "+350 kJ"], 1,
    "By Hess's law, enthalpy changes add for consecutive steps: ΔH = (+100) + (−250) = −150 kJ."),
  S(6,
    "Use the average bond enthalpies H–H = 436 kJ/mol, Cl–Cl = 243 kJ/mol, and H–Cl = 431 kJ/mol to estimate ΔH for H₂(g) + Cl₂(g) → 2 HCl(g).",
    ["−862 kJ", "−183 kJ", "+183 kJ", "+679 kJ"], 1,
    "ΔH ≈ (energy to break bonds) − (energy released forming bonds) = (436 + 243) − 2(431) = 679 − 862 = −183 kJ. The reaction is exothermic because the bonds formed are stronger than the bonds broken."),
  M(6,
    "A solid is heated at a constant rate and its temperature stays constant for several minutes while it melts. Which statement best explains why the temperature does not rise?",
    ["The energy added overcomes attractions between particles, raising their potential energy.", "The energy added is converted into the average kinetic energy of the particles.", "The energy added is lost to the surroundings as heat while the solid melts.", "The particles stop moving entirely while the solid is melting into a liquid."],
    "During a phase change the temperature, which measures the average kinetic energy of the particles, stays constant. The energy added goes into increasing the potential energy of the particles as the attractions between them are overcome."),
  S(6,
    "Use the standard enthalpies of formation (in kJ/mol): CH₄(g) = −74.8, CO₂(g) = −393.5, H₂O(l) = −285.8. What is ΔH° for CH₄(g) + 2 O₂(g) → CO₂(g) + 2 H₂O(l)?",
    ["−1,040 kJ", "−890 kJ", "−604 kJ", "+890 kJ"], 1,
    "ΔH° = ΣΔHf°(products) − ΣΔHf°(reactants) = [−393.5 + 2(−285.8)] − [−74.8 + 0] = −965.1 + 74.8 = −890.3 kJ. The standard enthalpy of formation of O₂(g) is zero. −1,040 kJ results from adding the reactant's ΔHf° instead of subtracting it."),

  // ================= Unit 7 (6) =================
  M(7,
    "Which of the following is the equilibrium constant expression for N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g)?",
    ["K = [NH₃]² / ([N₂][H₂]³)", "K = [NH₃] / ([N₂][H₂])", "K = [N₂][H₂]³ / [NH₃]²", "K = 2[NH₃] / (3[N₂][H₂])"],
    "The equilibrium expression is [products] raised to their coefficients divided by [reactants] raised to their coefficients: K = [NH₃]²/([N₂][H₂]³). The coefficients are exponents, not multipliers."),
  S(7,
    "For the reaction N₂O₄(g) ⇌ 2 NO₂(g), the equilibrium concentrations are [N₂O₄] = 0.25 M and [NO₂] = 0.50 M. What is the value of K for the reaction?",
    ["0.50", "1.0", "2.0", "4.0"], 1,
    "K = [NO₂]²/[N₂O₄] = (0.50)²/(0.25) = 0.25/0.25 = 1.0."),
  M(7,
    "The volume of the container for the system N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g) at equilibrium is suddenly decreased at constant temperature. In which direction does the equilibrium shift?",
    ["Toward the products, because there are fewer moles of gas on the product side.",
     "Toward the reactants, because there are more moles of gas on the reactant side.",
     "It does not shift, because the temperature is constant.",
     "Toward the reactants, because the concentrations of all the gases increase."],
    "Decreasing the volume increases the pressure. By Le Châtelier's principle, the system shifts to relieve the stress by reducing the number of gas molecules. The product side has 2 mol of gas and the reactant side has 4 mol, so the equilibrium shifts toward the products."),
  M(7,
    "For a reaction at a certain temperature, K = 2.0. A mixture of reactants and products has a reaction quotient Q = 0.50. Which statement is correct?",
    ["The reaction will proceed in the forward direction until equilibrium is reached.",
     "The reaction will proceed in the reverse direction until equilibrium is reached.",
     "The system is at equilibrium.",
     "The reaction will not proceed in either direction."],
    "When Q < K, the mixture has too much reactant and too little product compared with equilibrium, so the net reaction proceeds in the forward direction, forming products, until Q = K."),
  S(7,
    "The solubility product constant for AgCl is K_sp = 1.8 × 10⁻¹⁰. What is the molar solubility of AgCl in pure water?",
    ["1.8 × 10⁻¹⁰ M", "1.3 × 10⁻⁵ M", "1.8 × 10⁻⁵ M", "9.0 × 10⁻⁵ M"], 1,
    "AgCl(s) ⇌ Ag⁺ + Cl⁻, so K_sp = s² and s = √(1.8 × 10⁻¹⁰) = 1.3 × 10⁻⁵ M."),
  S(7,
    "For the reaction 2 SO₂(g) + O₂(g) ⇌ 2 SO₃(g), K_c = 100 at 800 K. What is K_p at this temperature? (R = 0.0821 L·atm/(mol·K))",
    ["0.015", "1.5", "100", "6600"], 1,
    "K_p = K_c(RT)^Δn, where Δn = 2 − 3 = −1. So K_p = 100/((0.0821)(800)) = 100/65.7 = 1.5."),

  // ================= Unit 8 (8) =================
  S(8,
    "What is the pH of a solution in which [H⁺] = 3.2 × 10⁻⁴ M?",
    ["2.49", "3.49", "4.49", "10.51"], 1,
    "pH = −log[H⁺] = −log(3.2 × 10⁻⁴) = 3.49."),
  S(8,
    "What is the pH of a 0.010 M NaOH solution at 25 °C?",
    ["2.00", "7.00", "12.00", "14.00"], 2,
    "NaOH is a strong base, so [OH⁻] = 0.010 M and pOH = 2.00. Then pH = 14.00 − 2.00 = 12.00."),
  G(8, {
    text: "A 25.0 mL sample of 0.100 M acetic acid (pK_a = 4.74) is titrated with 0.100 M NaOH. The titration curve is shown.",
    figures: [fig(C.titrationCurve({ Ca: 0.1, Va: 25, Cb: 0.1, Ka: 1.8e-5, vMax: 50 }), "A titration curve of pH against volume of 0.100 molar NaOH added. The curve starts near pH 2.9, rises slowly through a buffer region, rises steeply near 25 milliliters, and levels off near pH 12.")],
  }, [
    S(8, "What volume of NaOH is needed to reach the equivalence point?",
      ["12.5 mL", "25.0 mL", "37.5 mL", "50.0 mL"], 1,
      "The acid and base have the same concentration and react 1 : 1, so the equivalence point occurs when the volume of NaOH equals the volume of acid: 25.0 mL. This is where the curve rises most steeply."),
    S(8, "What is the pH of the solution after 12.5 mL of NaOH has been added?",
      ["2.87", "4.74", "7.00", "9.26"], 1,
      "At 12.5 mL, exactly half of the acetic acid has been converted into acetate, so [CH₃COOH] = [CH₃COO⁻]. By the Henderson–Hasselbalch equation, pH = pK_a + log(1) = 4.74."),
    M(8, "Why is the pH at the equivalence point greater than 7?",
      ["The acetate ion, the conjugate base of a weak acid, reacts with water to produce OH⁻.",
       "The sodium ion reacts with water to produce OH⁻.",
       "Excess NaOH remains in the solution at the equivalence point.",
       "Acetic acid is a strong acid, so its conjugate base is a strong base."],
      "At the equivalence point all of the acetic acid has been converted to acetate. Acetate is the conjugate base of a weak acid, so it hydrolyzes: CH₃COO⁻ + H₂O ⇌ CH₃COOH + OH⁻, making the solution basic. Na⁺ does not react with water."),
  ]),
  S(8,
    "A buffer solution contains 0.20 M CH₃COO⁻ and 0.10 M CH₃COOH. The pK_a of acetic acid is 4.74. What is the pH of the buffer?",
    ["4.44", "4.74", "5.04", "5.34"], 2,
    "By the Henderson–Hasselbalch equation, pH = pK_a + log([A⁻]/[HA]) = 4.74 + log(0.20/0.10) = 4.74 + 0.30 = 5.04."),
  M(8,
    "Acid HA has K_a = 1 × 10⁻³ and acid HB has K_a = 1 × 10⁻⁷. Which statement is correct?",
    ["A⁻ is a weaker base than B⁻.", "A⁻ is a stronger base than B⁻.", "HB is a stronger acid than HA.", "A⁻ and B⁻ have equal base strength."],
    "A stronger acid has a weaker conjugate base. HA has the larger K_a, so it is the stronger acid, and its conjugate base A⁻ is weaker than B⁻."),
  S(8,
    "A solution has a pH of 9.30 at 25 °C. What is the pOH of the solution?",
    ["4.70", "5.30", "9.30", "14.0"], 0,
    "At 25 °C, pH + pOH = 14.00, so pOH = 14.00 − 9.30 = 4.70."),

  // ================= Unit 9 (6) =================
  S(9,
    "For a reaction, ΔH = −40 kJ and ΔS = −100 J/K. What is ΔG at 300 K?",
    ["−70 kJ", "−10 kJ", "+10 kJ", "+70 kJ"], 1,
    "ΔG = ΔH − TΔS = −40 kJ − (300 K)(−0.100 kJ/K) = −40 + 30 = −10 kJ. The entropy must be converted from J/K to kJ/K to match the units of ΔH."),
  M(9,
    "Which of the following processes results in an increase in the entropy of the system?",
    ["NH₄NO₃(s) → NH₄⁺(aq) + NO₃⁻(aq)", "H₂O(g) → H₂O(l)", "2 NO₂(g) → N₂O₄(g)", "CO₂(g) → CO₂(s)"],
    "Entropy increases when there are more ways to arrange the particles and energy. Dissolving a crystalline solid into freely moving ions in solution increases the entropy. Condensation, dimerization (fewer moles of gas), and deposition all decrease the entropy of the system."),
  G(9, {
    text: "A galvanic cell is constructed from a zinc electrode in 1.0 M Zn²⁺ and a copper electrode in 1.0 M Cu²⁺, connected by a salt bridge, as shown. The standard reduction potentials are: Cu²⁺ + 2e⁻ → Cu, E° = +0.34 V; Zn²⁺ + 2e⁻ → Zn, E° = −0.76 V.",
    figures: [fig(C.galvanicCell({ left: { metal: "Zn", sol: "1.0 M Zn²⁺" }, right: { metal: "Cu", sol: "1.0 M Cu²⁺" }, electronDir: "right" }), "A galvanic cell. A zinc electrode in a zinc ion solution on the left and a copper electrode in a copper ion solution on the right are connected by a wire containing a voltmeter and by a salt bridge. An arrow shows electrons moving through the wire from the zinc toward the copper.")],
  }, [
    M(9, "Which electrode is the anode, and in which direction do electrons flow in the external wire?",
      ["Zinc is the anode, and electrons flow from the zinc electrode to the copper electrode.",
       "Copper is the anode, and electrons flow from the zinc electrode to the copper electrode.",
       "Zinc is the anode, and electrons flow from the copper electrode to the zinc electrode.",
       "Copper is the anode, and electrons flow from the copper electrode to the zinc electrode."],
      "Zinc has the more negative reduction potential, so it is the more easily oxidized species and serves as the anode (where oxidation occurs): Zn → Zn²⁺ + 2e⁻. Electrons travel through the wire from the anode to the cathode, so from zinc to copper."),
    S(9, "What is the standard cell potential, E°cell?",
      ["0.42 V", "0.76 V", "1.10 V", "1.44 V"], 2,
      "E°cell = E°(cathode) − E°(anode) = (+0.34) − (−0.76) = +1.10 V. The positive value indicates that the reaction is spontaneous."),
  ]),
  S(9,
    "A current of 2.00 A is passed through a solution of Cu²⁺ for 965 s. What mass of copper is deposited at the cathode? (Cu²⁺ + 2e⁻ → Cu; molar mass of Cu = 63.5 g/mol; 1 F = 96,500 C/mol e⁻)",
    ["0.318 g", "0.635 g", "1.27 g", "2.54 g"], 1,
    "The charge is q = It = (2.00)(965) = 1930 C, which is 1930/96,500 = 0.0200 mol of electrons. Two electrons deposit one Cu atom, so 0.0100 mol of Cu is deposited, with a mass of (0.0100)(63.5) = 0.635 g."),
  M(9,
    "A reaction has a standard free energy change ΔG° < 0 at 298 K. Which statement about the equilibrium constant K for this reaction is correct?",
    ["K > 1", "K < 1", "K = 1", "K = 0"],
    "The standard free energy change is related to the equilibrium constant by ΔG° = −RT ln K. A negative ΔG° requires ln K > 0, so K > 1: products are favored at equilibrium."),
];
