import { S, M, G } from "./pool.mjs";
import * as C from "./chemfigs.mjs";
const { fig, table, chart, curve, COL } = C;

export const config = { hub: "chemistry", prefix: "ce", N: 2, file: "exam2.js", title: "AP Chemistry — Exam 2", seed: 22, units: { 1: 5, 2: 6, 3: 12, 4: 5, 5: 6, 6: 6, 7: 5, 8: 9, 9: 6 } };

const solubility = chart({
  w: 520, h: 330, x: [0, 100, 20], y: [0, 180, 20], xLabel: "Temperature (°C)", yLabel: "Solubility (g per 100 g H₂O)", legend: true,
  series: [
    { name: "KNO₃", pts: [[0, 13], [20, 32], [40, 64], [60, 110], [80, 169]], markers: true, color: COL.a },
    { name: "NaCl", pts: [[0, 35.7], [20, 36], [40, 36.6], [60, 37.3], [80, 38]], markers: true, color: COL.b },
  ],
});
const decay = chart({
  w: 520, h: 320, x: [0, 80, 20], y: [0, 0.8, 0.2], xLabel: "Time (s)", yLabel: "[A] (M)", xFmt: (v) => v, yFmt: (v) => v.toFixed(1),
  series: [{ name: "[A]", pts: curve((t) => 0.8 * Math.pow(0.5, t / 20), 0, 80, 80), color: COL.a }],
  annotations: [{ type: "dot", x: 0, y: 0.8, fill: COL.b }, { type: "dot", x: 20, y: 0.4, fill: COL.b }, { type: "dot", x: 40, y: 0.2, fill: COL.b }, { type: "dot", x: 60, y: 0.1, fill: COL.b }],
});
const approach = chart({
  w: 520, h: 320, x: [0, 120, 20], y: [0, 1.0, 0.2], xLabel: "Time (s)", yLabel: "Concentration (M)", legend: true, xFmt: (v) => v, yFmt: (v) => v.toFixed(1),
  series: [
    { name: "[N₂O₄]", pts: curve((t) => 0.3 + 0.5 * Math.exp(-t / 20), 0, 120, 120), color: COL.a },
    { name: "[NO₂]", pts: curve((t) => 1.0 * (1 - Math.exp(-t / 20)), 0, 120, 120), color: COL.b },
  ],
});

export default [
  // ================= Unit 1 (5) =================
  S(1,
    "What is the mass percent of oxygen in calcium carbonate, CaCO₃? (Molar masses: Ca = 40.1, C = 12.0, O = 16.0 g/mol)",
    ["12.0%", "40.0%", "48.0%", "52.0%"], 2,
    "The molar mass of CaCO₃ is 40.1 + 12.0 + 3(16.0) = 100.1 g/mol. The oxygen contributes 48.0 g of that, so the mass percent is (48.0/100.1)(100) = 48.0%. The value 40.0% is the mass percent of calcium."),
  G(1, {
    text: "The photoelectron spectrum of a neutral atom of an element in the third period is shown.",
    figures: [fig(C.pesSpectrum({ peaks: [{ E: 104, n: 2, label: "1s" }, { E: 6.84, n: 2, label: "2s" }, { E: 3.67, n: 6, label: "2p" }, { E: 0.5, n: 1, label: "3s" }], xMax: 200, xTicks: [0.1, 1, 10, 100] }), "A photoelectron spectrum on a logarithmic binding energy axis with four peaks: 104 megajoules per mole with relative height 2, 6.84 with height 2, 3.67 with height 6, and 0.50 with height 1.")],
  }, [
    M(1, "Identify the element whose atoms produced this spectrum.",
      ["Sodium", "Magnesium", "Neon", "Aluminum"],
      "The relative peak heights, 2 : 2 : 6 : 1, correspond to 1s², 2s², 2p⁶, 3s¹. That is 11 electrons, so the element has 11 protons and is sodium."),
    M(1, "How would the photoelectron spectrum of magnesium differ from this spectrum?",
      ["The 3s peak would have a height of 2, and every peak would appear at a higher binding energy.",
       "The 3s peak would have a height of 2, and every peak would appear at a lower binding energy.",
       "The 3s peak would be absent, and a new 3p peak would appear.",
       "The spectrum would be identical, because both elements are in the third period."],
      "Magnesium has one more electron (1s²2s²2p⁶3s²), so its 3s peak is twice as tall. It also has one more proton, which increases the effective nuclear charge, so all of the electrons are held more tightly and all of the peaks shift to higher binding energy."),
  ]),
  M(1,
    "Which of the following correctly compares the first ionization energies of beryllium and boron?",
    ["Beryllium is higher, because its outer electron is in a lower-energy 2s subshell.", "Boron is higher, because it has more protons than beryllium has.", "Boron is higher, because its atoms are smaller than beryllium atoms are.", "The two are equal, because both elements are in the same period."],
    "The 2p electron that boron loses is higher in energy and is partially shielded by the 2s electrons, so it is easier to remove than beryllium's 2s electron, even though boron has the larger nuclear charge. This is a well-known exception to the general trend across a period."),
  M(1,
    "A compound is found to contain 40.0% carbon, 6.7% hydrogen, and 53.3% oxygen by mass. What is the empirical formula of the compound?",
    ["CH₂O", "C₂H₄O", "CHO", "C₂H₂O₂"],
    "In 100 g of the compound there are 40.0/12.0 = 3.33 mol C, 6.7/1.0 = 6.7 mol H, and 53.3/16.0 = 3.33 mol O. Dividing by the smallest value gives the ratio C : H : O = 1 : 2 : 1, so the empirical formula is CH₂O."),

  // ================= Unit 2 (6) =================
  M(2,
    "Which of the following species has a trigonal planar molecular geometry?",
    ["BF₃", "NF₃", "PCl₃", "NH₃"],
    "Boron in BF₃ has three bonding domains and no lone pairs, so its geometry is trigonal planar. NF₃, PCl₃, and NH₃ each have a lone pair on the central atom, giving them trigonal pyramidal geometry."),
  M(2,
    "Which of the following molecules is polar?",
    ["CH₃Cl", "CCl₄", "CO₂", "BF₃"],
    "A molecule is polar when it has polar bonds that do not cancel. CCl₄, CO₂, and BF₃ have polar bonds arranged symmetrically (tetrahedral, linear, and trigonal planar), so their bond dipoles cancel. In CH₃Cl the C–Cl bond is much more polar than the C–H bonds, and the molecule has a net dipole."),
  M(2,
    "Silicon dioxide, SiO₂, has a melting point of about 1700 °C, while carbon dioxide, CO₂, is a gas at room temperature. Which statement best explains this difference?",
    ["SiO₂ is a network covalent solid in which each atom is bonded to its neighbors, so melting requires breaking covalent bonds.",
     "SiO₂ molecules have stronger London dispersion forces because silicon has more electrons than carbon.",
     "SiO₂ is an ionic compound, and CO₂ is a covalent compound.",
     "The Si–O bond is much more polar than the C–O bond, which makes SiO₂ molecules attract each other strongly."],
    "In solid SiO₂, a continuous three-dimensional network of Si–O covalent bonds extends throughout the crystal, so melting requires breaking many strong covalent bonds. CO₂ consists of discrete nonpolar molecules held together only by weak London dispersion forces."),
  S(2,
    "In the nitrate ion, NO₃⁻, one Lewis structure has nitrogen bonded to one oxygen by a double bond and to two other oxygens by single bonds, with every atom satisfying the octet rule. What is the formal charge on the nitrogen atom in this structure?",
    ["−1", "0", "+1", "+2"], 2,
    "Formal charge = (valence electrons) − (nonbonding electrons) − ½(bonding electrons). Nitrogen has 5 valence electrons, no lone pairs, and 8 bonding electrons (four bonds), so the formal charge is 5 − 0 − 4 = +1."),
  M(2,
    "Which of the following correctly predicts which compound has the greater lattice energy, and why?",
    ["NaF has the greater lattice energy than KBr, because its ions are smaller, so the Coulombic attraction is stronger.",
     "KBr has the greater lattice energy than NaF, because its ions are larger and can pack more closely.",
     "NaF has the greater lattice energy than KBr, because fluorine is less electronegative than bromine.",
     "The two compounds have equal lattice energies, because both ions have a charge of magnitude 1."],
    "By Coulomb's law, the lattice energy increases with the magnitude of the ionic charges and decreases with the distance between the ions. Both compounds have +1 and −1 ions, but Na⁺ and F⁻ are much smaller than K⁺ and Br⁻, so the distance between the ions is smaller and the attraction is stronger in NaF."),
  M(2,
    "Brass is an alloy made by mixing copper atoms with zinc atoms of similar size. Which type of alloy is brass?",
    ["A substitutional alloy, because zinc atoms replace some of the copper atoms in the lattice.",
     "An interstitial alloy, because zinc atoms fit into the spaces between copper atoms.",
     "An ionic compound, because copper and zinc transfer electrons.",
     "A molecular solid, because copper and zinc form discrete molecules."],
    "In a substitutional alloy, atoms of similar size replace some of the atoms of the host metal in its crystal lattice. In an interstitial alloy, much smaller atoms (such as carbon in steel) occupy the gaps between the larger atoms."),

  // ================= Unit 3 (12) =================
  M(3,
    "Which of the following substances has the highest boiling point?",
    ["CH₃CH₂CH₂CH₃", "CH₄", "CH₃CH₃", "CH₃CH₂CH₃"],
    "All four are nonpolar hydrocarbons, so the only intermolecular forces are London dispersion forces. These increase with the size of the electron cloud, which increases with molar mass. Butane, CH₃CH₂CH₂CH₃, is the largest and has the strongest dispersion forces and the highest boiling point."),
  M(3,
    "Water has a much higher surface tension than hexane (C₆H₁₄). Which statement best explains this?",
    ["Water molecules are held by hydrogen bonds, which are stronger than hexane's dispersion forces.", "Water molecules have a much larger electron cloud than the molecules of hexane do.", "Water molecules are nonpolar, so they are pulled strongly toward one another at the surface.", "The covalent bonds within water molecules are stronger than those within hexane molecules."],
    "Surface tension reflects the strength of the attractions between molecules at the surface. Water molecules form hydrogen bonds with each other, which are much stronger than the London dispersion forces that hold hexane molecules together. The bonds within the molecules are not what is overcome."),
  S(3,
    "What is the density of methane, CH₄ (molar mass 16.0 g/mol), at STP? (At STP, 1 mol of an ideal gas occupies 22.4 L.)",
    ["0.357 g/L", "0.714 g/L", "1.40 g/L", "16.0 g/L"], 1,
    "The density is the molar mass divided by the molar volume: 16.0 g/mol ÷ 22.4 L/mol = 0.714 g/L."),
  S(3,
    "How many times faster does hydrogen gas (H₂, 2.0 g/mol) effuse than oxygen gas (O₂, 32 g/mol) at the same temperature?",
    ["2", "4", "8", "16"], 1,
    "By Graham's law, the ratio of effusion rates is √(M₂/M₁) = √(32/2.0) = √16 = 4."),
  S(3,
    "A 5.0 L flask contains 0.20 mol of an ideal gas at a pressure of 1.0 atm. What is the temperature of the gas? (R = 0.0821 L·atm/(mol·K))",
    ["25 K", "152 K", "304 K", "608 K"], 2,
    "T = PV/(nR) = (1.0)(5.0)/((0.20)(0.0821)) = 5.0/0.01642 ≈ 304 K."),
  G(3, {
    text: "The graph shows the solubility of two salts, KNO₃ and NaCl, in water at different temperatures.",
    figures: [fig(solubility, "A graph of solubility in grams per 100 grams of water against temperature. The KNO3 curve rises steeply from 13 at 0 degrees Celsius to 32, 64, 110, and 169 at 80 degrees. The NaCl curve is nearly flat near 36 to 38.")],
  }, [
    S(3, "What is the maximum mass of KNO₃ that will dissolve in 50 g of water at 60 °C?",
      ["32 g", "55 g", "64 g", "110 g"], 1,
      "At 60 °C, 110 g of KNO₃ dissolves in 100 g of water. In 50 g of water, half as much dissolves: 55 g."),
    M(3, "A saturated solution of KNO₃ at 80 °C is slowly cooled to 20 °C. What happens?",
      ["Solid KNO₃ crystallizes from the solution, because its solubility is lower at 20 °C.",
       "The solution remains saturated and no solid forms, because the concentration of the solution is unchanged.",
       "Solid KNO₃ dissolves, because the solution can hold more solute at a lower temperature.",
       "The solution becomes unsaturated, because KNO₃ reacts with water at low temperatures."],
      "The solubility of KNO₃ falls from about 169 g/100 g at 80 °C to about 32 g/100 g at 20 °C. The solution now holds more solute than it can at equilibrium, so the excess crystallizes out."),
  ]),
  S(3,
    "What is the molarity of a solution prepared by dissolving 10.0 g of NaOH (molar mass 40.0 g/mol) in enough water to make 250. mL of solution?",
    ["0.25 M", "1.00 M", "2.50 M", "4.00 M"], 1,
    "Moles of NaOH = 10.0/40.0 = 0.250 mol, and M = 0.250 mol/0.250 L = 1.00 M."),
  S(3,
    "What is the energy of a photon of blue light with a wavelength of 450 nm? (h = 6.63 × 10⁻³⁴ J·s, c = 3.00 × 10⁸ m/s)",
    ["4.4 × 10⁻²⁰ J", "4.4 × 10⁻¹⁹ J", "4.4 × 10⁻¹⁸ J", "1.5 × 10⁻³⁹ J"], 1,
    "E = hc/λ = (6.63 × 10⁻³⁴)(3.00 × 10⁸)/(450 × 10⁻⁹) = 4.4 × 10⁻¹⁹ J. The wavelength must be converted to meters."),
  M(3,
    "At very high pressures, real gases show deviations from ideal behavior. Which statement best explains these deviations?",
    ["The volume of the molecules is no longer negligible compared with the container's volume.", "The molecules stop moving, so the kinetic molecular theory no longer applies to them.", "The temperature of the gas decreases, so the molecules attract each other less strongly.", "The molecules collide with each other less often, so the gas behaves less like an ideal gas."],
    "The ideal gas model assumes the molecules have negligible volume and no attractions. At high pressure the molecules are squeezed close together, so their own volume becomes a significant part of the total volume and attractions between them become more important."),
  S(3,
    "In the reaction 2 KClO₃(s) → 2 KCl(s) + 3 O₂(g), what volume of O₂ at STP is produced from the decomposition of 0.20 mol of KClO₃? (1 mol of gas occupies 22.4 L at STP.)",
    ["4.5 L", "6.7 L", "10 L", "15 L"], 1,
    "The mole ratio is 3 mol O₂ per 2 mol KClO₃, so 0.20 mol KClO₃ gives 0.30 mol O₂. The volume is (0.30 mol)(22.4 L/mol) = 6.7 L."),
  M(3,
    "Which of the following aqueous solutions has the greatest electrical conductivity?",
    ["0.10 M CaCl₂", "0.10 M C₆H₁₂O₆ (glucose)", "0.10 M CH₃COOH", "0.10 M C₂H₅OH"],
    "Conductivity depends on the concentration of ions. CaCl₂ is a strong electrolyte that dissociates completely into three ions per formula unit (Ca²⁺ and 2 Cl⁻). Glucose and ethanol are nonelectrolytes, and acetic acid is a weak electrolyte that produces only a few ions."),

  // ================= Unit 4 (5) =================
  S(4,
    "A mixture contains 14 g of N₂ (molar mass 28.0 g/mol) and 4.0 g of H₂ (molar mass 2.0 g/mol). What is the maximum mass of NH₃ (17.0 g/mol) that can be produced by N₂ + 3 H₂ → 2 NH₃?",
    ["8.5 g", "17 g", "34 g", "51 g"], 1,
    "There are 14/28.0 = 0.50 mol of N₂ and 4.0/2.0 = 2.0 mol of H₂. The reaction needs 3 mol H₂ per mol N₂, so 0.50 mol N₂ would need 1.5 mol H₂ — N₂ is the limiting reactant. It produces 2(0.50) = 1.0 mol of NH₃, which has a mass of 17 g."),
  M(4,
    "Which of the following reactions is an oxidation–reduction reaction?",
    ["Zn(s) + CuSO₄(aq) → ZnSO₄(aq) + Cu(s)",
     "NaOH(aq) + HCl(aq) → NaCl(aq) + H₂O(l)",
     "AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq)",
     "CaCO₃(s) → CaO(s) + CO₂(g)"],
    "In the first reaction, zinc is oxidized (0 → +2) and copper(II) is reduced (+2 → 0), so electrons are transferred. The other reactions are acid–base, precipitation, and decomposition reactions in which no oxidation numbers change."),
  S(4,
    "In an experiment, the theoretical yield of a product is 25.0 g and 20.0 g of the product is actually obtained. What is the percent yield?",
    ["20.0%", "75.0%", "80.0%", "125%"], 2,
    "Percent yield = (actual/theoretical)(100) = (20.0/25.0)(100) = 80.0%."),
  S(4,
    "What volume of 0.200 M NaOH is required to neutralize completely 20.0 mL of 0.150 M H₂SO₄?",
    ["15.0 mL", "30.0 mL", "40.0 mL", "60.0 mL"], 1,
    "Sulfuric acid supplies two H⁺ per formula unit: (0.150 M)(0.0200 L)(2) = 6.00 × 10⁻³ mol H⁺. This requires 6.00 × 10⁻³ mol OH⁻, so V = 6.00 × 10⁻³/0.200 = 0.0300 L = 30.0 mL."),
  M(4,
    "Which of the following is the net ionic equation for the reaction between aqueous hydrochloric acid and aqueous sodium hydroxide?",
    ["H⁺(aq) + OH⁻(aq) → H₂O(l)", "HCl(aq) + NaOH(aq) → NaCl(aq) + H₂O(l)", "Na⁺(aq) + Cl⁻(aq) → NaCl(s)", "H⁺(aq) + Cl⁻(aq) → HCl(aq)"],
    "HCl and NaOH are strong electrolytes that exist as ions in solution. Na⁺ and Cl⁻ are spectator ions that appear on both sides, so the net reaction is H⁺ + OH⁻ → H₂O."),

  // ================= Unit 5 (6) =================
  S(5,
    "A first-order reaction has a rate constant of 0.0231 min⁻¹. What is the half-life of this reaction?",
    ["15 min", "30 min", "60 min", "120 min"], 1,
    "For a first-order reaction, t½ = ln 2/k = 0.693/0.0231 = 30.0 min."),
  G(5, {
    text: "The concentration of reactant A is measured as a function of time for the reaction A → products. The data are plotted in the graph.",
    figures: [fig(decay, "A graph of the concentration of A in molar against time in seconds. The concentration falls from 0.80 at 0 seconds to 0.40 at 20 seconds, 0.20 at 40 seconds, and 0.10 at 60 seconds, curving downward and flattening.")],
  }, [
    S(5, "What is the half-life of the reaction?",
      ["10 s", "20 s", "40 s", "60 s"], 1,
      "The concentration falls from 0.80 M to 0.40 M in 20 s, so the half-life is 20 s. It takes another 20 s to fall from 0.40 M to 0.20 M."),
    M(5, "What is the order of the reaction with respect to A?",
      ["First order, because the half-life is constant.",
       "Zero order, because the concentration decreases continuously.",
       "Second order, because the rate decreases as the concentration decreases.",
       "It cannot be determined without data for a second reactant."],
      "A constant half-life that does not depend on the initial concentration is the signature of a first-order reaction. For a zero-order reaction the concentration would decrease linearly, and for a second-order reaction successive half-lives would double."),
    S(5, "What is the rate constant for the reaction?",
      ["0.0347 s⁻¹", "0.347 s⁻¹", "1.39 s⁻¹", "28.8 s⁻¹"], 0,
      "For a first-order reaction, k = ln 2/t½ = 0.693/20 s = 0.0347 s⁻¹."),
  ]),
  M(5,
    "Which of the following changes will increase the value of the rate constant, k, for a reaction?",
    ["Increasing the temperature", "Increasing the concentration of a reactant", "Increasing the volume of the container", "Adding more of a product"],
    "The rate constant depends on temperature (through the Arrhenius equation) and on the activation energy (changed by a catalyst), but not on the concentrations of the species. Increasing the concentration increases the rate, but k itself stays the same."),
  M(5,
    "A reaction proceeds by the following mechanism. Step 1 (slow): A + B → C. Step 2 (fast): C + A → D. Which of the following is the rate law for the overall reaction?",
    ["Rate = k[A][B]", "Rate = k[A]²[B]", "Rate = k[C][A]", "Rate = k[D]"],
    "The rate of the overall reaction is determined by the slowest step, the rate-determining step. Step 1 is an elementary step, so its rate law follows from its molecularity: rate = k[A][B]."),

  // ================= Unit 6 (6) =================
  S(6,
    "When 5.0 g of a salt is dissolved in 100.0 g of water, the temperature of the solution falls from 22.0 °C to 19.0 °C. Assuming the solution has the specific heat of water, 4.18 J/(g·°C), and a mass of 100.0 g, how much thermal energy did the solution lose?",
    ["4.18 × 10² J", "1.25 × 10³ J", "4.18 × 10³ J", "1.25 × 10⁴ J"], 1,
    "q = mcΔT = (100.0 g)(4.18 J/(g·°C))(3.0 °C) = 1254 J ≈ 1.25 × 10³ J. The solution lost this energy to the dissolving salt, so the dissolution is endothermic."),
  S(6,
    "Given: C(s) + O₂(g) → CO₂(g), ΔH = −393.5 kJ; and CO(g) + ½ O₂(g) → CO₂(g), ΔH = −283.0 kJ. What is ΔH for C(s) + ½ O₂(g) → CO(g)?",
    ["−676.5 kJ", "−110.5 kJ", "+110.5 kJ", "+676.5 kJ"], 1,
    "Reverse the second equation (ΔH = +283.0 kJ) and add it to the first: C + O₂ → CO₂ and CO₂ → CO + ½O₂ combine to give C + ½O₂ → CO, with ΔH = −393.5 + 283.0 = −110.5 kJ."),
  M(6,
    "A 50 g sample of a metal at 100 °C is placed in 50 g of water at 20 °C in an insulated container. The final temperature of the system is 35 °C. Which statement about the specific heat capacities is correct?",
    ["Water has the greater specific heat capacity, because its temperature changed less than the metal's.",
     "The metal has the greater specific heat capacity, because it started at a higher temperature.",
     "They have equal specific heat capacities, because the masses are equal.",
     "Water has the smaller specific heat capacity, because it gained thermal energy."],
    "The energy lost by the metal equals the energy gained by the water: mc_metalΔT_metal = mc_waterΔT_water. The masses are equal, but the metal's temperature changed by 65 °C and the water's by only 15 °C, so the water must have the larger specific heat capacity."),
  S(6,
    "Use the average bond enthalpies N≡N = 945 kJ/mol, H–H = 436 kJ/mol, and N–H = 391 kJ/mol to estimate ΔH for N₂(g) + 3 H₂(g) → 2 NH₃(g).",
    ["−2,346 kJ", "−93 kJ", "+93 kJ", "+2,253 kJ"], 1,
    "Bonds broken: 945 + 3(436) = 2253 kJ. Bonds formed: 6 N–H bonds = 6(391) = 2346 kJ. ΔH ≈ 2253 − 2346 = −93 kJ."),
  S(6,
    "The standard enthalpies of formation are ΔHf°[Al₂O₃(s)] = −1675.7 kJ/mol and ΔHf°[Fe₂O₃(s)] = −824.2 kJ/mol. What is ΔH° for 2 Al(s) + Fe₂O₃(s) → Al₂O₃(s) + 2 Fe(s)?",
    ["−2,500 kJ", "−851.5 kJ", "+851.5 kJ", "+2,500 kJ"], 1,
    "ΔH° = ΣΔHf°(products) − ΣΔHf°(reactants) = (−1675.7 + 0) − (0 + (−824.2)) = −851.5 kJ. The standard enthalpy of formation of an element in its standard state (Al, Fe) is zero."),
  M(6,
    "A student mixes two solutions in a flask, and the flask feels cold to the touch. Which statement about the reaction is correct?",
    ["The reaction is endothermic, because it absorbs thermal energy from the surroundings.",
     "The reaction is exothermic, because it releases thermal energy to the surroundings.",
     "The reaction has ΔH < 0, because the temperature of the surroundings decreased.",
     "The reaction does not involve any energy change."],
    "A flask that feels cold is losing thermal energy to the reacting mixture, so the reaction absorbs heat from its surroundings: it is endothermic (ΔH > 0)."),

  // ================= Unit 7 (5) =================
  S(7,
    "For H₂(g) + I₂(g) ⇌ 2 HI(g), K = 50 at a certain temperature. A 1.0 L container initially holds 1.0 mol of H₂ and 1.0 mol of I₂. What is the equilibrium concentration of HI?",
    ["0.78 M", "1.1 M", "1.6 M", "2.0 M"], 2,
    "Let x be the moles of H₂ that react. Then [HI] = 2x and [H₂] = [I₂] = 1.0 − x, so K = (2x)²/(1.0 − x)² = 50. Taking the square root: 2x/(1.0 − x) = 7.07, so x = 0.78 M and [HI] = 2x ≈ 1.6 M."),
  M(7,
    "For the endothermic reaction A(g) + heat ⇌ B(g), the temperature of the system at equilibrium is increased. What happens to the equilibrium?",
    ["It shifts toward the products, and the value of K increases.",
     "It shifts toward the reactants, and the value of K decreases.",
     "It shifts toward the products, and the value of K stays the same.",
     "It does not shift, because the pressure is constant."],
    "Heat acts like a reactant in an endothermic reaction. Raising the temperature favors the endothermic (forward) direction, so more product forms at equilibrium. Temperature is the one stress that changes the value of K, which increases for an endothermic reaction."),
  M(7,
    "The solubility of AgCl in 0.10 M NaCl solution is compared with its solubility in pure water. Which statement is correct?",
    ["AgCl is less soluble in the NaCl solution because of the common ion Cl⁻.",
     "AgCl is more soluble in the NaCl solution because NaCl increases the ionic strength.",
     "AgCl has the same solubility in both, because K_sp is a constant.",
     "AgCl is more soluble in the NaCl solution because Na⁺ reacts with Ag⁺."],
    "The NaCl provides Cl⁻, a common ion for the equilibrium AgCl(s) ⇌ Ag⁺ + Cl⁻. By Le Châtelier's principle the equilibrium shifts toward the solid, reducing the solubility. K_sp does not change, but the equilibrium concentration of Ag⁺ does."),
  G(7, {
    text: "A sample of N₂O₄(g) is placed in a rigid container and allowed to react according to N₂O₄(g) ⇌ 2 NO₂(g). The concentrations of both gases are measured over time and are shown in the graph.",
    figures: [fig(approach, "A graph of concentration in molar against time in seconds. The N2O4 concentration falls from 0.80 toward 0.30. The NO2 concentration rises from 0 toward 1.0. Both curves level off after about 100 seconds.")],
  }, [
    M(7, "Which statement describes the system at 100 s and beyond?",
      ["The system is at equilibrium, because the concentrations are no longer changing.",
       "The reaction has stopped, because the concentration of N₂O₄ is not zero.",
       "The forward reaction has stopped, because the concentration of NO₂ is constant.",
       "The system is not at equilibrium, because both reactant and product are present."],
      "After about 100 s the concentrations stay constant, which means the forward and reverse reaction rates are equal. Equilibrium is dynamic: both reactions continue, but their rates match, so there is no net change."),
    S(7, "What is the value of the equilibrium constant, K, for the reaction?",
      ["0.30", "1.0", "3.3", "10"], 2,
      "At equilibrium [NO₂] = 1.0 M and [N₂O₄] = 0.30 M, so K = [NO₂]²/[N₂O₄] = (1.0)²/(0.30) = 3.3."),
  ]),

  // ================= Unit 8 (9) =================
  S(8,
    "Hydrofluoric acid, HF, is a weak acid with K_a = 7.2 × 10⁻⁴. What is the approximate pH of a 0.10 M HF solution?",
    ["1.00", "2.07", "3.14", "4.14"], 1,
    "For a weak acid, [H⁺] ≈ √(K_aC) = √((7.2 × 10⁻⁴)(0.10)) = 8.5 × 10⁻³ M, so pH = −log(8.5 × 10⁻³) = 2.07. A pH of 1.00 would be the value for a strong acid at the same concentration."),
  M(8,
    "Which of the following species is amphiprotic?",
    ["HCO₃⁻", "CO₃²⁻", "H₂CO₃", "NO₃⁻"],
    "An amphiprotic species can both donate and accept a proton. HCO₃⁻ can donate a proton (forming CO₃²⁻) or accept one (forming H₂CO₃). CO₃²⁻ can only accept a proton, H₂CO₃ can only donate protons in this series, and NO₃⁻ is a very weak base that is not amphiprotic."),
  S(8,
    "The acid dissociation constant of HCN is K_a = 6.2 × 10⁻¹⁰. What is the base dissociation constant, K_b, for the cyanide ion, CN⁻? (K_w = 1.0 × 10⁻¹⁴)",
    ["6.2 × 10⁻²⁴", "1.0 × 10⁻¹⁴", "1.6 × 10⁻⁵", "6.2 × 10⁻⁴"], 2,
    "For a conjugate acid–base pair, K_aK_b = K_w, so K_b = (1.0 × 10⁻¹⁴)/(6.2 × 10⁻¹⁰) = 1.6 × 10⁻⁵."),
  G(8, {
    text: "A 25.0 mL sample of 0.100 M HCl is titrated with 0.100 M NaOH. The titration curve is shown. The table gives the pH ranges over which several indicators change color.",
    figures: [fig(C.titrationCurve({ Ca: 0.1, Va: 25, Cb: 0.1, vMax: 50 }), "A titration curve of pH against volume of NaOH added. The pH starts at 1, rises slowly, rises almost vertically near 25 milliliters from about pH 3 to pH 11, and levels off near pH 12.5."),
      table(["Indicator", "pH range of color change"], [["Methyl red", "4.4 – 6.2"], ["Bromothymol blue", "6.0 – 7.6"], ["Phenolphthalein", "8.2 – 10.0"]])],
  }, [
    S(8, "What is the pH at the equivalence point of this titration?",
      ["1.00", "7.00", "8.72", "12.0"], 1,
      "HCl and NaOH are a strong acid and a strong base. At the equivalence point the solution contains only Na⁺ and Cl⁻, which do not affect the pH, so the pH is 7.00."),
    M(8, "Which indicator changes color at a pH closest to the pH of the equivalence point?",
      ["Bromothymol blue", "Methyl red", "Phenolphthalein", "All three change color at exactly the equivalence point."],
      "The best indicator changes color over a range that includes the equivalence-point pH. The equivalence point is at pH 7.00, which falls within the 6.0–7.6 range of bromothymol blue. (Because the curve is so steep, the other two would also be usable, but their color changes would occur slightly before or after the equivalence point.)"),
  ]),
  S(8,
    "A buffer contains 0.50 mol of NH₃ and 0.50 mol of NH₄⁺ in 1.0 L of solution; the pK_a of NH₄⁺ is 9.26. What is the pH of the buffer after 0.010 mol of HCl is added to it? (Assume no change in volume.)",
    ["9.00", "9.24", "9.26", "9.50"], 1,
    "The added H⁺ reacts with NH₃: [NH₃] becomes 0.49 M and [NH₄⁺] becomes 0.51 M. pH = pK_a + log([NH₃]/[NH₄⁺]) = 9.26 + log(0.49/0.51) = 9.26 − 0.017 = 9.24. The pH changes very little, which is how a buffer works."),
  M(8,
    "An aqueous solution of NH₄Cl is acidic. Which statement best explains why?",
    ["The NH₄⁺ ion is the conjugate acid of a weak base and donates a proton to water.",
     "The Cl⁻ ion is the conjugate base of a weak acid and accepts a proton from water.",
     "NH₄Cl is a strong acid.",
     "The NH₄⁺ ion reacts with water to produce OH⁻."],
    "NH₄⁺ is the conjugate acid of the weak base NH₃, so it donates protons to water: NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺. Cl⁻ is the conjugate base of a strong acid and does not affect the pH."),
  S(8,
    "A solution has [OH⁻] = 2.5 × 10⁻³ M at 25 °C. What is the pH of the solution?",
    ["2.60", "3.40", "10.60", "11.40"], 3,
    "pOH = −log(2.5 × 10⁻³) = 2.60, so pH = 14.00 − 2.60 = 11.40."),
  M(8,
    "What is the conjugate base of the dihydrogen phosphate ion, H₂PO₄⁻?",
    ["HPO₄²⁻", "H₃PO₄", "PO₄³⁻", "H₃O⁺"],
    "A conjugate base is formed when an acid loses a proton. Removing H⁺ from H₂PO₄⁻ gives HPO₄²⁻. (H₃PO₄ is the conjugate acid of H₂PO₄⁻.)"),

  // ================= Unit 9 (6) =================
  S(9,
    "A reaction has an equilibrium constant K = 1 × 10⁵ at 298 K. What is ΔG° for the reaction? (R = 8.314 J/(mol·K))",
    ["−57.0 kJ", "−28.5 kJ", "+28.5 kJ", "+57.0 kJ"], 1,
    "ΔG° = −RT ln K = −(8.314)(298)(ln 10⁵) = −(2477.6)(11.51) = −28,500 J = −28.5 kJ. A large K corresponds to a negative ΔG°."),
  S(9,
    "A galvanic cell has a standard cell potential of E° = 1.10 V and involves the transfer of 2 mol of electrons. What is the cell potential at 25 °C when the reaction quotient is Q = 100? (E = E° − (0.0592/n) log Q)",
    ["0.98 V", "1.04 V", "1.10 V", "1.16 V"], 1,
    "E = E° − (0.0592/n) log Q = 1.10 − (0.0592/2) log(100) = 1.10 − (0.0296)(2) = 1.10 − 0.059 = 1.04 V. When Q > 1 the reaction has progressed beyond the standard state, so the cell potential is lower."),
  M(9,
    "A reaction has ΔH > 0 and ΔS > 0. Under what conditions is the reaction spontaneous?",
    ["At high temperatures, where the −TΔS term outweighs the positive ΔH", "At all temperatures, because ΔS is positive for the reaction", "At low temperatures, because the reaction absorbs energy from its surroundings", "At no temperature, because ΔH is positive for the reaction"],
    "Spontaneity requires ΔG = ΔH − TΔS < 0. With ΔH > 0, the −TΔS term must outweigh ΔH, which happens when T is large enough. At low temperature the positive ΔH dominates and the reaction is nonspontaneous."),
  G(9, {
    text: "A galvanic cell is constructed using an iron electrode in 1.0 M Fe²⁺ and a silver electrode in 1.0 M Ag⁺, connected by a salt bridge, as shown. Standard reduction potentials: Ag⁺ + e⁻ → Ag, E° = +0.80 V; Fe²⁺ + 2e⁻ → Fe, E° = −0.44 V.",
    figures: [fig(C.galvanicCell({ left: { metal: "Fe", sol: "1.0 M Fe²⁺" }, right: { metal: "Ag", sol: "1.0 M Ag⁺" }, electronDir: "right" }), "A galvanic cell with an iron electrode in iron ion solution on the left and a silver electrode in silver ion solution on the right, connected by a wire with a voltmeter and a salt bridge. Electrons flow through the wire from the iron toward the silver.")],
  }, [
    S(9, "What is the standard cell potential, E°cell, for this cell?",
      ["0.36 V", "0.80 V", "1.24 V", "2.04 V"], 2,
      "E°cell = E°(cathode) − E°(anode) = (+0.80) − (−0.44) = +1.24 V. The potentials are not multiplied by the stoichiometric coefficients, so doubling the silver half-reaction does not change E°."),
    M(9, "As the cell operates, what happens to the mass of the iron electrode?",
      ["It decreases, because Fe is oxidized to Fe²⁺ at the anode.",
       "It increases, because Fe²⁺ is reduced to Fe at the iron electrode.",
       "It stays the same, because the iron electrode is inert.",
       "It increases, because silver plates onto the iron."],
      "Iron has the lower reduction potential, so it is oxidized at the anode: Fe(s) → Fe²⁺(aq) + 2e⁻. Iron atoms leave the electrode as ions, so the mass of the iron electrode decreases while silver ions are reduced and plate onto the silver electrode."),
  ]),
  M(9,
    "Molten sodium chloride is electrolyzed using inert electrodes. Which substance is produced at the cathode?",
    ["Na(l)", "Cl₂(g)", "NaOH(aq)", "H₂(g)"],
    "At the cathode, reduction occurs. In molten NaCl the only species that can be reduced is Na⁺, which gains an electron to form liquid sodium: Na⁺ + e⁻ → Na(l). Chlorine gas forms at the anode by oxidation of Cl⁻."),
];
