import { S, M, G } from "./pool.mjs";
import * as C from "./chemfigs.mjs";
const { fig, table, chart, curve, COL } = C;

export const config = { hub: "chemistry", prefix: "ce", N: 4, file: "exam4.js", title: "AP Chemistry — Exam 4", seed: 44, units: { 1: 5, 2: 5, 3: 12, 4: 6, 5: 6, 6: 5, 7: 6, 8: 9, 9: 6 } };

const vp = (Tb) => curve((T) => 760 * Math.exp(0.05 * (T - Tb)), 20, 100, 80).filter((p) => p[1] <= 1200);
const vaporPressure = chart({
  w: 520, h: 330, x: [20, 100, 20], y: [0, 1200, 200], xLabel: "Temperature (°C)", yLabel: "Vapor pressure (torr)", legend: true,
  series: [{ name: "Liquid A", pts: vp(35), color: COL.a }, { name: "Liquid B", pts: vp(78), color: COL.b }, { name: "Liquid C", pts: vp(100), color: COL.c }],
  annotations: [{ type: "hline", y: 760 }, { type: "text", x: 22, y: 800, s: "760 torr", size: 12 }],
});
const lnA = chart({
  w: 520, h: 320, x: [0, 60, 10], y: [-4, -0.5, 0.5], xLabel: "Time (s)", yLabel: "ln [A]", xFmt: (v) => v, yFmt: (v) => v.toFixed(1),
  series: [{ name: "ln[A]", pts: [[0, Math.log(0.4)], [10, Math.log(0.4) - 0.5], [20, Math.log(0.4) - 1.0], [30, Math.log(0.4) - 1.5], [40, Math.log(0.4) - 2.0], [50, Math.log(0.4) - 2.5], [60, Math.log(0.4) - 3.0]], color: COL.a, markers: true }],
});

export default [
  // ================= Unit 1 (5) =================
  S(1,
    "What is the mass of 3.01 × 10²³ molecules of water? (Molar mass of H₂O = 18.0 g/mol; Avogadro's number = 6.02 × 10²³.)",
    ["4.50 g", "9.00 g", "18.0 g", "36.0 g"], 1,
    "3.01 × 10²³ molecules is 0.500 mol, and the mass is (0.500 mol)(18.0 g/mol) = 9.00 g."),
  G(1, {
    text: "The photoelectron spectrum of a neutral atom of an element in the second period is shown.",
    figures: [fig(C.pesSpectrum({ peaks: [{ E: 53.2, n: 2, label: "1s" }, { E: 3.12, n: 2, label: "2s" }, { E: 1.31, n: 4, label: "2p" }], xMax: 100, xTicks: [0.1, 1, 10, 100] }), "A photoelectron spectrum on a logarithmic binding energy axis with three peaks: 53.2 megajoules per mole with relative height 2, 3.12 with height 2, and 1.31 with height 4.")],
  }, [
    M(1, "Name the element whose atoms gave this spectrum.",
      ["Oxygen", "Nitrogen", "Fluorine", "Carbon"],
      "The relative peak heights are 2 : 2 : 4, corresponding to 1s²2s²2p⁴. That is 8 electrons, so the element has 8 protons and is oxygen."),
    M(1, "How would the photoelectron spectrum of fluorine compare with this spectrum?",
      ["The 2p peak would be taller (5 electrons), and all of the peaks would be at higher binding energies.",
       "The 2p peak would be taller (5 electrons), and all of the peaks would be at lower binding energies.",
       "The 2s peak would be taller, and the 2p peak would be the same height.",
       "The spectrum would be identical, because both elements are in the same period."],
      "Fluorine has configuration 1s²2s²2p⁵, so its 2p peak represents five electrons rather than four. It also has one more proton, which increases the effective nuclear charge and the binding energy of every subshell."),
  ]),
  M(1,
    "The radius of the Li⁺ ion is much smaller than the radius of the Li atom. Which statement best explains this?",
    ["The outer 2s electron is removed, leaving only the more tightly held 1s electrons.", "Li⁺ has more protons than the Li atom, so the nuclear charge is greater.", "The Li⁺ ion has a larger number of electrons than the neutral Li atom has.", "The 1s electrons in Li⁺ are less strongly attracted to the nucleus than before."],
    "When Li loses its valence electron from the 2s subshell, the outermost shell is removed entirely. The remaining two 1s electrons are in a smaller shell and are pulled in by the same nuclear charge (3+), so the ion is much smaller."),
  S(1,
    "Naturally occurring boron consists of two isotopes: ¹⁰B (mass 10.0 amu, 19.9% abundance) and ¹¹B (mass 11.0 amu, 80.1% abundance). What is the average atomic mass of boron?",
    ["10.2 amu", "10.5 amu", "10.8 amu", "11.0 amu"], 2,
    "The average atomic mass is (0.199)(10.0) + (0.801)(11.0) = 1.99 + 8.81 = 10.8 amu, which is close to 11 because ¹¹B is much more abundant."),

  // ================= Unit 2 (5) =================
  M(2,
    "What is the molecular geometry around the carbon atom in formaldehyde, H₂C=O?",
    ["Trigonal planar", "Trigonal pyramidal", "Tetrahedral", "Bent"],
    "The carbon atom has three electron domains: two C–H single bonds and one C=O double bond (a double bond counts as one domain). With no lone pairs, the geometry is trigonal planar."),
  M(2,
    "In which of the following molecules is the carbon atom sp² hybridized?",
    ["C₂H₄ (ethene)", "C₂H₂ (ethyne)", "CH₄ (methane)", "CO₂"],
    "Each carbon atom in ethene has three electron domains (two C–H bonds and one C=C double bond), which corresponds to sp² hybridization. The carbon atoms in ethyne and CO₂ are sp (two domains), and carbon in methane is sp³ (four domains)."),
  M(2,
    "Which of the following is a molecular solid?",
    ["I₂", "NaCl", "SiO₂", "Cu"],
    "A molecular solid consists of discrete molecules held together by intermolecular forces. Solid iodine is made of I₂ molecules held by London dispersion forces. NaCl is ionic, SiO₂ is a network covalent solid, and Cu is a metallic solid."),
  S(2,
    "How many valence electrons must be shown in a correct Lewis structure of the nitrate ion, NO₃⁻?",
    ["22", "23", "24", "26"], 2,
    "Nitrogen contributes 5 electrons and each oxygen contributes 6, for 5 + 3(6) = 23. The negative charge adds one more electron, for a total of 24."),
  M(2,
    "Lithium fluoride, LiF, has a much higher melting point than cesium iodide, CsI. Which statement best explains this?",
    ["The Li⁺ and F⁻ ions are smaller, so the Coulombic attraction between them is stronger.", "LiF has covalent bonds between its atoms, while CsI has ionic bonds between its ions.", "The ions in CsI have greater charges than the ions in LiF, so CsI holds together more strongly.", "LiF has much stronger London dispersion forces than CsI because it has more electrons."],
    "Both compounds are made of ions with charges of +1 and −1, so the difference is in the ion sizes. Smaller ions can approach one another more closely, and by Coulomb's law the attractive force increases as the distance decreases. LiF therefore has the greater lattice energy and the higher melting point."),

  // ================= Unit 3 (12) =================
  M(3,
    "The boiling points of the noble gases increase from helium (−269 °C) to xenon (−108 °C). Which statement best explains this trend?",
    ["The London dispersion forces increase as the atoms get larger with more electrons.", "The dipole–dipole forces increase as the atomic number of the noble gas increases.", "The atoms form stronger covalent bonds with each other as the atoms get larger.", "The hydrogen bonding between the atoms increases going down the group."],
    "The noble gases are nonpolar atoms, so the only attractions between them are London dispersion forces. Larger atoms have more electrons and are more polarizable, so the dispersion forces and the boiling points are greater."),
  M(3,
    "Which of the following liquids is expected to have the greatest viscosity at 25 °C?",
    ["HOCH₂CH₂OH (ethylene glycol)", "CH₃OH (methanol)", "C₆H₁₄ (hexane)", "CH₃CH₂OH (ethanol)"],
    "Viscosity increases with the strength of the intermolecular forces and with the molecule's ability to become tangled. Ethylene glycol has two O–H groups per molecule and forms extensive hydrogen bonds, so its molecules resist flowing past one another more than the others."),
  S(3,
    "What is the pressure of 0.50 mol of an ideal gas in a 2.5 L container at 300. K? (R = 0.0821 L·atm/(mol·K))",
    ["2.46 atm", "4.93 atm", "9.86 atm", "49.3 atm"], 1,
    "P = nRT/V = (0.50)(0.0821)(300.)/(2.5) = 12.3/2.5 = 4.93 atm."),
  S(3,
    "A gas has a density of 1.96 g/L at STP. What is the molar mass of the gas? (1 mol of an ideal gas occupies 22.4 L at STP.)",
    ["11.4 g/mol", "22.4 g/mol", "43.9 g/mol", "87.8 g/mol"], 2,
    "The molar mass is the density times the molar volume: (1.96 g/L)(22.4 L/mol) = 43.9 g/mol."),
  G(3, {
    text: "The graph shows the vapor pressure of three liquids, A, B, and C, as a function of temperature. The horizontal line marks 760 torr (1 atm).",
    figures: [fig(vaporPressure, "A graph of vapor pressure in torr against temperature in degrees Celsius for three liquids. All three curves rise with temperature. Liquid A crosses the 760 torr line at about 35 degrees, liquid B at about 78 degrees, and liquid C at about 100 degrees.")],
  }, [
    M(3, "Which liquid has the strongest intermolecular forces?",
      ["Liquid C, because it has the lowest vapor pressure at any given temperature.",
       "Liquid A, because it has the highest vapor pressure at any given temperature.",
       "Liquid B, because its curve is in the middle.",
       "They all have the same intermolecular forces, because the curves have the same shape."],
      "Stronger intermolecular forces make it harder for molecules to escape into the gas phase, so the vapor pressure is lower at a given temperature and a higher temperature is needed to reach 760 torr. Liquid C has the lowest vapor pressure at each temperature."),
    S(3, "What is the normal boiling point of liquid B?",
      ["35 °C", "78 °C", "100 °C", "760 °C"], 1,
      "The normal boiling point is the temperature at which the vapor pressure equals 760 torr. Curve B crosses the 760 torr line at about 78 °C."),
  ]),
  S(3,
    "Hydrogen gas is collected over water at a total pressure of 755 torr. The vapor pressure of water at the temperature of the experiment is 23.8 torr. What is the partial pressure of the hydrogen?",
    ["23.8 torr", "731 torr", "755 torr", "779 torr"], 1,
    "By Dalton's law, the total pressure is the sum of the partial pressures: P(H₂) = P_total − P(H₂O) = 755 − 23.8 = 731 torr."),
  S(3,
    "A solution has a transmittance of 10% at a certain wavelength. What is the absorbance of the solution at this wavelength? (A = −log T)",
    ["0.10", "1.0", "10", "100"], 1,
    "With T = 0.10, A = −log(0.10) = 1.0. An absorbance of 1.0 means that 90% of the light is absorbed."),
  M(3,
    "Which of the following solvents would best dissolve iodine, I₂?",
    ["CCl₄", "H₂O", "CH₃OH", "NH₃"],
    "Iodine is a nonpolar molecule held together by London dispersion forces. By the principle that like dissolves like, it dissolves best in a nonpolar solvent such as carbon tetrachloride. Water, methanol, and ammonia are polar and form hydrogen bonds with themselves."),
  S(3,
    "A 10.0 mL sample of 0.500 M solution is diluted with water to a final volume of 100. mL. Then 25.0 mL of this diluted solution is diluted with water to a final volume of 50.0 mL. What is the concentration of the final solution?",
    ["0.0125 M", "0.0250 M", "0.0500 M", "0.250 M"], 1,
    "The first dilution gives (0.500 M)(10.0/100.) = 0.0500 M. The second dilution halves it: (0.0500 M)(25.0/50.0) = 0.0250 M."),
  M(3,
    "In a paper chromatography experiment, a nonpolar compound travels farther up the paper (greater R_f) than a polar compound when a nonpolar solvent is used with a polar paper. Which statement best explains this?",
    ["The polar compound sticks more strongly to the polar paper, so it moves more slowly.", "The nonpolar compound is attracted more strongly to the polar paper than the polar compound is.", "The polar compound is more soluble in the nonpolar solvent, so it travels the farthest.", "The compounds move at the same rate, but the nonpolar compound is the lighter one."],
    "The paper (stationary phase) is polar, so polar compounds stick to it more strongly and spend less time dissolved in the moving nonpolar solvent. They travel a shorter distance, while nonpolar compounds are carried farther by the solvent."),
  S(3,
    "What volume of O₂ gas, measured at 300. K and 1.00 atm, is produced by the decomposition of 0.200 mol of H₂O₂? 2 H₂O₂(l) → 2 H₂O(l) + O₂(g) (R = 0.0821 L·atm/(mol·K))",
    ["1.23 L", "2.46 L", "4.92 L", "24.6 L"], 1,
    "The mole ratio H₂O₂ : O₂ is 2 : 1, so 0.200 mol H₂O₂ gives 0.100 mol O₂. Then V = nRT/P = (0.100)(0.0821)(300.)/(1.00) = 2.46 L."),

  // ================= Unit 4 (6) =================
  S(4,
    "A 5.0 g sample of Mg (molar mass 24.3 g/mol) is burned in 5.0 g of O₂ (molar mass 32.0 g/mol): 2 Mg + O₂ → 2 MgO (molar mass of MgO = 40.3 g/mol). What is the maximum mass of MgO that can form?",
    ["5.0 g", "8.3 g", "10.0 g", "12.6 g"], 1,
    "There are 5.0/24.3 = 0.206 mol Mg and 5.0/32.0 = 0.156 mol O₂. The reaction needs 2 mol Mg for each mol O₂, so the Mg (0.206 mol) can use only 0.103 mol of O₂: Mg is limiting. It forms 0.206 mol of MgO, which has a mass of (0.206)(40.3) = 8.3 g."),
  M(4,
    "When aqueous lead(II) nitrate is mixed with aqueous potassium iodide, a yellow solid forms. Which is the net ionic equation?",
    ["Pb²⁺(aq) + 2 I⁻(aq) → PbI₂(s)", "Pb(NO₃)₂(aq) + 2 KI(aq) → PbI₂(s) + 2 KNO₃(aq)", "K⁺(aq) + NO₃⁻(aq) → KNO₃(s)", "Pb²⁺(aq) + 2 NO₃⁻(aq) → Pb(NO₃)₂(s)"],
    "The yellow solid is PbI₂, which is insoluble. K⁺ and NO₃⁻ stay dissolved as spectator ions. The net ionic equation shows only the ions that combine: Pb²⁺ + 2 I⁻ → PbI₂(s)."),
  S(4,
    "A 1.50 g sample of impure CaCO₃ is heated and produces 0.0120 mol of CO₂ by CaCO₃(s) → CaO(s) + CO₂(g). The molar mass of CaCO₃ is 100.1 g/mol. What is the mass percent of CaCO₃ in the sample?",
    ["60.0%", "75.0%", "80.0%", "120%"], 2,
    "0.0120 mol CO₂ comes from 0.0120 mol CaCO₃, which has a mass of (0.0120)(100.1) = 1.20 g. The percent is (1.20/1.50)(100) = 80.0%."),
  G(4, {
    text: "The particle diagrams show a mixture of A atoms and B₂ molecules before and after a reaction goes to completion.",
    figures: [fig(C.particleBoxes({ boxes: [{ title: "Before reaction", parts: [{ kind: "A", n: 6 }, { kind: "B2", n: 2 }] }, { title: "After reaction", parts: [{ kind: "AB", n: 4 }, { kind: "A", n: 2 }] }], seed: 21 }), "Two boxes of particles. Before the reaction the box contains six single A atoms and two B2 molecules. After the reaction it contains four AB molecules and two single A atoms.")],
  }, [
    M(4, "Which equation best represents the reaction shown?",
      ["2 A + B₂ → 2 AB", "A + B₂ → AB₂", "A + B → AB", "3 A + B₂ → 2 AB + A"],
      "Two B₂ molecules (four B atoms) combined with four of the six A atoms to form four AB molecules, leaving two A atoms unreacted. The ratio of reactants consumed is 4 A : 2 B₂ = 2 A : 1 B₂, giving 2 A + B₂ → 2 AB."),
    M(4, "Which reactant limits the amount of product that can form?",
      ["B₂", "A", "AB", "Neither, because both are partly consumed."],
      "The limiting reactant is completely used up. No B₂ molecules remain after the reaction, while two A atoms are left over, so B₂ limited the amount of product that could form."),
  ]),
  M(4,
    "In the reaction 2 Al(s) + 3 Cu²⁺(aq) → 2 Al³⁺(aq) + 3 Cu(s), which species is the reducing agent?",
    ["Al", "Cu²⁺", "Al³⁺", "Cu"],
    "The reducing agent is the species that is oxidized, which gives up electrons. Aluminum goes from 0 to +3 and is oxidized, so Al is the reducing agent. Copper(II) is reduced (+2 to 0) and is the oxidizing agent."),

  // ================= Unit 5 (6) =================
  G(5, {
    text: "The concentration of reactant A was monitored over time for the reaction A → products, and the natural logarithm of the concentration was plotted against time. The data fall on a straight line, as shown.",
    figures: [fig(lnA, "A graph of the natural logarithm of the concentration of A against time in seconds. Seven points fall on a straight line decreasing from minus 0.92 at 0 seconds to minus 3.92 at 60 seconds, a slope of minus 0.050 per second.")],
  }, [
    S(5, "What is the rate constant for the reaction?",
      ["0.0200 s⁻¹", "0.0500 s⁻¹", "0.916 s⁻¹", "20.0 s⁻¹"], 1,
      "A linear plot of ln[A] versus time shows the reaction is first order. The slope equals −k. The line falls by 0.50 for every 10 s, so the slope is −0.050 s⁻¹ and k = 0.050 s⁻¹."),
    S(5, "What was the initial concentration of A?",
      ["0.40 M", "0.92 M", "1.0 M", "2.5 M"], 0,
      "The y-intercept of the line is ln[A]₀ = −0.916, so [A]₀ = e^(−0.916) = 0.40 M. The intercept is the logarithm of the initial concentration, not the concentration itself."),
    S(5, "What is the half-life of the reaction?",
      ["6.9 s", "13.9 s", "20.0 s", "27.7 s"], 1,
      "For a first-order reaction, t½ = ln 2/k = 0.693/0.0500 s⁻¹ = 13.9 s."),
  ]),
  M(5,
    "In a reaction mechanism, a catalyst and an intermediate are both species that do not appear in the overall balanced equation. Which statement correctly distinguishes them?",
    ["A catalyst is consumed in an early step and regenerated in a later step, while an intermediate is produced in one step and consumed in a later step.",
     "A catalyst is produced in an early step and consumed in a later step, while an intermediate is consumed first and regenerated later.",
     "A catalyst is present only in the first step, and an intermediate is present only in the last step.",
     "There is no difference between a catalyst and an intermediate."],
    "A catalyst enters the mechanism as a reactant (it is consumed) and is regenerated in a later step, so it has no net change. An intermediate is the opposite: it is formed in an early step and consumed in a later step. Neither appears in the overall equation."),
  M(5,
    "According to collision theory, which of the following best explains why increasing the concentration of the reactants usually increases the reaction rate?",
    ["The molecules collide more often, so more effective collisions occur each second.", "The activation energy of the reaction decreases when the concentration rises.", "Each collision releases more energy when the reactants are more concentrated.", "The rate constant increases whenever the concentration of a reactant is raised."],
    "A higher concentration puts more molecules in a given volume, so collisions are more frequent. The fraction of collisions with enough energy and the correct orientation does not change, but the number of effective collisions per second increases. The rate constant and activation energy depend on temperature and catalysts, not concentration."),
  M(5,
    "A reaction is first order in A and zero order in B. If [A] is doubled and [B] is halved, what happens to the rate of the reaction?",
    ["The rate doubles.", "The rate is unchanged.", "The rate is halved.", "The rate quadruples."],
    "The rate depends on [A] to the first power, so doubling [A] doubles the rate. The reaction is zero order in B, so changing [B] has no effect. The net effect is that the rate doubles."),

  // ================= Unit 6 (5) =================
  S(6,
    "How much thermal energy is absorbed by a 25.0 g sample of aluminum when its temperature increases from 20.0 °C to 100.0 °C? (The specific heat of aluminum is 0.900 J/(g·°C).)",
    ["225 J", "1.80 kJ", "2.25 kJ", "18.0 kJ"], 1,
    "q = mcΔT = (25.0 g)(0.900 J/(g·°C))(80.0 °C) = 1800 J = 1.80 kJ."),
  S(6,
    "The standard enthalpies of formation are ΔHf°[SO₂(g)] = −296.8 kJ/mol and ΔHf°[SO₃(g)] = −395.7 kJ/mol. What is ΔH° for 2 SO₂(g) + O₂(g) → 2 SO₃(g)?",
    ["−197.8 kJ", "−98.9 kJ", "+98.9 kJ", "+197.8 kJ"], 0,
    "ΔH° = 2(−395.7) − [2(−296.8) + 0] = −791.4 + 593.6 = −197.8 kJ. The coefficients in the balanced equation multiply the enthalpies of formation."),
  S(6,
    "Use the average bond enthalpies C–H = 413 kJ/mol, Cl–Cl = 243 kJ/mol, C–Cl = 339 kJ/mol, and H–Cl = 431 kJ/mol to estimate ΔH for CH₄ + Cl₂ → CH₃Cl + HCl.",
    ["−114 kJ", "−38 kJ", "+38 kJ", "+114 kJ"], 0,
    "One C–H bond and one Cl–Cl bond are broken: 413 + 243 = 656 kJ. One C–Cl bond and one H–Cl bond are formed: 339 + 431 = 770 kJ. ΔH ≈ 656 − 770 = −114 kJ."),
  M(6,
    "A student dissolves a solid in water in an insulated cup, and the temperature of the solution increases. Which statement is correct?",
    ["The dissolving process is exothermic, because thermal energy is released to the solution.",
     "The dissolving process is endothermic, because the solution gained thermal energy.",
     "The dissolving process has ΔH > 0, because the temperature increased.",
     "The dissolving process does not involve a change in energy."],
    "The temperature of the solution increased because the dissolving process released thermal energy to it. A process that releases heat to the surroundings is exothermic, with ΔH < 0."),
  M(6,
    "Which of the following is a state function?",
    ["Enthalpy, H", "The heat, q, absorbed by a system for a specific path", "The work done by a system for a specific path", "The time taken for a reaction"],
    "A state function depends only on the current state of the system, not on how it got there. Enthalpy is a state function, which is why Hess's law works. Heat and work depend on the path."),

  // ================= Unit 7 (6) =================
  S(7,
    "For CO(g) + 2 H₂(g) ⇌ CH₃OH(g), the equilibrium concentrations are [CO] = 0.20 M, [H₂] = 0.30 M, and [CH₃OH] = 0.12 M. What is the value of K?",
    ["0.15", "1.5", "6.7", "67"], 2,
    "K = [CH₃OH]/([CO][H₂]²) = 0.12/((0.20)(0.30)²) = 0.12/0.018 = 6.7."),
  M(7,
    "A system at equilibrium contains N₂, H₂, and NH₃. Some NH₃ is removed from the container at constant temperature and volume. What happens?",
    ["The equilibrium shifts toward the products, forming more NH₃.",
     "The equilibrium shifts toward the reactants, forming more N₂ and H₂.",
     "The value of K increases.",
     "Nothing happens, because the system is at equilibrium."],
    "Removing a product reduces its concentration, so Q becomes smaller than K. By Le Châtelier's principle, the system shifts toward the products to replace some of the NH₃. K does not change, because the temperature is constant."),
  S(7,
    "For H₂(g) + I₂(g) ⇌ 2 HI(g), a mixture has [H₂] = 0.10 M, [I₂] = 0.20 M, and [HI] = 0.40 M. What is the value of the reaction quotient, Q?",
    ["0.010", "0.50", "8.0", "16"], 2,
    "Q = [HI]²/([H₂][I₂]) = (0.40)²/((0.10)(0.20)) = 0.16/0.020 = 8.0."),
  M(7,
    "The reaction N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g) is exothermic. How does the value of K change if the temperature is increased?",
    ["K decreases, because the equilibrium shifts toward the reactants.", "K increases, because the reaction rate increases.", "K does not change, because K depends only on the concentrations.", "K increases, because heat is added to the system."],
    "For an exothermic reaction, heat is a product, so raising the temperature shifts the equilibrium toward the reactants and the value of K decreases. K depends on temperature, not on the concentrations."),
  G(7, {
    text: "The equilibrium constant for a gas-phase reaction was measured at three temperatures. The data are shown in the table.",
    figures: [table(["Temperature (K)", "K"], [["400", "50"], ["500", "10"], ["600", "2.5"]])],
  }, [
    M(7, "What does the data show about the enthalpy change of the reaction?",
      ["The reaction is exothermic, because K decreases as the temperature increases.",
       "The reaction is endothermic, because K decreases as the temperature increases.",
       "The reaction is exothermic, because K is greater than 1.",
       "Nothing can be concluded about ΔH from the value of K."],
      "K decreases as the temperature rises, meaning the equilibrium shifts toward the reactants when heat is added. Heat acts like a product, which is the behavior of an exothermic reaction."),
    M(7, "A mixture of the gases at equilibrium at 500 K is heated to 600 K. What happens to the amount of product?",
      ["It decreases, because K is smaller at 600 K.", "It increases, because heating always favors the products.", "It stays the same, because the system was at equilibrium.", "It becomes zero."],
      "At 600 K, K is smaller (2.5 versus 10), so the new equilibrium contains a smaller proportion of products. The system shifts toward the reactants until Q equals the new value of K."),
  ]),

  // ================= Unit 8 (9) =================
  S(8,
    "What is the pH of a 0.050 M solution of HNO₃?",
    ["0.050", "1.30", "2.30", "12.70"], 1,
    "HNO₃ is a strong acid, so [H⁺] = 0.050 M and pH = −log(0.050) = 1.30."),
  S(8,
    "A 0.10 M solution of a weak acid HA has a pH of 3.00. What is the approximate value of K_a for the acid?",
    ["1.0 × 10⁻⁷", "1.0 × 10⁻⁵", "1.0 × 10⁻³", "1.0 × 10⁻¹"], 1,
    "[H⁺] = [A⁻] = 1.0 × 10⁻³ M, and [HA] ≈ 0.10 − 0.001 ≈ 0.10 M. K_a = [H⁺][A⁻]/[HA] = (1.0 × 10⁻³)²/(0.10) = 1.0 × 10⁻⁵."),
  G(8, {
    text: "A 25.0 mL sample of 0.100 M hydrofluoric acid, HF (K_a = 7.2 × 10⁻⁴, pK_a = 3.14), is titrated with 0.100 M NaOH. The titration curve is shown.",
    figures: [fig(C.titrationCurve({ Ca: 0.1, Va: 25, Cb: 0.1, Ka: 7.2e-4, vMax: 50 }), "A titration curve of pH against volume of 0.100 molar NaOH added. The pH begins near 2.1, rises gradually through a buffer region, rises steeply near 25 milliliters to about pH 11, and levels off near pH 12.5.")],
  }, [
    S(8, "Estimate the pH of the mixture at the point where 12.5 mL of NaOH has been added.",
      ["1.00", "3.14", "7.00", "8.37"], 1,
      "At 12.5 mL, half of the HF has been converted to F⁻, so [HF] = [F⁻] and pH = pK_a = 3.14."),
    M(8, "How does the pH at the equivalence point compare with 7, and why?",
      ["Greater than 7, because F⁻ is a weak acid's conjugate base and produces OH⁻", "Equal to 7, because the acid and the base are present in equal amounts", "Less than 7, because the solution began as a solution of the acid HF", "Greater than 7, because excess NaOH remains in solution at that point"],
      "At the equivalence point the solution contains F⁻, the conjugate base of a weak acid, which hydrolyzes: F⁻ + H₂O ⇌ HF + OH⁻. The solution is therefore basic, with a pH greater than 7."),
    M(8, "Which indicator is the most appropriate for this titration?",
      ["Phenolphthalein, which changes color in the pH range 8.2–10.0", "Methyl orange, which changes color in the pH range 3.1–4.4", "Bromocresol green, which changes color in the pH range 3.8–5.4", "Thymol blue (acid range), which changes color in the pH range 1.2–2.8"],
      "An indicator should change color near the pH of the equivalence point. For this titration the equivalence point is in the basic range (about pH 8), so phenolphthalein, which changes color between pH 8.2 and 10.0, is the best choice."),
  ]),
  S(8,
    "A chemist wants to prepare a buffer with pH equal to the pK_a of a weak acid HA. Starting with 0.20 mol of HA, how many moles of NaOH should be added?",
    ["0.050 mol", "0.10 mol", "0.20 mol", "0.40 mol"], 1,
    "The pH equals the pK_a when [A⁻] = [HA]. NaOH converts HA into A⁻ one-for-one, so converting half of the 0.20 mol of HA requires 0.10 mol of NaOH."),
  M(8,
    "Which of the following is a Lewis acid?",
    ["BF₃", "NH₃", "OH⁻", "Cl⁻"],
    "A Lewis acid is an electron-pair acceptor. Boron in BF₃ has an incomplete octet (only six electrons) and can accept a pair of electrons. NH₃, OH⁻, and Cl⁻ each have lone pairs to donate, so they are Lewis bases."),
  S(8,
    "What is the hydroxide ion concentration of a solution with a pH of 4.20 at 25 °C?",
    ["1.6 × 10⁻¹⁰ M", "6.3 × 10⁻⁵ M", "1.6 × 10⁻⁴ M", "6.3 × 10⁻¹⁰ M"], 0,
    "pOH = 14.00 − 4.20 = 9.80, so [OH⁻] = 10^(−9.80) = 1.6 × 10⁻¹⁰ M. The value 6.3 × 10⁻⁵ M is [H⁺] for this solution."),
  M(8,
    "Which of the following pairs of substances, dissolved in water, would make an effective buffer?",
    ["CH₃COOH and CH₃COONa", "HCl and NaCl", "HNO₃ and NaNO₃", "NaOH and NaCl"],
    "A buffer contains a weak acid and its conjugate base (or a weak base and its conjugate acid) in comparable amounts. Acetic acid and sodium acetate meet this requirement. HCl and HNO₃ are strong acids, and NaOH is a strong base."),

  // ================= Unit 9 (6) =================
  S(9,
    "Use the standard molar entropies (in J/(mol·K)): N₂(g) = 191.6, H₂(g) = 130.7, NH₃(g) = 192.5. What is ΔS° for N₂(g) + 3 H₂(g) → 2 NH₃(g)?",
    ["−198.7 J/K", "−97.7 J/K", "+97.7 J/K", "+198.7 J/K"], 0,
    "ΔS° = ΣS°(products) − ΣS°(reactants) = 2(192.5) − [191.6 + 3(130.7)] = 385.0 − 583.7 = −198.7 J/K. The entropy decreases because four moles of gas become two."),
  S(9,
    "A reaction has ΔH = +30 kJ and ΔS = +100 J/K. At what temperature does the reaction become spontaneous?",
    ["Above 30 K", "Above 300 K", "Above 3000 K", "At no temperature"], 1,
    "The reaction is spontaneous when ΔG = ΔH − TΔS < 0, so T > ΔH/ΔS = (30,000 J)/(100 J/K) = 300 K."),
  M(9,
    "Which statement is true of a reaction at equilibrium?",
    ["ΔG = 0, and ΔG° = −RT ln K", "ΔG° = 0, and K = 1", "ΔG > 0, because the reaction is not spontaneous", "ΔG < 0, because the reaction is spontaneous"],
    "At equilibrium there is no net driving force for the reaction, so ΔG = 0. The standard free energy change is related to the equilibrium constant by ΔG° = −RT ln K, and it is zero only if K = 1."),
  S(9,
    "How much charge must pass through a solution of Ag⁺ to deposit 1.08 g of silver at the cathode? (Ag⁺ + e⁻ → Ag; molar mass of Ag = 108 g/mol; 1 F = 96,500 C/mol e⁻)",
    ["96.5 C", "965 C", "9,650 C", "96,500 C"], 1,
    "1.08 g of Ag is 0.0100 mol. One electron is needed per Ag atom, so 0.0100 mol of electrons, with a charge of (0.0100)(96,500) = 965 C."),
  G(9, {
    text: "A galvanic cell is made from an aluminum electrode in 1.0 M Al³⁺ and a copper electrode in 1.0 M Cu²⁺, connected by a salt bridge. The standard reduction potentials are: Cu²⁺ + 2e⁻ → Cu, E° = +0.34 V; Al³⁺ + 3e⁻ → Al, E° = −1.66 V.",
    figures: [fig(C.galvanicCell({ left: { metal: "Al", sol: "1.0 M Al³⁺" }, right: { metal: "Cu", sol: "1.0 M Cu²⁺" }, electronDir: "right" }), "A galvanic cell with an aluminum electrode in aluminum ion solution on the left and a copper electrode in copper ion solution on the right, connected by a wire with a voltmeter and a salt bridge. Electrons flow through the wire from the aluminum toward the copper.")],
  }, [
    M(9, "At which electrode does reduction occur?",
      ["The copper electrode, which is the cathode", "The aluminum electrode, which is the cathode", "The copper electrode, which is the anode", "The aluminum electrode, which is the anode"],
      "Reduction occurs at the cathode, the electrode where the species with the more positive reduction potential is reduced. Cu²⁺ (E° = +0.34 V) is reduced to Cu at the copper electrode, and aluminum is oxidized at the anode."),
    S(9, "What is the standard cell potential, in volts?",
      ["1.32 V", "1.66 V", "2.00 V", "2.34 V"], 2,
      "E°cell = E°(cathode) − E°(anode) = 0.34 − (−1.66) = +2.00 V. Potentials are intensive properties and are not multiplied by the coefficients used to balance the electrons (2 Al + 3 Cu²⁺)."),
  ]),
];
