// Figure assignments for AP Physics 1 Exam 1 (question id -> figures).
import * as P from "./p1figs.mjs";
const { fig } = P;

export default {
  "e1-3": [fig(P.carts({ rows: [{ title: "Before the collision (frictionless track)", items: [{ x: 50, w: 76, label: "2.0 kg", v: "3.0 m/s", dir: 1 }, { x: 290, w: 96, label: "4.0 kg", v: "at rest" }] }] }), "Two carts on a track before a collision: a 2.0 kg cart moving right at 3.0 meters per second toward a 4.0 kg cart at rest.")],
  "e1-5": [fig(P.pipe({ left: ["A = 0.040 m²", "v = 2.0 m/s"], right: ["A = 0.010 m²", "v = ?"] }), "A horizontal pipe narrowing from a wide section with area 0.040 square meters and water speed 2.0 meters per second to a narrow section with area 0.010 square meters and unknown speed.")],
  "e1-8": [fig(P.springHoriz({ k: "k = 200 N/m", m: "0.50 kg", compressed: true, dimText: "0.30 m" }), "A block attached to a spring that is compressed 0.30 meters from its relaxed length against a wall, on a frictionless horizontal surface. The spring constant is 200 newtons per meter and the block's mass is 0.50 kilograms.")],
  "e1-9": [fig(P.elevator({ personText: "60 kg", aText: "a = 2.0 m/s²" }), "A 60 kilogram person standing on a scale inside an elevator that accelerates upward at 2.0 meters per second squared.")],
  "e1-12": [fig(P.carts({ rows: [
    { title: "Before", items: [{ x: 60, w: 28, shape: "ball", label: "0.15 kg", v: "20 m/s", dir: 1 }, { x: 410, w: 14, shape: "wall" }] },
    { title: "After", items: [{ x: 250, w: 28, shape: "ball", label: "0.15 kg", v: "12 m/s", dir: -1 }, { x: 410, w: 14, shape: "wall" }] }] }), "A 0.15 kilogram ball moves right at 20 meters per second toward a wall and then rebounds to the left at 12 meters per second.")],
  "e1-13": [fig(P.pushedBlock({ label: "25 kg", F: "80 N", surface: "μs = 0.40, μk = 0.30" }), "A 25 kilogram crate on a horizontal floor pushed to the right with an 80 newton force. The coefficients of friction are 0.40 static and 0.30 kinetic.")],
  "e1-15": [fig(P.dropCompare({ mode: "ramp", hText: "h" }), "Two identical blocks starting at the same height h: block 1 falling straight down, and block 2 sliding down a frictionless ramp.")],
  "e1-17": [fig(P.circleTop({ rText: "r = 0.50 m", vText: "3.0 m/s", objText: "2.0 kg" }), "Top view of a 2.0 kilogram puck moving in a horizontal circle of radius 0.50 meters at 3.0 meters per second, attached to a string from the center.")],
  "e1-18": [fig(P.carts({ rows: [{ title: "At rest, spring compressed between the carts (frictionless track)", items: [{ x: 120, w: 60, label: "m", spring: true }, { x: 262, w: 90, label: "3m" }] }] }), "Two carts at rest on a track with a compressed spring between them: a cart of mass m on the left and a cart of mass 3m on the right.")],
  "e1-19": [fig(P.pipe({ left: ["wide section"], right: ["narrow section"], points: true }), "A horizontal pipe that narrows, with point 1 in the wide section and point 2 in the narrow section, and water flowing from left to right.")],
  "e1-22": [fig(P.torqueArm({ rText: "0.40 m", F: "20 N", deg: 30 }), "A wrench with its pivot at the bolt on the left. A 20 newton force is applied at the far end, 0.40 meters from the bolt, at an angle of 30 degrees to the handle.")],
  "e1-24": [fig(P.incline({ deg: 30, blockLabel: "3.0 kg", t: 0.88, hText: "2.0 m", info: "rough", W: 470 }), "A 3.0 kilogram block at the top of a rough incline, 2.0 meters above the bottom of the incline.")],
  "e1-25": [fig(P.beam({ L: 100, supports: [{ at: 70 }], loads: [{ at: 100, kind: "hang", label: "0.30 kg" }], ticks: [{ at: 0, label: "0" }, { at: 70, label: "70 cm" }, { at: 100, label: "100 cm" }], beamLabel: "uniform meterstick" }), "A uniform meterstick balanced on a pivot at its 70 centimeter mark, with a 0.30 kilogram mass hanging from the 100 centimeter end.")],
  "e1-27": [fig(P.hingedRod({ rodLabel: "uniform rod, 6.0 kg", lenText: "2.0 m" }), "A uniform horizontal rod of mass 6.0 kilograms and length 2.0 meters hinged to a wall at its left end and held horizontal by a vertical cable at its right end.")],
  "e1-29": [fig(P.momentArm({ vText: "4.0 m/s", mText: "0.50 kg", dText: "1.5 m" }), "A ball with a mass of 0.50 kilograms moving to the right at 4.0 meters per second along a straight line. Point P is 1.5 meters from the line, measured perpendicular to it.")],
  "e1-30": [fig(P.graph({ x: [0, 6, 1], y: [-6, 6, 2], xLabel: "t (s)", yLabel: "v (m/s)", series: [{ name: "v", pts: [[0, 6], [6, -6]], color: "#3F7A94" }], annotations: [{ type: "vline", x: 5 }] }), "A velocity versus time graph: a straight line with negative slope that starts at 6 meters per second at time zero, crosses zero at 3 seconds, and reaches negative 6 meters per second at 6 seconds. A dashed vertical line marks t equals 5 seconds.")],
  "e1-32": [fig(P.graph({ x: [0, 6, 1], y: [0, 8, 2], xLabel: "x (m)", yLabel: "Force (N)", series: [{ name: "F", pts: [[0, 6], [2, 6], [6, 0]], color: "#D2705A" }] }), "A force versus position graph: the force is 6.0 newtons from 0 to 2.0 meters, then decreases linearly to zero at 6.0 meters.")],
  "e1-34": [fig(P.hangSubmerged({ objText: "0.50 kg", volText: "V = 3.0×10⁻⁴ m³" }), "A 0.50 kilogram object of volume 3.0 times 10 to the minus 4 cubic meters hanging from a string attached to a support above, completely underwater in a container of water.")],
  "e1-35": [fig(P.coordLine({ items: [{ x: 1, label: "2.0 kg" }, { x: 6, label: "3.0 kg" }] }), "A number line showing a 2.0 kilogram object at x equals 1.0 meter and a 3.0 kilogram object at x equals 6.0 meters.")],
  "e1-36": [fig(P.incline({ deg: 30, blockLabel: "10 kg", info: "frictionless" }), "A 10 kilogram block on a frictionless incline that makes a 30 degree angle with the horizontal.")],
  "e1-41": [fig(P.flatBlocks({ blocks: [{ label: "2.0 kg", w: 90 }, { label: "3.0 kg", w: 100 }], forces: [{ label: "10 N", dir: 1, on: 0, push: true, len: 90 }], surfaceLabel: "frictionless surface" }), "A 2.0 kilogram block and a 3.0 kilogram block in contact on a frictionless surface. A 10 newton force pushes the 2.0 kilogram block to the right, and it pushes on the 3.0 kilogram block.")],
};
