import { S, M, G, fig, table } from "./pool.mjs";
import * as F from "./p2figs.mjs";
import { chart, curve, COL } from "./figlib.mjs";

export const config = { hub: "physics2", prefix: "p2e", N: 4, file: "exam4.js", title: "AP Physics 2 — Exam 4", seed: 404, units: { 9: 7, 10: 6, 11: 7, 12: 6, 13: 6, 14: 5, 15: 5 }, note: "Uses g = 10 m/s²." };

const heating = chart({
  w: 520, h: 330, x: [0, 80, 10], y: [-40, 120, 20], xLabel: "Thermal energy added (kJ)", yLabel: "Temperature (°C)",
  series: [{ name: "sample", pts: [[0, -20], [4.2, 0], [37.2, 0], [79.2, 100]], color: COL.a }],
  annotations: [{ type: "text", x: 1.5, y: -33, s: "A", size: 15 }, { type: "text", x: 19, y: 10, s: "B", size: 15 }, { type: "text", x: 58, y: 62, s: "C", size: 15 }],
});
const waveTime = chart({
  w: 520, h: 300, x: [0, 1.2, 0.2], y: [-6, 6, 3], xLabel: "Time t (s)", yLabel: "Displacement y (mm)", vgrid: true,
  series: [{ name: "wave", pts: curve((t) => 5 * Math.sin((2 * Math.PI * t) / 0.4), 0, 1.2, 160), color: COL.a }],
  xFmt: (v) => (Math.round(v * 10) / 10).toString(),
});

export default [
  // ================= Unit 9 (7) =================
  S(9,
    "A cylinder with a movable piston holds an ideal gas at a pressure of 2.0 × 10⁵ Pa and a volume of 3.0 L. The gas is compressed slowly at constant temperature to a volume of 1.0 L. What is the final pressure of the gas?",
    ["1.0 × 10⁵ Pa", "3.0 × 10⁵ Pa", "6.0 × 10⁵ Pa", "1.2 × 10⁶ Pa"], 2,
    "At constant temperature, PV is constant (Boyle's law): P₂ = P₁V₁/V₂ = (2.0 × 10⁵)(3.0)/(1.0) = 6.0 × 10⁵ Pa. Decreasing the volume by a factor of 3 increases the pressure by the same factor."),
  M(9,
    "The volume of a fixed amount of ideal gas in a cylinder is decreased while its temperature is held constant. Which of the following explains, at the molecular level, why the pressure increases?",
    ["The molecules strike the walls more often, because they have less distance to travel between collisions.",
     "The molecules move faster, because the temperature increases when the gas is compressed.",
     "The molecules strike the walls with more force each time, because their average kinetic energy increases.",
     "The molecules become heavier when they are squeezed closer together."],
    "The temperature is constant, so the average kinetic energy and the typical speed of the molecules do not change. In a smaller volume each molecule travels a shorter distance between wall collisions, so collisions with the walls are more frequent and the pressure (average force per area) increases."),
  S(9,
    "A heat engine does 300 J of work during each cycle while it exhausts 700 J of heat to the cold reservoir. How much heat does the engine absorb from the hot reservoir during each cycle?",
    ["400 J", "700 J", "1000 J", "2300 J"], 2,
    "Energy conservation for one cycle gives Q_H = W + Q_C = 300 + 700 = 1000 J. (The efficiency of this engine is 300/1000 = 30%.)"),
  G(9, {
    text: "A 0.10 kg sample of a substance, initially a solid at −20 °C, is heated at a constant rate. The graph shows the temperature of the sample as a function of the thermal energy added. Segment A is the warming of the solid, segment B is a phase change at constant temperature, and segment C is the warming of the liquid.",
    figures: [fig(heating, "A graph of temperature in degrees Celsius against thermal energy added in kilojoules. The temperature rises steeply from minus 20 to 0 over the first 4.2 kilojoules (segment A), stays flat at 0 degrees until 37.2 kilojoules (segment B), and then rises more gradually to 100 degrees at 79.2 kilojoules (segment C).")],
  }, [
    S(9, "How much thermal energy is needed to melt the entire sample after it has reached its melting temperature?",
      ["4.2 kJ", "33 kJ", "37 kJ", "79 kJ"], 1,
      "The melting occurs during the flat segment B, from 4.2 kJ to 37.2 kJ of energy added, so the energy needed is 37.2 − 4.2 = 33 kJ. The value 37.2 kJ is the total energy added from the start through the end of melting."),
    M(9, "During which segment is the specific heat capacity of the substance greatest?",
      ["Segment C, because the temperature rises the least per unit of energy added.",
       "Segment A, because the temperature rises the most per unit of energy added.",
       "Segment B, because the most energy is added without a temperature change.",
       "The specific heat is the same in segments A and C, because the substance is the same."],
      "The specific heat is c = Q/(mΔT), so a smaller temperature rise for a given amount of energy means a greater specific heat. In segment C the line is less steep than in segment A, so the liquid has the larger specific heat. Segment B involves a phase change at constant temperature, where specific heat does not apply."),
  ]),
  S(9,
    "An ideal gas expands at a constant pressure of 1.0 × 10⁵ Pa from a volume of 2.0 L to a volume of 5.0 L while absorbing 600 J of heat. What is the change in the internal energy of the gas?",
    ["−300 J", "+300 J", "+600 J", "+900 J"], 1,
    "The work done by the gas is W = PΔV = (1.0 × 10⁵)(3.0 × 10⁻³) = 300 J. By the first law, ΔU = Q − W_by = 600 − 300 = +300 J. +900 J results from adding the work instead of subtracting it."),
  M(9,
    "When liquid water freezes in a freezer, the entropy of the water decreases. Why is this consistent with the second law of thermodynamics?",
    ["The heat released to the surroundings raises their entropy by more than the water's entropy falls.", "The second law applies only to gases and does not apply to liquids and solids.", "The water's entropy does not actually decrease, because its molecules become more ordered.", "The second law is violated, but only for a brief time while the water freezes."],
    "The second law requires the total entropy of an isolated system (here, the water plus its surroundings) not to decrease. As the water freezes, it releases heat to the colder surroundings, increasing their entropy by more than the water's entropy falls. The total entropy therefore increases, even though the water's entropy decreases."),

  // ================= Unit 10 (6) =================
  S(10,
    "A +2.0 μC charge is fixed at x = 0 and another +2.0 μC charge is fixed at x = 0.40 m. A small +1.0 μC test charge is placed at x = 0.10 m, as shown. What is the magnitude of the net electric force on the test charge?",
    ["1.0 N", "1.6 N", "2.0 N", "2.2 N"], 1,
    "The charge at x = 0 is 0.10 m away and pushes the test charge to the right with F₁ = (9.0 × 10⁹)(2.0 × 10⁻⁶)(1.0 × 10⁻⁶)/(0.10)² = 1.8 N. The charge at x = 0.40 m is 0.30 m away and pushes it to the left with F₂ = 0.20 N. The net force is 1.8 − 0.20 = 1.6 N to the right. Adding the magnitudes gives 2.0 N, which ignores that the forces point in opposite directions.",
    { figures: [fig(F.chargeLine({ items: [{ x: 70, q: "+", label: "+2.0 μC" }, { x: 160, name: "test" }, { x: 410, q: "+", label: "+2.0 μC" }], spans: [{ x1: 70, x2: 160, label: "0.10 m" }, { x1: 160, x2: 410, label: "0.30 m" }] }), "A horizontal line with a +2.0 microcoulomb charge on the left, a small test charge 0.10 meters to its right, and a second +2.0 microcoulomb charge 0.30 meters farther to the right.", { maxWidth: 500 })] }),
  S(10,
    "A 2.0 μC charge is moved through a potential difference of 50 V. How much work is done on the charge by the electric field?",
    ["1.0 × 10⁻⁶ J", "1.0 × 10⁻⁴ J", "2.5 × 10⁻⁴ J", "2.5 × 10⁷ J"], 1,
    "The work done by the field is W = qΔV = (2.0 × 10⁻⁶ C)(50 V) = 1.0 × 10⁻⁴ J. The value 2.5 × 10⁷ J results from dividing the potential difference by the charge instead of multiplying."),
  M(10,
    "Which of the following is a correct unit for electric field?",
    ["Volts per meter (V/m)", "Volts times meters (V·m)", "Joules per coulomb (J/C)", "Newtons times coulombs (N·C)"],
    "Electric field is force per unit charge, E = F/q, with units of newtons per coulomb (N/C), which are equivalent to volts per meter (V/m) since E = −ΔV/Δx. Joules per coulomb is the unit of potential (volts), not field."),
  S(10,
    "A 5.0 μF capacitor is connected across a 12 V battery. How much charge is stored on each plate of the capacitor?",
    ["2.4 μC", "17 μC", "60 μC", "600 μC"], 2,
    "Q = CV = (5.0 μF)(12 V) = 60 μC. The value 2.4 μC results from dividing C by V."),
  S(10,
    "The capacitance of an air-filled parallel-plate capacitor is C. A dielectric material with a dielectric constant of 4.0 is then inserted to fill the space between the plates. What is the new capacitance?",
    ["C/4", "C", "2C", "4C"], 3,
    "A dielectric multiplies the capacitance by its dielectric constant κ: C_new = κC = 4.0C."),
  M(10,
    "A positive point charge is placed at the center of a neutral, hollow conducting spherical shell. Which statement describes the charges on the shell in electrostatic equilibrium?",
    ["The inner surface has a negative induced charge and the outer surface has an equal positive induced charge.",
     "The inner surface has a positive induced charge and the outer surface has an equal negative induced charge.",
     "Both surfaces remain neutral, because the shell is neutral overall.",
     "The shell becomes positively charged on both surfaces."],
    "The electric field inside the conducting material must be zero. The positive charge at the center therefore attracts an equal negative charge to the inner surface, which cancels the field in the metal. Because the shell is neutral overall, an equal positive charge appears on the outer surface."),

  // ================= Unit 11 (7) =================
  G(11, {
    text: "A 24 V battery with negligible internal resistance is connected to three resistors, as shown.",
    figures: [fig(F.circuitParallelThenSeries({ V: 24, Rp1: 12, Rp2: 6, Rs: 4 }), "A circuit with a 24 volt battery. A 4 ohm resistor is in series with the battery and is followed by a 12 ohm resistor and a 6 ohm resistor connected in parallel with each other.")],
  }, [
    S(11, "What is the total current drawn from the 24 V battery?",
      ["1.0 A", "2.0 A", "3.0 A", "6.0 A"], 2,
      "The 12 Ω and 6 Ω resistors in parallel are equivalent to (12)(6)/(12 + 6) = 4.0 Ω. In series with the 4 Ω resistor, the total resistance is 8.0 Ω, so I = 24/8.0 = 3.0 A."),
    S(11, "How many volts are across the 12 Ω resistor?",
      ["8.0 V", "12 V", "16 V", "24 V"], 1,
      "The 4 Ω resistor carries the full 3.0 A, so the potential difference across it is 12 V. That leaves 24 − 12 = 12 V across the parallel combination, so the 12 Ω resistor has 12 V across it."),
    M(11, "The 6 Ω resistor is removed from the circuit (leaving an open gap). What happens to the power dissipated in the 4 Ω resistor?",
      ["It decreases, because the total resistance increases and the current decreases.",
       "It increases, because the current is no longer divided between two resistors.",
       "It stays the same, because the 4 Ω resistor is not directly affected.",
       "It becomes zero, because the circuit is broken."],
      "Removing the 6 Ω branch leaves only the 12 Ω resistor in series with the 4 Ω resistor, so the total resistance rises from 8.0 Ω to 16 Ω and the current falls from 3.0 A to 1.5 A. The power in the 4 Ω resistor, P = I²R, drops from 36 W to 9 W. The circuit is not broken, because the 12 Ω resistor still provides a path."),
  ]),
  S(11,
    "A battery with an emf of 9.0 V and an internal resistance of 0.50 Ω delivers a current of 2.0 A to an external circuit. What is the potential difference across the battery's terminals?",
    ["1.0 V", "8.0 V", "9.0 V", "10 V"], 1,
    "The terminal voltage is the emf minus the potential drop across the internal resistance: V = ε − Ir = 9.0 − (2.0)(0.50) = 8.0 V."),
  M(11,
    "Household appliances are connected in parallel across the outlets of a home. What is the main advantage of this arrangement?",
    ["Each appliance operates at the full line voltage and can be switched on or off independently of the others.",
     "The total current in the wiring is less than it would be if the appliances were in series.",
     "Each appliance receives a smaller share of the voltage, which keeps the wiring cooler.",
     "All of the appliances always carry the same current."],
    "In parallel, each appliance is connected directly across the supply, so each gets the full voltage and carries its own current; turning one off does not affect the others. In series, the voltage would be divided among the appliances and switching one off would break the circuit for all of them."),
  S(11,
    "A wire of resistance R is stretched uniformly to twice its original length. The volume of the wire stays the same. What is the new resistance of the wire?",
    ["R/2", "R", "2R", "4R"], 3,
    "The resistance is R = ρL/A. Doubling the length with constant volume cuts the cross-sectional area to half. Then R_new = ρ(2L)/(A/2) = 4ρL/A = 4R."),
  S(11,
    "An electric heater rated at 1200 W is operated for 2.5 hours. If electrical energy costs $0.10 per kilowatt-hour, what is the cost?",
    ["$0.030", "$0.30", "$3.00", "$30"], 1,
    "The energy used is (1.2 kW)(2.5 h) = 3.0 kWh. The cost is (3.0 kWh)($0.10/kWh) = $0.30."),

  // ================= Unit 12 (6) =================
  S(12,
    "A proton (m = 1.67 × 10⁻²⁷ kg, q = 1.6 × 10⁻¹⁹ C) moves in a circular path in a uniform magnetic field of 0.50 T. What is the time required for the proton to complete one revolution?",
    ["6.6 × 10⁻⁸ s", "1.3 × 10⁻⁷ s", "2.6 × 10⁻⁷ s", "8.2 × 10⁻⁷ s"], 1,
    "The period of circular motion is T = 2πr/v. With r = mv/(qB), T = 2πm/(qB) = 2π(1.67 × 10⁻²⁷)/((1.6 × 10⁻¹⁹)(0.50)) ≈ 1.3 × 10⁻⁷ s, independent of the proton's speed."),
  M(12,
    "The diagram shows a negative charge moving downward on the page through a region where the magnetic field points into the page. Which way does the magnetic force push the charge at this instant?",
    ["Toward the left side of the page", "Toward the right side of the page", "Toward the top of the page", "Out of the page"],
    "For a positive charge, F = qv × B with v pointing down (−y) and B into the page (−z): (−y) × (−z) = y × z = +x, toward the right. The charge is negative, so the force is reversed and points toward the left side of the page.",
    { figures: [fig(F.magneticField({ dir: "in", vdir: "down", q: "-" }), "A grid of crosses showing a magnetic field directed into the page. A negative charge in the middle moves toward the bottom of the page with a velocity arrow pointing down.", { maxWidth: 420 })] }),
  S(12,
    "A generator coil has 100 turns, each with an area of 0.020 m². The coil rotates at an angular speed of 50 rad/s in a uniform magnetic field of 0.50 T. What is the maximum emf the generator produces?",
    ["5.0 V", "25 V", "50 V", "500 V"], 2,
    "The maximum emf is ε_max = NBAω = (100)(0.50)(0.020)(50) = 50 V."),
  M(12,
    "In a mass spectrometer, two ions with the same charge and speed enter a uniform magnetic field perpendicular to their velocities. The mass of ion 2 is greater than the mass of ion 1. How do the radii of their circular paths compare?",
    ["Ion 2 moves in a circle of larger radius than ion 1.",
     "Ion 2 moves in a circle of smaller radius than ion 1.",
     "The two ions move in circles of the same radius.",
     "Ion 2 moves in a straight line, because it is heavier."],
    "The radius of the path is r = mv/(qB). For the same charge, speed, and field, the radius is proportional to the mass, so the heavier ion follows a circle with a larger radius."),
  S(12,
    "A circular loop of radius 0.10 m is perpendicular to a magnetic field. The field increases uniformly from 0 to 0.20 T in 0.050 s. What is the magnitude of the average emf induced in the loop?",
    ["0.063 V", "0.13 V", "0.63 V", "1.3 V"], 1,
    "The area of the loop is πr² = π(0.10)² = 0.0314 m². The magnitude of the average emf is |ε| = AΔB/Δt = (0.0314)(0.20)/(0.050) ≈ 0.126 V ≈ 0.13 V."),
  M(12,
    "A charged particle moves in a region of uniform magnetic field with its velocity perpendicular to the field. Which statement about the particle's kinetic energy is correct?",
    ["The kinetic energy stays constant, because the magnetic force is always perpendicular to the velocity.",
     "The kinetic energy increases, because the magnetic force accelerates the particle.",
     "The kinetic energy decreases, because the magnetic force opposes the particle's motion.",
     "The kinetic energy changes periodically, because the particle moves in a circle."],
    "The magnetic force on a moving charge is always perpendicular to its velocity, so it does no work on the particle (W = Fd cos 90° = 0). The force changes only the direction of the velocity, not its magnitude, so the speed and kinetic energy are constant."),

  // ================= Unit 13 (6) =================
  S(13,
    "Light in glass (n = 1.5) strikes a boundary with water (n = 1.33) at an angle of incidence of 40° from the normal. What is the angle of refraction in the water?",
    ["26°", "40°", "46°", "65°"], 2,
    "Snell's law gives (1.5)(sin 40°) = (1.33) sin θ₂, so sin θ₂ = (1.5)(0.643)/1.33 = 0.725 and θ₂ ≈ 46°. The light bends away from the normal because it enters the medium with the lower index of refraction."),
  G(13, {
    text: "An object is placed 24 cm from a thin converging lens that has a focal length of 12 cm, as shown. (The vertical scale of the diagram is exaggerated.)",
    figures: [fig(F.lensRays({ f: 12, dO: 24, h: 3, scale: 5, vscale: 12 }), "A ray diagram for a converging lens with the object at twice the focal length from the lens. Two rays from the arrow tip, one parallel to the axis and one through the lens center, meet at twice the focal length on the other side, forming an inverted image the same size as the object.")],
  }, [
    S(13, "What is the image distance?",
      ["12 cm", "24 cm", "36 cm", "48 cm"], 1,
      "1/d_i = 1/f − 1/d_o = 1/12 − 1/24 = 1/24, so d_i = 24 cm. When the object is at twice the focal length, the image is also at twice the focal length."),
    M(13, "How can the image formed by this lens be described?",
      ["It is real, inverted, and the same size as the object.",
       "It is real, inverted, and larger than the object.",
       "It is virtual, upright, and the same size as the object.",
       "It is real, upright, and the same size as the object."],
      "The magnification is m = −d_i/d_o = −24/24 = −1. The negative sign means inverted, and the magnitude of 1 means the same size. The image distance is positive, so the image is real."),
  ]),
  S(13,
    "A diverging lens has a focal length of −20 cm. An object is placed 20 cm from the lens. At what position is the image formed?",
    ["20 cm in front of the lens", "10 cm in front of the lens", "10 cm behind the lens", "20 cm behind the lens"], 1,
    "The lens equation gives 1/d_i = 1/f − 1/d_o = −1/20 − 1/20 = −1/10, so d_i = −10 cm. The negative sign means the image is virtual and on the same side of the lens as the object, 10 cm from the lens."),
  M(13,
    "A swimmer looks straight down at a coin on the bottom of a pool. How does the apparent depth of the coin compare with its actual depth?",
    ["The coin appears shallower than it really is, because the light bends away from the normal as it leaves the water.",
     "The coin appears deeper than it really is, because the light bends toward the normal as it leaves the water.",
     "The coin appears at its actual depth, because the light travels straight to the eye.",
     "The coin appears shallower, because the water magnifies the coin."],
    "Light from the coin refracts as it passes from water into air. Since air has the lower index of refraction, the rays bend away from the normal, and the eye traces them back to a point above the actual location. The coin therefore appears to be at a shallower depth."),
  M(13,
    "White light passes through a glass prism and spreads into a spectrum of colors. Which statement explains why violet light is bent more than red light?",
    ["The index of refraction of glass is greater for violet light than for red light.", "Violet light has a lower frequency than red light, so it is slowed more in glass.", "Violet light travels faster in glass than red light does, so it is bent more.", "The prism adds extra energy to the violet light as the light passes through it."],
    "The index of refraction of glass depends on wavelength (dispersion); it is larger for the shorter wavelengths of violet light. A larger index means the light slows more in glass and bends more at the surface. Violet light has a higher frequency, not a lower one, and travels more slowly in glass than red light."),

  // ================= Unit 14 (5) =================
  S(14,
    "A string has a tension of 100 N and a linear mass density of 0.010 kg/m. What is the speed of transverse waves on the string?",
    ["10 m/s", "32 m/s", "100 m/s", "1000 m/s"], 2,
    "The wave speed on a string is v = √(T/μ) = √(100/0.010) = √(10,000) = 100 m/s."),
  S(14,
    "The intensity of sound from a small speaker is 8.0 × 10⁻⁴ W/m² at a distance of 2.0 m from the speaker. Assuming the sound spreads out equally in all directions, what is the intensity at a distance of 4.0 m?",
    ["1.0 × 10⁻⁴ W/m²", "2.0 × 10⁻⁴ W/m²", "4.0 × 10⁻⁴ W/m²", "1.6 × 10⁻³ W/m²"], 1,
    "For a point source, the intensity varies as 1/r². Doubling the distance reduces the intensity by a factor of 4: (8.0 × 10⁻⁴)/4 = 2.0 × 10⁻⁴ W/m². 4.0 × 10⁻⁴ W/m² results from assuming an inverse (rather than inverse-square) relationship."),
  G(14, {
    text: "The graph shows the displacement of one point on a rope as a function of time as a transverse wave passes by. The wavelength of the wave is 1.0 m.",
    figures: [fig(waveTime, "A sinusoidal graph of displacement in millimeters against time in seconds. The amplitude is 5 millimeters and the wave completes three full cycles in 1.2 seconds, with a period of 0.4 seconds.")],
  }, [
    S(14, "What is the frequency of the wave?",
      ["0.40 Hz", "2.5 Hz", "5.0 Hz", "10 Hz"], 1,
      "The graph shows one full cycle every 0.40 s, so the period is T = 0.40 s and the frequency is f = 1/T = 2.5 Hz. (0.40 is the period in seconds.)"),
    S(14, "What is the speed of the wave?",
      ["0.40 m/s", "1.0 m/s", "2.5 m/s", "5.0 m/s"], 2,
      "v = fλ = (2.5 Hz)(1.0 m) = 2.5 m/s."),
  ]),
  M(14,
    "Which statement about the standing waves in an air column in a pipe that is open at both ends is correct?",
    ["There are displacement antinodes at both ends of the pipe.",
     "There is a displacement node at each end of the pipe.",
     "There is a displacement node at one end and an antinode at the other end.",
     "Only the fundamental can exist in the pipe."],
    "At an open end the air is free to move, so there is a displacement antinode there. A pipe open at both ends has antinodes at both ends, and its resonant frequencies are f = nv/(2L) for n = 1, 2, 3, … A pipe closed at one end has a node at the closed end."),

  // ================= Unit 15 (5) =================
  S(15,
    "Light with a photon energy of 3.5 eV strikes a metal surface that has a work function of 2.0 eV. What is the maximum kinetic energy of the ejected electrons?",
    ["0.57 eV", "1.5 eV", "2.0 eV", "5.5 eV"], 1,
    "By the photoelectric equation, K_max = hf − φ = 3.5 − 2.0 = 1.5 eV. 5.5 eV results from adding the work function instead of subtracting it."),
  G(15, {
    text: "In a photoelectric experiment, light of several different frequencies is incident on a metal surface. For each frequency, the stopping potential (the potential difference that just stops the most energetic ejected electrons) is measured. The data are shown in the table. (e = 1.6 × 10⁻¹⁹ C)",
    figures: [table(["Frequency (10¹⁴ Hz)", "Stopping potential (V)"], [["6.0", "0.60"], ["7.0", "1.00"], ["8.0", "1.40"], ["9.0", "1.80"]])],
  }, [
    S(15, "What is the threshold frequency of the metal?",
      ["3.0 × 10¹⁴ Hz", "4.5 × 10¹⁴ Hz", "6.0 × 10¹⁴ Hz", "7.5 × 10¹⁴ Hz"], 1,
      "The stopping potential rises by 0.40 V for each 1.0 × 10¹⁴ Hz, so V = 0.40(f − f₀) with f in units of 10¹⁴ Hz. At f = 6.0, V = 0.60 V, which gives f₀ = 6.0 − 0.60/0.40 = 4.5 × 10¹⁴ Hz, the frequency at which the stopping potential would be zero."),
    S(15, "Use the data to estimate the value of Planck's constant.",
      ["6.4 × 10⁻³⁶ J·s", "6.4 × 10⁻³⁴ J·s", "6.4 × 10⁻³² J·s", "2.5 × 10⁻²⁰ J·s"], 1,
      "The photoelectric equation gives eV = hf − φ, so a graph of V against f has a slope of h/e. The slope is (0.40 V)/(1.0 × 10¹⁴ Hz) = 4.0 × 10⁻¹⁵ V·s, so h = e × slope = (1.6 × 10⁻¹⁹)(4.0 × 10⁻¹⁵) = 6.4 × 10⁻³⁴ J·s."),
  ]),
  S(15,
    "What is the magnitude of the momentum of a photon of light with a wavelength of 500 nm? (h = 6.63 × 10⁻³⁴ J·s)",
    ["1.3 × 10⁻²⁷ kg·m/s", "1.3 × 10⁻²⁵ kg·m/s", "4.0 × 10⁻²⁰ kg·m/s", "3.3 × 10⁻⁴⁰ kg·m/s"], 0,
    "The momentum of a photon is p = h/λ = (6.63 × 10⁻³⁴)/(500 × 10⁻⁹) = 1.3 × 10⁻²⁷ kg·m/s."),
  M(15,
    "In nuclear fusion, two light nuclei combine to form a heavier nucleus and energy is released. Which statement best explains why energy is released?",
    ["The binding energy per nucleon of the product nucleus is greater than that of the original nuclei, so the total mass decreases.",
     "The product nucleus has more mass than the original nuclei, and the extra mass is converted to energy.",
     "The protons in the nuclei attract each other by the electric force, releasing energy as they combine.",
     "The neutrons in the nuclei are converted into protons, which releases energy."],
    "For light nuclei, fusion produces a nucleus with a larger binding energy per nucleon. The product is more tightly bound, so its total mass is less than the combined mass of the original nuclei. The mass difference is released as energy, E = Δmc²."),
];
