import { S, M, G, fig } from "./pool.mjs";
import * as F from "./p2figs.mjs";

export const config = { hub: "physics2", prefix: "p2e", N: 1, file: "exam1.js", title: "AP Physics 2 — Exam 1", seed: 101, units: { 9: 7, 10: 7, 11: 7, 12: 5, 13: 6, 14: 6, 15: 4 }, note: "Uses g = 10 m/s²." };

export default [
  // ================= Unit 9: Thermodynamics (7) =================
  S(9,
    "A rigid sealed container holds an ideal gas at 27 °C and a pressure of 1.0 × 10⁵ Pa. The gas is heated to 127 °C. What is the final pressure of the gas?",
    ["1.0 × 10⁵ Pa", "1.3 × 10⁵ Pa", "2.0 × 10⁵ Pa", "4.7 × 10⁵ Pa"], 1,
    "At constant volume and amount of gas, P/T is constant when T is the absolute temperature. The temperatures are 300 K and 400 K, so P = (1.0 × 10⁵)(400/300) = 1.3 × 10⁵ Pa. 4.7 × 10⁵ Pa results from using the Celsius temperatures (127/27) instead of kelvins."),
  S(9,
    "During a process, an ideal gas absorbs 500 J of heat while doing 200 J of work on its surroundings. What is the change in the internal energy of the gas?",
    ["−700 J", "−300 J", "+300 J", "+700 J"], 2,
    "The first law of thermodynamics is ΔU = Q − W_by, where Q is the heat added to the gas and W_by is the work done by the gas. Here ΔU = 500 − 200 = +300 J. +700 J would result from adding the work done by the gas instead of subtracting it."),
  G(9, {
    text: "An ideal gas undergoes the cycle A → B → C → A shown in the PV diagram. Process A → B occurs at constant pressure, process B → C occurs at constant volume, and process C → A is a straight line on the diagram.",
    figures: [fig(F.pvDiagram({ states: [{ label: "A", V: 2, P: 100, dx: -16 }, { label: "B", V: 6, P: 100 }, { label: "C", V: 6, P: 40 }], xMax: 8, yMax: 120 }),
      "A PV diagram of a triangular cycle. State A is at 2 liters and 100 kilopascals, B at 6 liters and 100 kilopascals, and C at 6 liters and 40 kilopascals. The cycle runs A to B to C and back to A, clockwise.")],
  }, [
    S(9, "How much work is done by the gas during process A → B?",
      ["200 J", "400 J", "600 J", "800 J"], 1,
      "At constant pressure the work done by the gas is W = PΔV = (100 × 10³ Pa)(6 − 2)(10⁻³ m³) = 400 J (the area under the A → B line). 600 J is P·V at state B alone, which does not account for the gas starting at 2 L."),
    M(9, "Which of the following correctly describes process B → C?",
      ["The gas releases heat to its surroundings, and its internal energy decreases.",
       "The gas absorbs heat from its surroundings, and its internal energy increases.",
       "The gas does positive work on its surroundings, and its temperature stays constant.",
       "The gas releases heat to its surroundings, and its internal energy stays constant."],
      "The volume is constant, so no work is done (W = 0). The pressure drops, and since P/T is constant at fixed volume, the temperature also drops, so the internal energy decreases. With W = 0, the first law gives ΔU = Q, so Q is negative: the gas releases heat."),
    S(9, "What is the net work done by the gas during one complete cycle A → B → C → A?",
      ["60 J", "120 J", "240 J", "400 J"], 1,
      "The net work equals the area enclosed by the cycle, a triangle with base ΔV = 4.0 × 10⁻³ m³ and height ΔP = 60 × 10³ Pa: ½(4.0 × 10⁻³)(60 × 10³) = 120 J. The cycle runs clockwise, so the net work done by the gas is positive. 240 J would be the area of the full rectangle."),
  ]),
  S(9,
    "How much thermal energy must be added to 0.50 kg of liquid water to raise its temperature by 20 °C? (The specific heat capacity of water is 4200 J/(kg·°C).)",
    ["2.1 × 10⁴ J", "4.2 × 10⁴ J", "8.4 × 10⁴ J", "4.2 × 10⁵ J"], 1,
    "Q = mcΔT = (0.50)(4200)(20) = 4.2 × 10⁴ J."),
  M(9,
    "A cup of hot coffee sits in a cool room and gradually cools until it reaches room temperature. Which statement about the entropy change in this process is correct?",
    ["The entropy of the coffee decreases, but the total entropy of the coffee and the room increases.",
     "The total entropy of the coffee and the room decreases, because the coffee loses thermal energy.",
     "The total entropy of the coffee and the room stays the same, because energy is conserved.",
     "The entropy of the coffee increases, because heat flows out of the coffee."],
    "When energy flows out of the coffee as heat, the coffee's entropy decreases (ΔS = Q/T with Q negative). The room gains the same amount of energy at a lower temperature, so its entropy increases by more than the coffee's entropy decreases. The second law requires the total entropy of the coffee and the room to increase in a spontaneous process. Energy is conserved, but entropy is not."),

  // ================= Unit 10: Electric Force, Field, and Potential (7) =================
  S(10,
    "Two small spheres carrying charges of +2.0 μC and +3.0 μC are 0.30 m apart. What is the magnitude of the electric force that each sphere exerts on the other?",
    ["0.18 N", "0.60 N", "1.8 N", "6.0 N"], 1,
    "By Coulomb's law, F = kq₁q₂/r² = (9.0 × 10⁹)(2.0 × 10⁻⁶)(3.0 × 10⁻⁶)/(0.30)² = 0.60 N. The forces on the two spheres have equal magnitudes (Newton's third law)."),
  S(10,
    "What is the magnitude of the electric field at a point 0.50 m from an isolated point charge of +5.0 nC?",
    ["90 N/C", "180 N/C", "360 N/C", "900 N/C"], 1,
    "E = kq/r² = (9.0 × 10⁹)(5.0 × 10⁻⁹)/(0.50)² = 45/0.25 = 180 N/C. 90 N/C results from dividing by r instead of r²."),
  S(10,
    "What is the electric potential energy of a system of two point charges, +4.0 μC and −2.0 μC, that are 0.60 m apart?",
    ["−0.12 J", "−0.072 J", "+0.072 J", "+0.12 J"], 0,
    "U = kq₁q₂/r = (9.0 × 10⁹)(4.0 × 10⁻⁶)(−2.0 × 10⁻⁶)/(0.60) = −0.12 J. The energy is negative because the charges have opposite signs (they attract), so work would have to be done to separate them."),
  G(10, {
    text: "A charge +Q and a charge −Q, each of magnitude 2.0 μC, are fixed 0.40 m apart. Point P is midway between the two charges.",
    figures: [fig(F.chargeLine({ items: [{ x: 110, q: "+", label: "+Q" }, { x: 240, name: "P" }, { x: 370, q: "-", label: "−Q" }], spans: [{ x1: 110, x2: 370, label: "0.40 m" }] }),
      "A horizontal line with a positive charge on the left, a point P in the middle, and a negative charge on the right. The charges are 0.40 meters apart.")],
  }, [
    S(10, "What is the magnitude of the net electric field at point P?",
      ["0 N/C", "4.5 × 10⁵ N/C", "9.0 × 10⁵ N/C", "1.8 × 10⁶ N/C"], 2,
      "P is 0.20 m from each charge. Each charge produces a field of magnitude kQ/r² = (9.0 × 10⁹)(2.0 × 10⁻⁶)/(0.20)² = 4.5 × 10⁵ N/C. Both fields at P point to the right (away from +Q and toward −Q), so they add: 9.0 × 10⁵ N/C. A net field of zero would occur only if the fields pointed in opposite directions."),
    M(10, "What is the electric potential at point P? (Take V = 0 infinitely far from the charges.)",
      ["Zero, because the potentials due to the two equal and opposite charges cancel at P.",
       "Nonzero and negative, because the net electric field at P points toward the negative charge.",
       "Nonzero and positive, because the electric field at P is not zero.",
       "Nonzero and positive, because the positive charge is the source of the field."],
      "Potential is a scalar, and the contributions add algebraically: V = kQ/r + k(−Q)/r = 0 at the midpoint. A nonzero field does not imply a nonzero potential, and the direction of the field does not determine the sign of the potential at that point."),
  ]),
  S(10,
    "Two parallel metal plates are separated by 2.0 mm and connected across a 100 V battery, as shown. What is the magnitude of the electric field between the plates?",
    ["5.0 × 10³ V/m", "2.0 × 10⁴ V/m", "5.0 × 10⁴ V/m", "2.0 × 10⁵ V/m"], 2,
    "For a uniform field between parallel plates, E = V/d = 100/(2.0 × 10⁻³) = 5.0 × 10⁴ V/m. Using the distance in millimeters without converting to meters would give an answer 1000 times too small.",
    { figures: [fig(F.plateCapacitor({ V: "100 V", d: "2.0 mm" }), "Two horizontal parallel plates, the upper one positive and the lower one negative, separated by 2.0 millimeters. Arrows between them point from the upper plate to the lower plate. A 100 volt potential difference is applied.", { maxWidth: 360 })] }),
  M(10,
    "A neutral metal sphere on an insulating stand is brought near, but does not touch, a positively charged rod. Which statement describes the interaction between the rod and the sphere?",
    ["The sphere is attracted to the rod, because the side of the sphere nearer the rod becomes negatively charged.",
     "The sphere is repelled by the rod, because the sphere becomes positively charged.",
     "There is no force between them, because the sphere is neutral overall.",
     "The sphere is attracted to the rod, because positive charge flows from the rod onto the sphere."],
    "The rod's positive charge pulls mobile electrons in the metal toward the near side of the sphere, leaving the far side positive. The near (negative) charges are closer to the rod, so the attraction is stronger than the repulsion on the far side, and the net force is attractive. No charge is transferred because they do not touch."),

  // ================= Unit 11: Electric Circuits (7) =================
  G(11, {
    text: "A 12 V battery with negligible internal resistance is connected to three resistors, as shown.",
    figures: [fig(F.circuitSeriesParallel({ V: 12, R1: 4, R2: 6, R3: 3 }),
      "A circuit with a 12 volt battery. A 4 ohm resistor R1 is in series with the battery, followed by a 6 ohm resistor R2 and a 3 ohm resistor R3 connected in parallel with each other.")],
  }, [
    S(11, "What is the current supplied by the battery?",
      ["0.50 A", "1.0 A", "2.0 A", "3.0 A"], 2,
      "The 6 Ω and 3 Ω resistors in parallel have an equivalent resistance of (6)(3)/(6 + 3) = 2.0 Ω. In series with the 4 Ω resistor, the total resistance is 6.0 Ω, so I = V/R = 12/6.0 = 2.0 A."),
    S(11, "What is the power dissipated in the 4 Ω resistor?",
      ["8 W", "16 W", "36 W", "48 W"], 1,
      "The full battery current of 2.0 A flows through the 4 Ω resistor, so P = I²R = (2.0)²(4) = 16 W. 36 W would come from wrongly applying the whole 12 V to the 4 Ω resistor (V²/R)."),
    S(11, "What is the current in the 6 Ω resistor?",
      ["0.33 A", "0.67 A", "1.0 A", "1.3 A"], 1,
      "The 4 Ω resistor has a potential difference of (2.0)(4) = 8.0 V across it, leaving 12 − 8.0 = 4.0 V across the parallel pair. The current in the 6 Ω resistor is I = 4.0/6 = 0.67 A. (The 3 Ω resistor carries 1.3 A; the two add to the 2.0 A from the battery.)"),
  ]),
  S(11,
    "A wire has resistance R. A second wire made of the same material has twice the length and twice the diameter of the first wire. What is the resistance of the second wire?",
    ["R/4", "R/2", "R", "2R"], 1,
    "The resistance is R = ρL/A. Doubling the length doubles R, but doubling the diameter increases the cross-sectional area by a factor of 2² = 4, which divides R by 4. Combined: 2/4 = 1/2, so the resistance is R/2."),
  M(11,
    "Three identical bulbs are connected in parallel across a battery that has negligible internal resistance. If one of the bulbs is removed from the circuit, what happens to the brightness of the other two bulbs?",
    ["It does not change, because each remaining bulb still has the full battery voltage across it.",
     "Both become dimmer, because the current is now shared among fewer bulbs.",
     "Both become brighter, because the battery's current is now divided between fewer bulbs.",
     "Both go out, because removing a bulb breaks the circuit."],
    "Each branch of a parallel circuit is connected directly across the battery, so each bulb has the same potential difference as before and carries the same current. Removing one bulb changes only the total current drawn from the battery. The other bulbs' brightness does not change."),
  M(11,
    "A student wants to measure both the current through a resistor and the potential difference across it. How should the meters be connected?",
    ["The ammeter in series with the resistor and the voltmeter in parallel with the resistor",
     "The ammeter in parallel with the resistor and the voltmeter in series with the resistor",
     "Both the ammeter and the voltmeter in series with the resistor",
     "Both the ammeter and the voltmeter in parallel with the resistor"],
    "An ammeter measures the current passing through it, so it must be in series with the resistor and have very low resistance. A voltmeter measures the potential difference between two points, so it is connected in parallel across the resistor and has very high resistance so it draws almost no current."),
  S(11,
    "A battery with an emf of 12 V and an internal resistance of 1.0 Ω is connected to a 5.0 Ω resistor, as shown. What is the potential difference across the 5.0 Ω resistor?",
    ["2.0 V", "10 V", "11 V", "12 V"], 1,
    "The internal and external resistors are in series, so I = ε/(r + R) = 12/6.0 = 2.0 A. The potential difference across the external resistor is V = IR = (2.0)(5.0) = 10 V. 12 V would be the potential difference only if the battery had no internal resistance.",
    { figures: [fig(F.circuitInternal({ emf: 12, r: 1.0, R: 5.0 }), "A single loop circuit. A 12 volt battery with 1.0 ohm of internal resistance, drawn inside a dashed box labeled real battery, is connected to an external 5.0 ohm resistor.", { maxWidth: 400 })] }),

  // ================= Unit 12: Magnetism and Electromagnetism (5) =================
  S(12,
    "A proton moves at 2.0 × 10⁶ m/s perpendicular to a uniform magnetic field of 0.50 T. What is the magnitude of the magnetic force on the proton?",
    ["1.6 × 10⁻¹⁴ N", "1.6 × 10⁻¹³ N", "3.2 × 10⁻¹³ N", "1.6 × 10⁻¹² N"], 1,
    "For a velocity perpendicular to the field, F = qvB = (1.6 × 10⁻¹⁹)(2.0 × 10⁶)(0.50) = 1.6 × 10⁻¹³ N."),
  M(12,
    "A positive charge moves to the right in a uniform magnetic field directed into the page, as shown. What is the direction of the magnetic force on the charge at the instant shown?",
    ["Toward the top of the page", "Toward the bottom of the page", "To the right, in the direction of the velocity", "Out of the page"],
    "Using the right-hand rule for F = qv × B: point the fingers along v (right), curl them toward B (into the page), and the thumb points up. For a positive charge the force is toward the top of the page. The magnetic force is always perpendicular to the velocity, so it can never point along the velocity, and it is perpendicular to B as well.",
    { figures: [fig(F.magneticField({ dir: "in", vdir: "right", q: "+" }), "A grid of crosses showing a magnetic field directed into the page. A positive charge in the middle moves to the right with a velocity arrow pointing right.", { maxWidth: 420 })] }),
  S(12,
    "A flat conducting loop with an area of 0.20 m² is perpendicular to a uniform magnetic field of 0.50 T. The field decreases uniformly to zero in 0.10 s. What is the magnitude of the average emf induced in the loop?",
    ["0.10 V", "0.50 V", "1.0 V", "10 V"], 2,
    "The magnetic flux changes from BA = (0.50)(0.20) = 0.10 T·m² to zero in 0.10 s. By Faraday's law, |ε| = ΔΦ/Δt = 0.10/0.10 = 1.0 V."),
  M(12,
    "The north pole of a bar magnet is pushed toward the face of a conducting loop. Which statement correctly describes the current induced in the loop while the magnet moves?",
    ["The current creates a magnetic field that opposes the increase in flux, so the face of the loop nearest the magnet acts like a north pole.",
     "The current creates a magnetic field that opposes the increase in flux, so the face of the loop nearest the magnet acts like a south pole.",
     "No current is induced, because the magnet does not touch the loop.",
     "A current is induced only after the magnet stops moving."],
    "By Lenz's law, the induced current opposes the change in flux that causes it. The flux through the loop from the approaching north pole is increasing, so the loop's induced field points back toward the magnet. A north face next to the approaching north pole produces repulsion, which opposes the motion. A current is induced only while the flux is changing."),
  S(12,
    "A straight wire 0.40 m long carries a current of 5.0 A perpendicular to a uniform magnetic field of 0.30 T. What is the magnitude of the magnetic force on the wire?",
    ["0.15 N", "0.60 N", "1.5 N", "6.0 N"], 1,
    "F = BIL = (0.30)(5.0)(0.40) = 0.60 N."),

  // ================= Unit 13: Geometric Optics (6) =================
  S(13,
    "A ray of light in air strikes a flat glass surface (n = 1.5) at an angle of incidence of 30° measured from the normal. What is the angle of refraction in the glass?",
    ["15°", "19.5°", "30°", "48.6°"], 1,
    "Snell's law gives n₁ sin θ₁ = n₂ sin θ₂: (1.0)(sin 30°) = (1.5) sin θ₂, so sin θ₂ = 0.333 and θ₂ ≈ 19.5°. The ray bends toward the normal because it enters the higher-index glass. 48.6° results from putting the indices in the wrong places."),
  G(13, {
    text: "An object is placed 30 cm in front of a thin converging lens that has a focal length of 10 cm, as shown. (The vertical scale of the diagram is exaggerated.)",
    figures: [fig(F.lensRays({ f: 10, dO: 30, h: 3 }), "A ray diagram for a converging lens. An upright arrow, the object, stands to the left of the lens, beyond twice the focal length. Two rays leave the arrow tip: one parallel to the axis that refracts through the far focal point, and one through the center of the lens. They meet to the right of the lens beyond the focal point, forming a small inverted arrow below the axis.")],
  }, [
    S(13, "What is the distance from the lens to the image?",
      ["7.5 cm", "15 cm", "20 cm", "30 cm"], 1,
      "The thin-lens equation, 1/f = 1/d_o + 1/d_i, gives 1/d_i = 1/10 − 1/30 = 2/30, so d_i = 15 cm."),
    S(13, "What is the magnification of the image?",
      ["−2.0", "−0.50", "+0.50", "+2.0"], 1,
      "The magnification is m = −d_i/d_o = −15/30 = −0.50. The negative sign means the image is inverted, and its magnitude of 0.50 means the image is half as tall as the object."),
    M(13, "Which statement correctly describes the image?",
      ["It is real, inverted, and smaller than the object.",
       "It is virtual, upright, and smaller than the object.",
       "It is real, upright, and larger than the object.",
       "It is virtual, inverted, and larger than the object."],
      "The object is beyond twice the focal length, and the image distance is positive (on the side of the lens opposite the object), so the image is real. Real images formed by a single converging lens are inverted, and since the magnification magnitude is 0.50, the image is smaller."),
  ]),
  M(13,
    "An object is placed 5 cm in front of a concave spherical mirror that has a focal length of 10 cm. Which statement describes the image formed by the mirror?",
    ["It is virtual, upright, and larger than the object.",
     "It is real, inverted, and larger than the object.",
     "It is real, inverted, and smaller than the object.",
     "It is virtual, upright, and smaller than the object."],
    "The object is inside the focal length. The mirror equation gives 1/d_i = 1/10 − 1/5 = −1/10, so d_i = −10 cm. The negative image distance means the image is virtual (behind the mirror), and m = −d_i/d_o = +2, so the image is upright and twice as large — the way a makeup mirror works."),
  M(13,
    "Light travels from air into water. Which statement is correct about the light's frequency and wavelength in the water?",
    ["Its frequency is unchanged and its wavelength is shorter.",
     "Its frequency is unchanged and its wavelength is longer.",
     "Its frequency decreases and its wavelength is unchanged.",
     "Its frequency increases and its wavelength is shorter."],
    "The frequency of a wave is set by its source and does not change when the wave crosses a boundary. The speed of light is lower in water (v = c/n), and since v = fλ with f fixed, the wavelength is shorter."),

  // ================= Unit 14: Waves, Sound, and Physical Optics (6) =================
  G(14, {
    text: "The graph shows the shape of a transverse wave traveling along a string at one instant. The wave speed is 12 cm/s.",
    figures: [fig(F.waveSnapshot({ A: 2, lam: 6, xMax: 12, xStep: 3 }), "A sinusoidal wave plotted as displacement in centimeters against position in centimeters. The wave has amplitude 2 centimeters and completes two full cycles between 0 and 12 centimeters.")],
  }, [
    S(14, "What is the wavelength of the wave?",
      ["2 cm", "3 cm", "6 cm", "12 cm"], 2,
      "One full wavelength is the distance over which the wave pattern repeats. The graph shows two complete cycles between x = 0 and x = 12 cm, so λ = 6 cm. (3 cm is half a wavelength, and 2 cm is the amplitude.)"),
    S(14, "What is the frequency of the wave?",
      ["0.50 Hz", "2.0 Hz", "6.0 Hz", "72 Hz"], 1,
      "From v = fλ, the frequency is f = v/λ = (12 cm/s)/(6 cm) = 2.0 Hz."),
  ]),
  S(14,
    "A string of length 1.2 m is fixed at both ends and vibrates in the standing wave pattern shown, which has three loops. The wave speed on the string is 120 m/s. What is the frequency of the vibration?",
    ["50 Hz", "100 Hz", "150 Hz", "300 Hz"], 2,
    "Three loops means three half-wavelengths fit on the string: 3(λ/2) = 1.2 m, so λ = 0.80 m. The frequency is f = v/λ = 120/0.80 = 150 Hz. (The fundamental, with one loop, would have f = 50 Hz.)",
    { figures: [fig(F.standingWave({ n: 3, L: "L = 1.2 m" }), "A standing wave on a string fixed at both ends, showing three loops with nodes at both ends and two interior nodes. The string length is 1.2 meters.", { maxWidth: 440 })] }),
  S(14,
    "In a double-slit experiment, light of wavelength 600 nm passes through two slits that are 0.20 mm apart. The screen is 2.0 m from the slits. What is the distance between adjacent bright fringes on the screen?",
    ["0.60 mm", "3.0 mm", "6.0 mm", "12 mm"], 2,
    "For small angles, the fringe spacing is Δy = λL/d = (600 × 10⁻⁹)(2.0)/(0.20 × 10⁻³) = 6.0 × 10⁻³ m = 6.0 mm."),
  S(14,
    "The intensity of a sound increases by a factor of 100. By how many decibels does the sound intensity level increase?",
    ["2 dB", "10 dB", "20 dB", "100 dB"], 2,
    "The sound intensity level is β = 10 log(I/I₀) dB. A factor of 100 in intensity adds 10 log(100) = 10(2) = 20 dB."),
  M(14,
    "Two identical speakers emit sound waves of the same wavelength in phase. A listener stands at a point where the path lengths to the two speakers differ by one-half of a wavelength. What does the listener hear at that point?",
    ["A minimum in loudness, because the waves interfere destructively",
     "A maximum in loudness, because the waves interfere constructively",
     "Sound of half the original frequency, because of the path difference",
     "Sound that is as loud as one speaker alone, because the waves do not interact"],
    "A path difference of half a wavelength puts the two waves a half-cycle out of phase when they arrive, so crests of one coincide with troughs of the other and they cancel. This is destructive interference, which gives a minimum in loudness. The frequency of the sound is not changed by interference."),

  // ================= Unit 15: Modern Physics (4) =================
  S(15,
    "What is the energy of a photon of visible light that has a wavelength of 500 nm? (Use hc = 1240 eV·nm.)",
    ["1.2 eV", "2.5 eV", "5.0 eV", "12 eV"], 1,
    "E = hc/λ = (1240 eV·nm)/(500 nm) = 2.48 eV ≈ 2.5 eV."),
  G(15, {
    text: "The figure shows the lowest energy levels of a hypothetical atom. Use hc = 1240 eV·nm.",
    figures: [fig(F.energyLevels({ levels: [{ n: 1, E: -8.0 }, { n: 2, E: -3.0 }, { n: 3, E: -1.5 }, { n: 4, E: -0.5 }] }), "An energy level diagram with horizontal lines for n equals 1 at minus 8.0 electron volts, n equals 2 at minus 3.0, n equals 3 at minus 1.5, and n equals 4 at minus 0.5, with a dashed line at 0 for the ionization energy.", { maxWidth: 420 })],
  }, [
    S(15, "What is the wavelength of the photon emitted when an electron makes a transition from n = 3 to n = 1?",
      ["95 nm", "190 nm", "380 nm", "1900 nm"], 1,
      "The photon carries the energy difference: ΔE = −1.5 − (−8.0) = 6.5 eV. Then λ = hc/ΔE = 1240/6.5 ≈ 190 nm."),
    M(15, "Which transition emits the photon with the longest wavelength?",
      ["n = 4 to n = 3", "n = 2 to n = 1", "n = 3 to n = 1", "n = 4 to n = 1"],
      "The wavelength is inversely proportional to the photon energy, so the longest wavelength comes from the smallest energy difference. The n = 4 to n = 3 transition releases only 1.0 eV, less than the others (5.0 eV, 6.5 eV, and 7.5 eV)."),
  ]),
  S(15,
    "A radioactive sample initially contains 80 g of an isotope with a half-life of 3.0 days. How much of the isotope remains after 9.0 days?",
    ["5.0 g", "10 g", "20 g", "40 g"], 1,
    "Nine days is three half-lives, so the sample is halved three times: 80 → 40 → 20 → 10 g."),
];
