import { S, M, G, fig } from "./pool.mjs";
import * as F from "./p2figs.mjs";

export const config = { hub: "physics2", prefix: "p2e", N: 2, file: "exam2.js", title: "AP Physics 2 — Exam 2", seed: 202, units: { 9: 7, 10: 7, 11: 6, 12: 6, 13: 5, 14: 6, 15: 5 }, note: "Uses g = 10 m/s²." };

export default [
  // ================= Unit 9 (7) =================
  S(9,
    "How many moles of an ideal gas are in a 5.0 L container at a pressure of 4.0 × 10⁵ Pa and a temperature of 300 K? (R = 8.31 J/(mol·K))",
    ["0.20 mol", "0.40 mol", "0.60 mol", "0.80 mol"], 3,
    "Convert the volume to cubic meters: 5.0 L = 5.0 × 10⁻³ m³. Then n = PV/(RT) = (4.0 × 10⁵)(5.0 × 10⁻³)/((8.31)(300)) = 2000/2493 ≈ 0.80 mol. Using 2.0 × 10⁵ Pa would give 0.40 mol."),
  G(9, {
    text: "An ideal gas is taken around the rectangular cycle A → B → C → D → A shown in the PV diagram.",
    figures: [fig(F.pvDiagram({ states: [{ label: "A", V: 1, P: 150, dx: -16 }, { label: "B", V: 3, P: 150 }, { label: "C", V: 3, P: 50 }, { label: "D", V: 1, P: 50, dx: -16, dy: 16 }], xMax: 4, yMax: 180, yStep: 30 }),
      "A PV diagram of a rectangular cycle. State A is at 1 liter and 150 kilopascals, B at 3 liters and 150 kilopascals, C at 3 liters and 50 kilopascals, and D at 1 liter and 50 kilopascals. The cycle runs A to B to C to D and back to A, clockwise.")],
  }, [
    S(9, "What is the net work done by the gas during one complete cycle?",
      ["100 J", "200 J", "300 J", "400 J"], 1,
      "The net work equals the area enclosed by the cycle: ΔV × ΔP = (3 − 1)(10⁻³ m³) × (150 − 50)(10³ Pa) = 200 J. The cycle runs clockwise, so the net work done by the gas is positive."),
    M(9, "At which state is the temperature of the gas the highest?",
      ["State B", "State A", "State C", "State D"],
      "For a fixed amount of an ideal gas, PV = nRT, so the temperature is proportional to the product PV. The products are: A: 150, B: 450, C: 150, and D: 50 (in kPa·L). State B has the largest product, so it has the highest temperature."),
  ]),
  S(9,
    "A heat engine absorbs 800 J of heat from a hot reservoir during each cycle and exhausts 600 J of heat to a cold reservoir. What is the efficiency of the engine?",
    ["25%", "33%", "75%", "133%"], 0,
    "The work done per cycle is W = Q_H − Q_C = 800 − 600 = 200 J, so the efficiency is e = W/Q_H = 200/800 = 25%. 75% is the fraction of the heat that is exhausted instead."),
  S(9,
    "What is the maximum possible efficiency of a heat engine that operates between a hot reservoir at 900 K and a cold reservoir at 300 K?",
    ["33%", "50%", "60%", "67%"], 3,
    "The Carnot efficiency is the upper limit for any engine operating between two temperatures: e = 1 − T_C/T_H = 1 − 300/900 = 0.67, or 67%. 33% is the ratio T_C/T_H, which is the fraction of the heat that must be exhausted."),
  M(9,
    "The absolute temperature of a fixed amount of an ideal gas in a rigid container is doubled. What happens to the average translational kinetic energy of the gas molecules?",
    ["It doubles, because it is proportional to the absolute temperature.",
     "It quadruples, because the kinetic energy depends on the square of the speed.",
     "It stays the same, because the volume of the container does not change.",
     "It increases by a factor of √2, because the speed increases by that factor."],
    "The average translational kinetic energy of an ideal gas molecule is (3/2)k_BT, which is directly proportional to the absolute temperature. Doubling T doubles the average kinetic energy. The rms speed increases by √2, but the energy depends on the speed squared, so the energy doubles."),
  S(9,
    "A 0.20 kg piece of metal at 100 °C is placed in 0.50 kg of water at 20 °C in an insulated container. The final equilibrium temperature is 24 °C. What is the specific heat capacity of the metal? (The specific heat of water is 4200 J/(kg·°C).)",
    ["280 J/(kg·°C)", "550 J/(kg·°C)", "1100 J/(kg·°C)", "4200 J/(kg·°C)"], 1,
    "Energy lost by the metal equals the energy gained by the water: m_m c_m (100 − 24) = m_w c_w (24 − 20). Then c_m = (0.50)(4200)(4)/((0.20)(76)) = 8400/15.2 ≈ 550 J/(kg·°C)."),

  // ================= Unit 10 (7) =================
  S(10,
    "Two point charges, +3.0 μC and −6.0 μC, are 0.30 m apart. What is the magnitude of the electric force between them?",
    ["0.90 N", "1.8 N", "5.4 N", "18 N"], 1,
    "F = k|q₁q₂|/r² = (9.0 × 10⁹)(3.0 × 10⁻⁶)(6.0 × 10⁻⁶)/(0.30)² = 1.8 N. The force is attractive because the charges have opposite signs."),
  S(10,
    "An electron is accelerated from rest through a potential difference of 200 V. What kinetic energy does the electron gain?",
    ["1.6 × 10⁻¹⁹ J", "1.6 × 10⁻¹⁷ J", "3.2 × 10⁻¹⁷ J", "3.2 × 10⁻¹⁵ J"], 2,
    "The kinetic energy gained equals the decrease in electric potential energy: ΔK = qΔV = (1.6 × 10⁻¹⁹ C)(200 V) = 3.2 × 10⁻¹⁷ J (200 eV). 1.6 × 10⁻¹⁷ J would result from using a potential difference of 100 V."),
  G(10, {
    text: "Two identical point charges of +1.0 μC are fixed 0.40 m apart. Point P is midway between them.",
    figures: [fig(F.chargeLine({ items: [{ x: 110, q: "+", label: "+Q" }, { x: 240, name: "P" }, { x: 370, q: "+", label: "+Q" }], spans: [{ x1: 110, x2: 370, label: "0.40 m" }] }),
      "A horizontal line with a positive charge on the left, a point P in the middle, and another positive charge of equal magnitude on the right. The charges are 0.40 meters apart.")],
  }, [
    M(10, "What is the net electric field at point P?",
      ["Zero, because the fields from the two charges are equal in magnitude and opposite in direction.",
       "4.5 × 10⁵ N/C directed to the right, because the fields from the two charges add.",
       "2.25 × 10⁵ N/C directed to the left, because only the right charge's field matters at P.",
       "2.25 × 10⁵ N/C directed to the right, because only the left charge's field matters at P."],
      "P is 0.20 m from each charge, so each charge produces a field of magnitude kQ/r² = (9.0 × 10⁹)(1.0 × 10⁻⁶)/(0.20)² = 2.25 × 10⁵ N/C. The field of the left charge points to the right (away from it), and the field of the right charge points to the left (away from it), so they cancel exactly. Electric fields are vectors, so the cancellation occurs only when directions are opposite."),
    S(10, "What is the electric potential at point P? (Take V = 0 infinitely far from the charges.)",
      ["0 V", "4.5 × 10⁴ V", "9.0 × 10⁴ V", "1.8 × 10⁵ V"], 2,
      "Potential is a scalar, so the contributions from the two charges add: V = 2kQ/r = 2(9.0 × 10⁹)(1.0 × 10⁻⁶)/(0.20) = 9.0 × 10⁴ V. Although the field is zero at P, the potential is not: the two positive charges both raise the potential there."),
  ]),
  S(10,
    "A parallel-plate capacitor has plates of area 0.020 m² separated by 1.0 mm, with vacuum between them. What is its capacitance? (ε₀ = 8.85 × 10⁻¹² C²/(N·m²))",
    ["1.8 × 10⁻¹² F", "1.8 × 10⁻¹¹ F", "1.8 × 10⁻¹⁰ F", "1.8 × 10⁻⁹ F"], 2,
    "C = ε₀A/d = (8.85 × 10⁻¹²)(0.020)/(1.0 × 10⁻³) = 1.77 × 10⁻¹⁰ F. The separation must be in meters (1.0 mm = 1.0 × 10⁻³ m)."),
  M(10,
    "Which of the following statements about electric field lines is correct?",
    ["Field lines are closer together in regions where the electric field is stronger.",
     "Field lines can cross each other at points where two fields are equal.",
     "Field lines start on negative charges and end on positive charges.",
     "A charged particle released from rest always moves along a field line's curved path."],
    "The density of field lines represents the field's strength: closer lines mean a stronger field. Field lines never cross, because the field has one direction at each point. They begin on positive charges and end on negative charges. A charge released from rest begins moving along the field line direction, but it does not necessarily follow a curved line afterward because of its inertia."),
  M(10,
    "A charged particle moves from one point to another along an equipotential surface. How much work does the electric field do on the particle?",
    ["Zero, because the potential difference between the two points is zero.",
     "Positive, because the electric field exerts a force on the particle.",
     "Negative, because the particle is moving against the electric field.",
     "It depends on the length of the path along the surface."],
    "The work done by the electric field is W = −qΔV. On an equipotential surface ΔV = 0, so the work is zero regardless of the path. The electric field is perpendicular to the equipotential surface, so it exerts no force component along the motion."),

  // ================= Unit 11 (6) =================
  G(11, {
    text: "Three resistors are connected in parallel across a 12 V battery that has negligible internal resistance, as shown.",
    figures: [fig(F.circuitParallel({ V: 12, rs: ["R₁ = 6 Ω", "R₂ = 12 Ω", "R₃ = 4 Ω"] }),
      "A circuit with a 12 volt battery connected across three parallel resistors of 6 ohms, 12 ohms, and 4 ohms.")],
  }, [
    S(11, "What is the total current supplied by the battery?",
      ["2.0 A", "3.0 A", "6.0 A", "11 A"], 2,
      "Each resistor has the full 12 V across it, so the currents are 12/6 = 2.0 A, 12/12 = 1.0 A, and 12/4 = 3.0 A. The battery supplies their sum: 6.0 A."),
    M(11, "Which resistor dissipates the greatest power?",
      ["The 4 Ω resistor, because it carries the greatest current at the same voltage.",
       "The 12 Ω resistor, because it has the largest resistance.",
       "The 6 Ω resistor, because it is the first one connected to the battery.",
       "All three dissipate the same power, because they have the same voltage across them."],
      "For resistors in parallel the voltage is the same, so P = V²/R is largest for the smallest resistance. The 4 Ω resistor dissipates 144/4 = 36 W, compared with 24 W for the 6 Ω resistor and 12 W for the 12 Ω resistor. Equal voltage does not mean equal power; the current differs."),
    S(11, "What is the equivalent resistance of the three resistors?",
      ["2.0 Ω", "4.0 Ω", "6.0 Ω", "22 Ω"], 0,
      "For parallel resistors, 1/R_eq = 1/6 + 1/12 + 1/4 = (2 + 1 + 3)/12 = 6/12 = 1/2, so R_eq = 2.0 Ω. (This agrees with R = V/I = 12/6.0.) The value 22 Ω is the sum, which applies to resistors in series."),
  ]),
  S(11,
    "A space heater is rated at 1500 W when connected to a 120 V outlet. What is the resistance of the heater element?",
    ["9.6 Ω", "12.5 Ω", "180 Ω", "18,000 Ω"], 0,
    "The power is P = V²/R, so R = V²/P = (120)²/1500 = 9.6 Ω. The value 12.5 is the current in amperes, I = P/V, not a resistance."),
  S(11,
    "A 100 W lightbulb operates for 5.0 hours. How much electrical energy does the bulb use?",
    ["0.020 kWh", "0.50 kWh", "5.0 kWh", "500 kWh"], 1,
    "Energy equals power times time: (0.100 kW)(5.0 h) = 0.50 kWh."),
  S(11,
    "At a junction in a circuit, currents of 3.0 A and 2.0 A flow into the junction, and currents of I and 1.0 A flow out of it. What is the value of I?",
    ["1.0 A", "4.0 A", "5.0 A", "6.0 A"], 1,
    "Kirchhoff's junction rule says the total current entering equals the total current leaving: 3.0 + 2.0 = I + 1.0, so I = 4.0 A."),

  // ================= Unit 12 (6) =================
  S(12,
    "Electrons traveling at 3.0 × 10⁶ m/s enter a region where a uniform magnetic field of 1.0 × 10⁻⁴ T is directed at a right angle to their velocity. Each electron follows a circular arc. What is the radius of the arc? (m_e = 9.1 × 10⁻³¹ kg and e = 1.6 × 10⁻¹⁹ C)",
    ["0.017 m", "0.17 m", "1.7 m", "17 m"], 1,
    "The magnetic force provides the centripetal force: evB = mv²/r, so r = mv/(eB) = (9.1 × 10⁻³¹)(3.0 × 10⁶)/((1.6 × 10⁻¹⁹)(1.0 × 10⁻⁴)) ≈ 0.17 m."),
  M(12,
    "A negatively charged particle moves toward the top of the page in a uniform magnetic field directed out of the page, as shown. What is the direction of the magnetic force on the particle at the instant shown?",
    ["Toward the left side of the page", "Toward the right side of the page", "Toward the top of the page", "Into the page"],
    "Using F = qv × B: for a positive charge moving up in a field out of the page, v × B points to the right. Because the particle is negatively charged, the force is reversed and points to the left. The force is perpendicular to both the velocity and the field.",
    { figures: [fig(F.magneticField({ dir: "out", vdir: "up", q: "-" }), "A grid of dots showing a magnetic field directed out of the page. A negative charge in the middle moves toward the top of the page with a velocity arrow pointing up.", { maxWidth: 420 })] }),
  S(12,
    "A conducting rod 0.40 m long moves at 3.0 m/s through a uniform 0.50 T magnetic field. The rod, its velocity, and the field are mutually perpendicular. What is the magnitude of the emf induced between the ends of the rod?",
    ["0.15 V", "0.60 V", "1.2 V", "6.0 V"], 1,
    "The motional emf is ε = BLv = (0.50)(0.40)(3.0) = 0.60 V."),
  M(12,
    "A rectangular conducting loop moves at constant velocity while remaining entirely inside a region of uniform magnetic field, with the plane of the loop perpendicular to the field. What is the induced emf in the loop?",
    ["Zero, because the magnetic flux through the loop is not changing.",
     "Nonzero, because the loop is moving through a magnetic field.",
     "Nonzero, because the field exerts a force on each side of the loop.",
     "Zero, because the loop has no resistance."],
    "An emf is induced only when the magnetic flux through the loop changes. Here the field is uniform and the loop's area and orientation do not change, so the flux is constant and there is no induced emf. (Forces on the charges in opposite sides of the loop do act, but they cancel around the loop.)"),
  M(12,
    "Two long, straight, parallel wires carry currents in the same direction. Which of the following describes the force the wires exert on each other?",
    ["The wires attract each other.",
     "The wires repel each other.",
     "The wires exert no force on each other, because they are neutral.",
     "Each wire is pushed perpendicular to the plane containing both wires."],
    "Each wire creates a magnetic field at the location of the other. Using the right-hand rules, the force on each wire points toward the other when the currents are parallel, so the wires attract. They repel when the currents are in opposite directions."),
  S(12,
    "A proton moves in a circular path of radius r in a uniform magnetic field. If the proton's speed is doubled while the field stays the same, what is the new radius of its path?",
    ["r/2", "r", "2r", "4r"], 2,
    "From mv²/r = qvB, the radius is r = mv/(qB), which is directly proportional to the speed. Doubling the speed doubles the radius, to 2r."),

  // ================= Unit 13 (5) =================
  S(13,
    "Light travels inside a piece of glass with an index of refraction of 1.6 toward a boundary with air. What is the critical angle for total internal reflection at the glass–air boundary?",
    ["19°", "30°", "39°", "51°"], 2,
    "The critical angle satisfies n_glass sin θ_c = n_air sin 90°, so sin θ_c = 1/1.6 = 0.625 and θ_c ≈ 39°. The value 51° is the complement (90° − 39°)."),
  G(13, {
    text: "A thin converging lens has a focal length of 15 cm. An object is placed 20 cm from the lens, as shown. (The vertical scale of the diagram is exaggerated.)",
    figures: [fig(F.lensRays({ f: 15, dO: 20, h: 3, scale: 4, vscale: 8 }), "A ray diagram for a converging lens with the object between one and two focal lengths from the lens. Two rays from the arrow tip, one parallel to the axis and one through the lens center, meet far to the right of the lens, forming a large inverted image.")],
  }, [
    S(13, "How far from the lens is the image?",
      ["8.6 cm", "30 cm", "60 cm", "75 cm"], 2,
      "From 1/f = 1/d_o + 1/d_i: 1/d_i = 1/15 − 1/20 = 1/60, so d_i = 60 cm."),
    S(13, "What is the magnification of the image?",
      ["−3.0", "−1.3", "+1.3", "+3.0"], 0,
      "m = −d_i/d_o = −60/20 = −3.0. The image is inverted (negative sign) and three times as tall as the object."),
  ]),
  M(13,
    "Under which of the following conditions can total internal reflection occur at a boundary between two transparent media?",
    ["Light travels from the medium with the higher index of refraction toward the medium with the lower index, at an angle of incidence greater than the critical angle.",
     "Light travels from the medium with the lower index of refraction toward the medium with the higher index, at an angle of incidence greater than the critical angle.",
     "Light strikes the boundary at normal incidence from either medium.",
     "Light travels from either medium at any angle if the boundary is smooth enough."],
    "Total internal reflection requires light to travel from a higher-index medium toward a lower-index medium (so that the refracted ray would bend away from the normal) and to strike the boundary at an angle larger than the critical angle. When going from a lower to a higher index, light always refracts into the second medium."),
  S(13,
    "A person stands 0.80 m in front of a plane mirror. What is the distance between the person and the person's image?",
    ["0.40 m", "0.80 m", "1.6 m", "3.2 m"], 2,
    "A plane mirror forms a virtual image as far behind the mirror as the object is in front of it: 0.80 m. The distance from the person to the image is 0.80 + 0.80 = 1.6 m."),

  // ================= Unit 14 (6) =================
  M(14,
    "A sound source moves toward a stationary observer. Compared with the frequency emitted by the source, how does the frequency detected by the observer differ?",
    ["The detected frequency is higher, because the wavelength between the source and the observer is shortened.",
     "The detected frequency is lower, because the source's motion reduces the wave speed.",
     "The detected frequency is the same, because the speed of sound does not depend on the source's motion.",
     "The detected frequency is higher, because the speed of the sound waves increases."],
    "The speed of sound in air depends only on the medium, not on the motion of the source. As the source moves toward the observer, it follows the waves it emits, so successive crests are closer together (a shorter wavelength). With the same wave speed, a shorter wavelength means a higher detected frequency — the Doppler effect."),
  S(14,
    "A pipe that is open at one end and closed at the other has a length of 0.50 m. If the speed of sound is 340 m/s, what is the frequency of the fundamental standing wave in the pipe?",
    ["85 Hz", "170 Hz", "340 Hz", "680 Hz"], 1,
    "For a pipe closed at one end, the fundamental has a node at the closed end and an antinode at the open end: L = λ/4, so λ = 4L = 2.0 m. Then f = v/λ = 340/2.0 = 170 Hz. A pipe open at both ends of the same length would have a fundamental of 340 Hz."),
  S(14,
    "A diffraction grating has 500 lines per millimeter. Light of wavelength 600 nm is incident normally on the grating. At what angle from the normal is the first-order maximum observed?",
    ["8.6°", "17.5°", "30°", "53°"], 1,
    "The line spacing is d = 1/500 mm = 2.0 × 10⁻⁶ m. For the first-order maximum, d sin θ = λ, so sin θ = (600 × 10⁻⁹)/(2.0 × 10⁻⁶) = 0.30 and θ ≈ 17.5°."),
  G(14, {
    text: "A guitar string that is 0.60 m long is held fixed at both ends. It is plucked so that it vibrates in the pattern shown, with two loops and a node at its center. Waves travel along this string at 60 m/s.",
    figures: [fig(F.standingWave({ n: 2, L: "L = 0.60 m" }), "A standing wave on a string fixed at both ends showing two loops, with a node in the middle. The string length is 0.60 meters.", { maxWidth: 440 })],
  }, [
    S(14, "What is the wavelength of the standing wave?",
      ["0.30 m", "0.60 m", "1.2 m", "2.4 m"], 1,
      "Two loops means two half-wavelengths fit on the string: 2(λ/2) = L, so λ = L = 0.60 m."),
    S(14, "At what frequency does the string vibrate in this pattern?",
      ["25 Hz", "50 Hz", "100 Hz", "200 Hz"], 2,
      "f = v/λ = 60/0.60 = 100 Hz."),
  ]),
  M(14,
    "In a double-slit interference experiment, the distance between the two slits is decreased while the wavelength of the light and the distance to the screen stay the same. What happens to the spacing between adjacent bright fringes on the screen?",
    ["It increases.", "It decreases.", "It stays the same.", "It becomes zero."],
    "The fringe spacing is Δy = λL/d, which is inversely proportional to the slit separation d. Decreasing d therefore increases the spacing between the bright fringes."),

  // ================= Unit 15 (5) =================
  S(15,
    "An electron has a momentum of 2.0 × 10⁻²⁴ kg·m/s. What is its de Broglie wavelength? (h = 6.63 × 10⁻³⁴ J·s)",
    ["3.3 × 10⁻¹¹ m", "3.3 × 10⁻¹⁰ m", "3.3 × 10⁻⁹ m", "1.3 × 10⁻⁵⁸ m"], 1,
    "The de Broglie wavelength is λ = h/p = (6.63 × 10⁻³⁴)/(2.0 × 10⁻²⁴) = 3.3 × 10⁻¹⁰ m. The value 1.3 × 10⁻⁵⁸ m results from multiplying h by p instead of dividing."),
  G(15, {
    text: "The graph shows the maximum kinetic energy of electrons ejected from a metal surface as a function of the frequency of the light incident on the surface. The frequency f₀ marks the threshold frequency, which is 5.0 × 10¹⁴ Hz.",
    figures: [fig(F.photoGraph({ f0: 5, slope: 0.41 }), "A graph of maximum kinetic energy in electron volts against light frequency in units of 10 to the 14 hertz. A straight line rises from zero at the threshold frequency of 5.0 and reaches about 2 electron volts at a frequency of 10.", { maxWidth: 480 })],
  }, [
    S(15, "What is the work function of the metal? (h = 4.14 × 10⁻¹⁵ eV·s)",
      ["1.0 eV", "2.1 eV", "3.4 eV", "4.1 eV"], 1,
      "At the threshold frequency the photon energy equals the work function: φ = hf₀ = (4.14 × 10⁻¹⁵ eV·s)(5.0 × 10¹⁴ Hz) = 2.07 eV ≈ 2.1 eV."),
    M(15, "The intensity of the incident light is doubled while its frequency stays above f₀. What happens to the maximum kinetic energy of the ejected electrons and to the number of electrons ejected per second?",
      ["The maximum kinetic energy is unchanged, and the number of electrons per second increases.",
       "The maximum kinetic energy doubles, and the number of electrons per second is unchanged.",
       "The maximum kinetic energy doubles, and the number of electrons per second doubles.",
       "The maximum kinetic energy is unchanged, and the number of electrons per second is unchanged."],
      "The maximum kinetic energy is K_max = hf − φ, which depends on the frequency and not on the intensity. Doubling the intensity doubles the number of photons arriving per second, so more electrons are ejected each second, each with the same maximum kinetic energy."),
  ]),
  S(15,
    "In a nuclear reaction, the total mass of the products is 0.030 u less than the total mass of the reactants. How much energy is released in the reaction? (1 u = 931.5 MeV/c²)",
    ["0.28 MeV", "2.8 MeV", "28 MeV", "280 MeV"], 2,
    "The energy released is E = Δmc² = (0.030 u)(931.5 MeV/u) = 27.9 MeV ≈ 28 MeV."),
  M(15,
    "A nucleus of uranium-238 (atomic number 92, mass number 238) undergoes alpha decay. What are the atomic number and mass number of the daughter nucleus?",
    ["Atomic number 90, mass number 234", "Atomic number 91, mass number 238", "Atomic number 90, mass number 236", "Atomic number 93, mass number 238"],
    "An alpha particle is a helium nucleus with two protons and two neutrons (Z = 2, A = 4). The daughter nucleus has Z = 92 − 2 = 90 and A = 238 − 4 = 234 (thorium-234). A change of Z by +1 with the same A would be beta-minus decay."),
];
