import { S, M, G, fig } from "./pool.mjs";
import * as F from "./p2figs.mjs";

export const config = { hub: "physics2", prefix: "p2e", N: 3, file: "exam3.js", title: "AP Physics 2 — Exam 3", seed: 303, units: { 9: 6, 10: 7, 11: 7, 12: 6, 13: 6, 14: 5, 15: 5 }, note: "Uses g = 10 m/s²." };

export default [
  // ================= Unit 9 (6) =================
  G(9, {
    text: "A fixed amount of an ideal gas is taken through the cycle A → B → C → A shown in the PV diagram. Process A → B occurs at constant volume, process B → C is a straight line, and process C → A occurs at constant pressure.",
    figures: [fig(F.pvDiagram({ states: [{ label: "A", V: 2, P: 100, dx: -16, dy: 18 }, { label: "B", V: 2, P: 200, dx: -16 }, { label: "C", V: 4, P: 100 }], xMax: 5, yMax: 240, yStep: 40 }),
      "A PV diagram of a triangular cycle. State A is at 2 liters and 100 kilopascals, B at 2 liters and 200 kilopascals, and C at 4 liters and 100 kilopascals. The cycle runs A to B to C and back to A, clockwise.")],
  }, [
    S(9, "How much net work does the gas do in one trip around the cycle?",
      ["50 J", "100 J", "200 J", "400 J"], 1,
      "The net work is the area enclosed by the cycle: ½(ΔV)(ΔP) = ½(2 × 10⁻³ m³)(100 × 10³ Pa) = 100 J. The cycle runs clockwise, so the net work done by the gas is positive."),
    S(9, "How much work does the gas do during process B → C?",
      ["150 J", "300 J", "400 J", "600 J"], 1,
      "The work done by the gas equals the area under the B → C line. The pressure falls linearly from 200 kPa to 100 kPa, so the average pressure is 150 kPa, and W = (150 × 10³ Pa)(2 × 10⁻³ m³) = 300 J."),
    M(9, "Which of the following correctly describes process C → A?",
      ["The gas releases heat to its surroundings, and its internal energy decreases.",
       "The gas absorbs heat from its surroundings, and its internal energy increases.",
       "The gas releases heat to its surroundings, and its internal energy stays constant.",
       "The gas neither absorbs nor releases heat, because the pressure is constant."],
      "At constant pressure the volume decreases, and since PV = nRT, the temperature falls as V falls at fixed P. The internal energy therefore decreases (ΔU < 0). Work is done on the gas (W_by < 0), so by the first law Q = ΔU + W_by is even more negative: the gas releases heat. A constant pressure does not mean there is no heat flow."),
  ]),
  S(9,
    "How much thermal energy is needed to melt 0.50 kg of ice that is already at 0 °C? (The latent heat of fusion of water is 3.3 × 10⁵ J/kg.)",
    ["8.3 × 10⁴ J", "1.65 × 10⁵ J", "3.3 × 10⁵ J", "6.6 × 10⁵ J"], 1,
    "During melting at a constant temperature, Q = mL_f = (0.50)(3.3 × 10⁵) = 1.65 × 10⁵ J. No temperature change formula (mcΔT) applies while the ice is melting."),
  M(9,
    "A container holds hydrogen gas (H₂) and a second, identical container holds oxygen gas (O₂). Both gases are ideal and are at the same temperature. Which statement is correct?",
    ["The molecules have the same average kinetic energy, but the hydrogen molecules have the greater average speed.",
     "The hydrogen molecules have the greater average kinetic energy and the greater average speed.",
     "The molecules have the same average speed, but the oxygen molecules have the greater average kinetic energy.",
     "The oxygen molecules have the greater average kinetic energy and the greater average speed."],
    "The average translational kinetic energy depends only on the temperature, K = (3/2)k_BT, so it is the same for both gases. Since K = ½mv², the lighter hydrogen molecules must have the greater average speed."),
  S(9,
    "An ideal gas is compressed quickly in an insulated cylinder, so that no heat is exchanged with the surroundings. During the compression, 200 J of work is done on the gas. What is the change in the internal energy of the gas?",
    ["−200 J", "0 J", "+100 J", "+200 J"], 3,
    "The process is adiabatic, so Q = 0. By the first law, ΔU = Q + W_on = 0 + 200 = +200 J. The temperature of the gas rises as its internal energy increases."),

  // ================= Unit 10 (7) =================
  S(10,
    "The electric force between two small charged spheres is 9.0 N when they are 0.10 m apart. What is the magnitude of the force when the spheres are 0.30 m apart? (The charges do not change.)",
    ["0.33 N", "1.0 N", "3.0 N", "27 N"], 1,
    "Coulomb's force varies as 1/r². Tripling the distance reduces the force by a factor of 9: 9.0/9 = 1.0 N. The value 3.0 N results from dividing by 3 rather than 9."),
  S(10,
    "At what distance from an isolated point charge of +2.0 nC is the magnitude of the electric field equal to 450 N/C?",
    ["0.040 m", "0.20 m", "0.40 m", "2.0 m"], 1,
    "E = kq/r² gives r = √(kq/E) = √((9.0 × 10⁹)(2.0 × 10⁻⁹)/450) = √(0.040) = 0.20 m."),
  S(10,
    "What is the electric potential at a point 0.30 m from an isolated point charge of −4.0 nC? (Take V = 0 infinitely far from the charge.)",
    ["−120 V", "−36 V", "+36 V", "+120 V"], 0,
    "V = kq/r = (9.0 × 10⁹)(−4.0 × 10⁻⁹)/(0.30) = −120 V. The potential near a negative charge is negative."),
  G(10, {
    text: "An electron is released from rest at the negative plate of a parallel-plate capacitor. The plates are 4.0 cm apart, and a potential difference of 200 V is maintained between them, as shown. Ignore gravity. (m_e = 9.1 × 10⁻³¹ kg and e = 1.6 × 10⁻¹⁹ C)",
    figures: [fig(F.plateCapacitor({ V: "200 V", d: "4.0 cm" }), "Two horizontal parallel plates, the upper one positive and the lower one negative, separated by 4.0 centimeters, with an electric field pointing from the upper plate to the lower plate. A 200 volt potential difference is applied.", { maxWidth: 360 })],
  }, [
    S(10, "What is the magnitude of the electric field between the plates?",
      ["5.0 × 10³ V/m", "8.0 × 10³ V/m", "5.0 × 10⁴ V/m", "5.0 × 10⁶ V/m"], 0,
      "E = V/d = 200/(0.040) = 5.0 × 10³ V/m. The separation must be converted from centimeters to meters."),
    S(10, "What is the speed of the electron just before it reaches the positive plate?",
      ["8.4 × 10⁴ m/s", "8.4 × 10⁵ m/s", "8.4 × 10⁶ m/s", "8.4 × 10⁷ m/s"], 2,
      "The electron gains kinetic energy equal to the potential energy lost: eΔV = ½mv². Then v = √(2eΔV/m) = √(2(1.6 × 10⁻¹⁹)(200)/(9.1 × 10⁻³¹)) ≈ 8.4 × 10⁶ m/s."),
  ]),
  S(10,
    "A metal sphere has a charge of +6.0 μC. It is touched to an identical, neutral metal sphere, and the spheres are then separated. What is the charge on each sphere after they are separated?",
    ["0", "+1.5 μC", "+3.0 μC", "+6.0 μC"], 2,
    "When identical conductors touch, the total charge is shared equally, so each sphere ends up with half of +6.0 μC, which is +3.0 μC. Total charge is conserved."),
  M(10,
    "A solid metal sphere carries a net positive charge and is in electrostatic equilibrium. Which statement about the sphere is correct?",
    ["The electric field is zero everywhere inside the metal, and the excess charge is on the surface.",
     "The electric field points outward everywhere inside the metal, and the excess charge is spread throughout the volume.",
     "The electric field is zero everywhere inside the metal, and the excess charge is spread throughout the volume.",
     "The electric field points outward everywhere inside the metal, and the excess charge is on the surface."],
    "In electrostatic equilibrium the mobile charges in a conductor have stopped moving, which requires the electric field inside the conductor to be zero. Excess charge repels itself and moves as far apart as it can, ending up on the outer surface."),

  // ================= Unit 11 (7) =================
  G(11, {
    text: "Three resistors are connected in series with a 12 V battery that has negligible internal resistance, as shown.",
    figures: [fig(F.circuitSeries({ V: 12, rs: ["2 Ω", "3 Ω", "7 Ω"] }), "A series circuit with a 12 volt battery and three resistors of 2 ohms, 3 ohms, and 7 ohms in a single loop.")],
  }, [
    S(11, "What is the current in the 3 Ω resistor?",
      ["0.50 A", "1.0 A", "2.0 A", "4.0 A"], 1,
      "The resistors are in series, so they carry the same current: I = V/R_total = 12/(2 + 3 + 7) = 1.0 A."),
    S(11, "What is the potential difference across the 7 Ω resistor?",
      ["1.0 V", "3.0 V", "7.0 V", "12 V"], 2,
      "The current is 1.0 A, so V = IR = (1.0)(7) = 7.0 V. The 12 V of the battery is divided among the three resistors (2 V + 3 V + 7 V)."),
    M(11, "The 3 Ω resistor is replaced by a 6 Ω resistor. How does the current in the circuit change?",
      ["The current decreases, because the total resistance increases.",
       "The current increases, because the resistor with a larger resistance allows more current.",
       "The current stays the same, because the battery's potential difference is unchanged.",
       "The current decreases only in the 6 Ω resistor and stays the same elsewhere."],
      "In a series circuit the total resistance is the sum of the resistances. Replacing 3 Ω with 6 Ω raises the total from 12 Ω to 15 Ω. With the battery voltage fixed, I = V/R decreases (from 1.0 A to 0.80 A), and since the same current flows through every element of a series circuit, the current decreases everywhere."),
  ]),
  S(11,
    "Current of 2.0 A flows through a 5.0 Ω wire. What is the power dissipated in the wire?",
    ["10 W", "20 W", "40 W", "100 W"], 1,
    "P = I²R = (2.0)²(5.0) = 20 W. The value 10 W is the potential difference across the wire (IR = 10 V), which is not a power."),
  S(11,
    "A 4.0 μF capacitor and a 12 μF capacitor are connected in series. What is the equivalent capacitance of the combination?",
    ["3.0 μF", "8.0 μF", "16 μF", "48 μF"], 0,
    "For capacitors in series, 1/C_eq = 1/4.0 + 1/12 = 3/12 + 1/12 = 4/12, so C_eq = 3.0 μF. The sum, 16 μF, would apply to capacitors in parallel."),
  M(11,
    "A resistor and an initially uncharged capacitor are connected in series to a battery. After the switch is closed, what happens to the current in the circuit as the capacitor charges?",
    ["The current is largest at first and decreases toward zero as the capacitor charges.",
     "The current is zero at first and increases to a constant value as the capacitor charges.",
     "The current stays constant until the capacitor is fully charged and then drops to zero.",
     "The current is largest when the capacitor is fully charged."],
    "At the instant the switch is closed the capacitor has no charge and no potential difference, so the full battery voltage is across the resistor and the current is V/R, its maximum. As charge builds up, the capacitor's voltage grows and opposes the battery, reducing the voltage across the resistor and therefore the current. When the capacitor's voltage equals the battery's, the current is zero."),
  S(11,
    "Two 10 Ω resistors are connected in parallel, and this combination is connected in series with a 5.0 Ω resistor. What is the equivalent resistance of the whole combination?",
    ["5.0 Ω", "10 Ω", "15 Ω", "25 Ω"], 1,
    "The two 10 Ω resistors in parallel are equivalent to 5.0 Ω (10/2). In series with the 5.0 Ω resistor, the total is 5.0 + 5.0 = 10 Ω."),

  // ================= Unit 12 (6) =================
  S(12,
    "A coil of 50 turns has a magnetic flux through each turn that changes by 0.020 Wb in 0.40 s. What is the magnitude of the average emf induced in the coil?",
    ["0.050 V", "0.50 V", "2.5 V", "25 V"], 2,
    "Faraday's law for a coil gives |ε| = NΔΦ/Δt = (50)(0.020)/(0.40) = 2.5 V. Leaving out the number of turns would give 0.050 V."),
  M(12,
    "A positively charged particle travels toward the left edge of the page through a uniform magnetic field that points out of the page, as shown. In which direction does the magnetic field push the particle at the instant shown?",
    ["Toward the top of the page", "Toward the bottom of the page", "To the right", "Into the page"],
    "Using F = qv × B with v pointing left (−x) and B out of the page (+z): (−x) × (+z) = +y, which is toward the top of the page. For a positive charge the force points the same way as v × B.",
    { figures: [fig(F.magneticField({ dir: "out", vdir: "left", q: "+" }), "A grid of dots showing a magnetic field directed out of the page. A positive charge in the middle moves to the left with a velocity arrow pointing left.", { maxWidth: 420 })] }),
  S(12,
    "A straight wire 0.25 m long carries a current of 8.0 A. The wire makes an angle of 30° with a uniform magnetic field of 0.40 T. What is the magnitude of the magnetic force on the wire?",
    ["0.20 N", "0.40 N", "0.69 N", "0.80 N"], 1,
    "F = BIL sin θ = (0.40)(8.0)(0.25)(sin 30°) = 0.40 N. The value 0.69 N results from using cosine instead of sine, and 0.80 N ignores the angle."),
  M(12,
    "A long straight wire carries a current directed out of the page. Which of the following describes the magnetic field the wire produces in the plane of the page?",
    ["The field lines are circles centered on the wire, directed counterclockwise as seen from the front of the page.",
     "The field lines are circles centered on the wire, directed clockwise as seen from the front of the page.",
     "The field lines are straight lines directed away from the wire.",
     "The field lines are straight lines directed toward the wire."],
    "Using the right-hand rule for a straight wire, point the thumb along the current (out of the page) and curl the fingers: they circle the wire counterclockwise as seen from the front of the page. Magnetic field lines form closed loops around the current and never point radially toward or away from the wire."),
  S(12,
    "In a velocity selector, charged particles move through a region with a uniform electric field of 2000 V/m and a uniform magnetic field of 0.50 T, perpendicular to each other and to the particles' velocity. What speed must the particles have to pass straight through undeflected?",
    ["250 m/s", "1000 m/s", "4000 m/s", "1.0 × 10⁶ m/s"], 2,
    "Particles pass through undeflected when the electric and magnetic forces cancel: qE = qvB, so v = E/B = 2000/0.50 = 4000 m/s. The charge and mass do not matter."),
  M(12,
    "A strong bar magnet is dropped through a long vertical copper tube. Compared with a nonmagnetic object of the same mass, the magnet falls slowly. Which explanation is correct?",
    ["Induced currents in the tube create a magnetic force that opposes the magnet's motion (Lenz's law).", "The copper is attracted to the magnet, and this attraction supports part of its weight.", "Copper is a ferromagnetic material, so the magnet is held back by magnetic friction.", "The magnet loses its magnetization as it falls, which reduces its mass and its weight."],
    "As the magnet falls, the magnetic flux through each section of the tube changes. This induces circulating (eddy) currents in the copper, and by Lenz's law the magnetic field of these currents opposes the change, which exerts an upward force on the magnet. Copper is not ferromagnetic, so there is no attraction in the absence of motion."),

  // ================= Unit 13 (6) =================
  S(13,
    "A ray of light in water (n = 1.33) strikes the water–air boundary at an angle of incidence of 30° from the normal. What is the angle of refraction in the air?",
    ["22°", "30°", "42°", "49°"], 2,
    "Snell's law gives (1.33)(sin 30°) = (1.00) sin θ₂, so sin θ₂ = 0.665 and θ₂ ≈ 42°. The ray bends away from the normal as it enters the medium with the lower index."),
  G(13, {
    text: "A small bulb is placed 15 cm from a thin converging lens whose focal length is 10 cm, as shown. (The vertical scale of the diagram is exaggerated.)",
    figures: [fig(F.lensRays({ f: 10, dO: 15, h: 3, scale: 5, vscale: 10 }), "A ray diagram for a converging lens with the object between one and two focal lengths from the lens. Two rays from the arrow tip, one parallel to the axis and one through the lens center, meet to the right of the lens beyond twice the focal length, forming a large inverted image.")],
  }, [
    S(13, "At what distance from the lens does the bulb's image form?",
      ["6.0 cm", "15 cm", "30 cm", "45 cm"], 2,
      "From 1/f = 1/d_o + 1/d_i: 1/d_i = 1/10 − 1/15 = 1/30, so d_i = 30 cm."),
    M(13, "The object is moved to a point 5 cm from the lens. Which statement describes the image that is now formed?",
      ["It is virtual, upright, and larger than the object.",
       "It is real, inverted, and larger than the object.",
       "It is virtual, inverted, and smaller than the object.",
       "No image is formed, because the object is inside the focal length."],
      "With the object inside the focal length, 1/d_i = 1/10 − 1/5 = −1/10, so d_i = −10 cm. The negative sign means the image is virtual (on the same side as the object), and m = −d_i/d_o = +2 means upright and twice as large — a magnifying glass. An image is formed, but it can be seen only by looking through the lens."),
  ]),
  M(13,
    "A ray of light passes from air through a flat, parallel-sided glass slab and back into air. Which statement describes the ray that emerges from the slab?",
    ["It is parallel to the original ray but shifted sideways.",
     "It is bent toward the normal compared with the original ray.",
     "It is bent away from the normal compared with the original ray.",
     "It follows exactly the same line as the original ray."],
    "The ray bends toward the normal on entering the glass and bends back by the same angle on leaving, because the second refraction is the reverse of the first. The emerging ray is therefore parallel to the incoming ray but displaced sideways."),
  S(13,
    "An object is 60 cm in front of a concave mirror that has a focal length of 20 cm. How far from the mirror is the image?",
    ["15 cm", "30 cm", "60 cm", "90 cm"], 1,
    "The mirror equation gives 1/d_i = 1/f − 1/d_o = 1/20 − 1/60 = 2/60, so d_i = 30 cm (in front of the mirror, a real image)."),
  M(13,
    "An object is placed in front of a convex (diverging) mirror. Which statement describes the image formed, regardless of the object's position?",
    ["The image is virtual, upright, and smaller than the object.",
     "The image is real, inverted, and smaller than the object.",
     "The image is virtual, upright, and larger than the object.",
     "The image is real, upright, and the same size as the object."],
    "A convex mirror always forms a virtual image behind the mirror that is upright and reduced in size. This wide field of view is why convex mirrors are used on vehicles."),

  // ================= Unit 14 (5) =================
  S(14,
    "A single machine in a factory produces a sound level of 70 dB. When a second identical machine is turned on next to the first, what is the approximate total sound level?",
    ["70 dB", "73 dB", "77 dB", "140 dB"], 1,
    "Doubling the intensity raises the level by 10 log(2) ≈ 3 dB, so the level is about 73 dB. Decibels are logarithmic, so the levels do not add directly."),
  S(14,
    "Two tuning forks with frequencies of 440 Hz and 444 Hz are sounded together. How many beats per second does a listener hear?",
    ["2", "4", "442", "884"], 1,
    "The beat frequency equals the difference between the two frequencies: |444 − 440| = 4 beats per second."),
  G(14, {
    text: "The graph shows a snapshot of a transverse wave traveling along a rope. The wave moves with a speed of 16 cm/s.",
    figures: [fig(F.waveSnapshot({ A: 3, lam: 8, xMax: 16, xStep: 4 }), "A sinusoidal wave plotted as displacement in centimeters against position in centimeters. The wave has amplitude 3 centimeters and completes two full cycles between 0 and 16 centimeters.")],
  }, [
    S(14, "What is the wavelength of the wave?",
      ["3 cm", "4 cm", "8 cm", "16 cm"], 2,
      "Two complete cycles span 16 cm, so one wavelength is 8 cm. (3 cm is the amplitude, and 4 cm is half a wavelength.)"),
    S(14, "What is the period of the wave?",
      ["0.25 s", "0.50 s", "2.0 s", "8.0 s"], 1,
      "The frequency is f = v/λ = 16/8 = 2.0 Hz, so the period is T = 1/f = 0.50 s. Alternatively T = λ/v = 8/16 = 0.50 s."),
  ]),
  M(14,
    "In a single-slit diffraction experiment using monochromatic light, the width of the slit is decreased while the wavelength and the distance to the screen stay the same. What happens to the width of the central bright maximum on the screen?",
    ["It increases.", "It decreases.", "It stays the same.", "It disappears."],
    "The angular position of the first minimum satisfies a sin θ = λ. A narrower slit (smaller a) gives a larger angle θ, so the central maximum spreads out and becomes wider."),

  // ================= Unit 15 (5) =================
  S(15,
    "A photon has an energy of 3.0 eV. What is its frequency? (h = 6.63 × 10⁻³⁴ J·s and 1 eV = 1.6 × 10⁻¹⁹ J)",
    ["1.4 × 10⁻¹⁵ Hz", "7.2 × 10¹³ Hz", "7.2 × 10¹⁴ Hz", "4.5 × 10¹⁵ Hz"], 2,
    "Convert the energy to joules: 3.0 eV = 4.8 × 10⁻¹⁹ J. Then f = E/h = (4.8 × 10⁻¹⁹)/(6.63 × 10⁻³⁴) ≈ 7.2 × 10¹⁴ Hz."),
  G(15, {
    text: "The figure shows the lowest four energy levels of a hydrogen atom. Use hc = 1240 eV·nm.",
    figures: [fig(F.energyLevels({ levels: [{ n: 1, E: -13.6 }, { n: 2, E: -3.4 }, { n: 3, E: -1.51 }, { n: 4, E: -0.85 }] }), "An energy level diagram for hydrogen with levels n equals 1 at minus 13.6 electron volts, n equals 2 at minus 3.4, n equals 3 at minus 1.51, and n equals 4 at minus 0.85, with a dashed line at 0 electron volts for ionization.", { maxWidth: 420 })],
  }, [
    S(15, "Which wavelength of light does the atom emit in the n = 3 to n = 2 transition?",
      ["122 nm", "365 nm", "656 nm", "1280 nm"], 2,
      "The photon energy is ΔE = −1.51 − (−3.4) = 1.89 eV. Then λ = hc/ΔE = 1240/1.89 ≈ 656 nm, a red photon in the visible range."),
    S(15, "What is the minimum energy needed to ionize a hydrogen atom that is in its ground state?",
      ["3.4 eV", "10.2 eV", "13.6 eV", "27.2 eV"], 2,
      "Ionization means moving the electron from n = 1 (−13.6 eV) to 0 eV, which requires 13.6 eV. The value 10.2 eV is the energy needed to excite the electron from n = 1 to n = 2."),
  ]),
  S(15,
    "The count rate from a radioactive sample falls from 800 counts per second to 100 counts per second in 15 days. What is the half-life of the sample?",
    ["3.0 days", "5.0 days", "7.5 days", "15 days"], 1,
    "The count rate falls by a factor of 8 = 2³, so three half-lives have passed in 15 days. The half-life is 15/3 = 5.0 days."),
  M(15,
    "Which of the following phenomena provides direct evidence for the particle nature of light?",
    ["The photoelectric effect, in which electrons are ejected only if the light's frequency exceeds a threshold",
     "Single-slit diffraction, in which light spreads out after passing through a narrow opening",
     "Double-slit interference, in which light produces alternating bright and dark fringes",
     "Refraction, in which light bends as it passes from air into glass"],
    "In the photoelectric effect, the ejection of electrons depends on the frequency, not the intensity, of the light, which classical wave theory cannot explain. It shows that light energy comes in packets (photons) with E = hf. Diffraction, interference and refraction are all explained by the wave model."),
];
