export default [
  ["cube with sides that are 2 μm long", 3.0],
  ["solute potential (Ψs) of −0.40 MPa", -0.30],
  ["pH of 5 has how many times", 100],
  ["net gain) for each molecule of glucose", 2],
  ["how many molecules of CO₂ must be fixed", 3],
  ["What percentage of the control cells were in interphase", 92],
  ["2n = 8 chromosomes in its somatic cells", 4],
  ["doubles every 6 hours", 16],
  ["genotype aabb", 1/16],
  ["chi-square statistic", 1.60],
  ["30% of the nucleotides are adenine", 20],
  ["approximate size of the plasmid", 3000],
  ["frequency of heterozygous individuals", 0.48],
  ["98 have the genotype AA", 0.30],
  ["per capita population growth rate", 0.08],
  ["tertiary consumers", 10],
  ["Simpson's diversity index", 0.62],
];
