export default [
  ["10 amino acids joined by dehydration synthesis", 9],
  ["solute potential of a 0.20 M sucrose solution", -0.2*0.0831*300],
  ["how many molecules of CO₂ are released", 6],
  ["molecules of ATP are produced from one molecule of glucose", 30],
  ["20 cells are in mitosis", 2.4],
  ["What percentage of the cells were in mitosis", 15],
  ["how long does a cell spend in prophase", 2.4],
  ["chi-square statistic for these data", 0.47],
  ["900 nucleotides", 300],
  ["copies are present after 5 cycles", 32],
  ["frequency of the dominant allele (p) is 0.7", 0.09],
  ["500 individuals in Hardy–Weinberg equilibrium", 160],
  ["one-eighth of the amount of carbon-14", 17190],
  ["per capita growth rate of r = 0.20", 20],
  ["carrying capacity of the habitat", 500],
  ["growth rate of the population the greatest", 250],
  ["Simpson's diversity index for community 2", 0.27],
  ["second child is a carrier", 2/3],
];
