export default [
  ["peptide bonds are in the protein", 149],
  ["Determine the ratio of the cell's surface area", 2.0],
  ["no change in mass", 0.514, 0.03],
  ["one net molecule of the three-carbon sugar G3P", 9],
  ["fraction of the cycle spent in S phase", 20],
  ["How many chromosomes are in each cell at the end of meiosis I", 23],
  ["at least one of their two children", 7/16],
  ["recombination frequency between the two genes", 15],
  ["degrees of freedom should be used", 3],
  ["20% of the nucleotides are thymine", 30],
  ["What is the total size of the plasmid", 3500],
  ["frequency of heterozygous individuals?", 0.42],
  ["25% of the uranium-238", 9.0],
  ["allele frequency of A after one generation of migration", 0.74],
  ["doubling time of the population", 10],
  ["efficiency of energy transfer", 9],
  ["population growth rate when N = 200", 60],
];
