// Authoring pool for Physics 1 Exam 1.
// S = numeric/ordered question: choices in final order, `a` = index of correct choice.
// M = conceptual question: choices[0] is the correct one; builder shuffles to hit the target letter.
const S = (u, s, c, a, e) => ({ u, s, c, a, e, sorted: true });
const M = (u, s, c, e) => ({ u, s, c, a: 0, e, sorted: false });

export default [
  // ---------------- Unit 1: Kinematics (5) ----------------
  S(1,
    "A cyclist rides along a straight path. At t = 0 her velocity is −3 m/s, and she then has a constant acceleration of +2 m/s². What is her displacement from t = 0 to t = 4 s?",
    ["−12 m", "+4 m", "+16 m", "+28 m"], 1,
    "Use x = v₀t + ½at² = (−3)(4) + ½(2)(4)² = −12 + 16 = +4 m. The initial velocity is negative, so it contributes −12 m even though the acceleration eventually reverses her motion. −12 m ignores the acceleration, +16 m ignores the initial velocity, and +28 m treats the initial velocity as +3 m/s."),
  S(1,
    "A ball is thrown straight upward from the ground with an initial speed of 20 m/s. Air resistance is negligible. What maximum height above the ground does the ball reach?",
    ["10 m", "20 m", "30 m", "40 m"], 1,
    "At the top of the path v = 0, so 0 = v₀² − 2gh and h = v₀²/(2g) = 400/20 = 20 m. 40 m results from using v₀²/g and forgetting the factor of 2 in the kinematic equation."),
  M(1,
    "The velocity of an object moving along a straight line is plotted against time. The graph is a straight line with a negative slope that crosses the time axis at t = 3 s. Which of the following describes the object at t = 5 s?",
    ["It is moving in the negative direction and speeding up.",
     "It is moving in the positive direction and slowing down.",
     "It is moving in the positive direction and speeding up.",
     "It is moving in the negative direction and slowing down."],
    "A straight line with a negative slope means a constant negative acceleration. After the line crosses zero at t = 3 s the velocity is negative, so the velocity and acceleration now point the same way and the speed increases while the object moves in the negative direction. Before t = 3 s the object was moving in the positive direction and slowing down."),
  M(1,
    "A projectile is launched from level ground at an angle of 45° above the horizontal. Air resistance is negligible. Which of the following is true at the highest point of the projectile's path?",
    ["Its velocity is horizontal and its acceleration is 10 m/s² downward.",
     "Its velocity and its acceleration are both zero.",
     "Its velocity is zero and its acceleration is 10 m/s² downward.",
     "Its velocity is horizontal and its acceleration is zero."],
    "At the top, the vertical component of velocity is zero but the horizontal component is unchanged and nonzero, so the velocity is horizontal. The only force is gravity, so the acceleration is g = 10 m/s² downward at every point of the flight, including the top."),
  S(1,
    "A boat points directly across a river and moves at 6 m/s relative to the water. The river's current is 8 m/s, parallel to the banks. What is the boat's speed relative to the shore?",
    ["2 m/s", "6 m/s", "8 m/s", "10 m/s"], 3,
    "The boat's velocity relative to the water (6 m/s across) and the current (8 m/s downstream) are perpendicular, so the speed relative to the shore is √(6² + 8²) = 10 m/s. 2 m/s would be the difference of the speeds, which only applies to motion along the same line."),

  // ---------------- Unit 2: Force and Translational Dynamics (8) ----------------
  M(2,
    "A book rests on a horizontal table. Earth pulls down on the book with a force equal to the book's weight, and the table pushes up on the book with a normal force. Which force forms the Newton's third-law pair with the weight of the book?",
    ["The gravitational force the book exerts on Earth",
     "The normal force the table exerts on the book",
     "The normal force the book exerts on the table",
     "The force the table exerts on Earth"],
    "A third-law pair acts on two different objects, is the same type of force, and has equal magnitude in opposite directions. Earth pulls on the book gravitationally, so the partner is the book's gravitational pull on Earth. The table's normal force balances the weight only because the book is in equilibrium (Newton's first law); it is not the third-law partner. The normal force of the book on the table is the partner of the table's normal force on the book."),
  S(2,
    "A 60 kg person stands on a bathroom scale in an elevator that is accelerating upward at 2.0 m/s². What does the scale read?",
    ["480 N", "600 N", "720 N", "1200 N"], 2,
    "Newton's second law gives N − mg = ma, so N = m(g + a) = 60(10 + 2) = 720 N. 600 N is the person's weight, which the scale would read at rest or at constant velocity, and 480 N is m(g − a), the reading if the elevator were accelerating downward at 2.0 m/s²."),
  S(2,
    "A 10 kg block slides down a frictionless incline that makes an angle of 30° with the horizontal. What is the magnitude of the block's acceleration?",
    ["2.5 m/s²", "5.0 m/s²", "8.7 m/s²", "10 m/s²"], 1,
    "Only the component of gravity along the incline accelerates the block: a = g sin 30° = (10)(0.50) = 5.0 m/s². The mass cancels. 8.7 m/s² results from using cosine instead of sine, and 10 m/s² would be free fall."),
  S(2,
    "A 25 kg crate rests on a horizontal floor. The coefficients of friction between the crate and the floor are μₛ = 0.40 and μₖ = 0.30. A person pushes horizontally on the crate with a force of 80 N, and the crate does not move. What is the magnitude of the friction force on the crate?",
    ["0 N", "75 N", "80 N", "100 N"], 2,
    "The crate is at rest, so the net force is zero and static friction must exactly balance the 80 N push. The maximum static friction is μₛN = (0.40)(250) = 100 N, which is larger than 80 N, so the crate does not slip. 100 N is only the maximum possible static friction, and 75 N is the kinetic friction value, which applies only once the crate is sliding."),
  S(2,
    "A 2.0 kg puck on a frictionless horizontal table is attached to a string and moves in a horizontal circle of radius 0.50 m at a constant speed of 3.0 m/s. What is the tension in the string?",
    ["6 N", "9 N", "18 N", "36 N"], 3,
    "The tension provides the centripetal force: T = mv²/r = (2.0)(3.0)²/0.50 = 36 N. 18 N results from using r = 1.0 m instead of 0.50 m."),
  S(2,
    "At the surface of Earth the gravitational acceleration is 10 m/s². What is the gravitational acceleration at a point that is 3 Earth radii from Earth's center, far from any other bodies?",
    ["1.1 m/s²", "3.3 m/s²", "5.0 m/s²", "10 m/s²"], 0,
    "Gravitational acceleration varies as 1/r². At three times the distance from the center it is 1/9 as large: 10/9 ≈ 1.1 m/s². 3.3 m/s² results from treating the dependence as 1/r instead of 1/r²."),
  S(2,
    "Two blocks of mass 2.0 kg and 3.0 kg are in contact on a frictionless horizontal surface. A 10 N horizontal force pushes on the 2.0 kg block, which in turn pushes on the 3.0 kg block. What is the magnitude of the force that the 2.0 kg block exerts on the 3.0 kg block?",
    ["4 N", "6 N", "10 N", "20 N"], 1,
    "Both blocks accelerate together: a = F/(m₁ + m₂) = 10/5.0 = 2.0 m/s². The 3.0 kg block is accelerated only by the contact force, so F = ma = (3.0)(2.0) = 6.0 N. 4 N is the net force on the 2.0 kg block (10 − 6), and 10 N is the force applied to the whole system."),
  M(2,
    "A skydiver falls through the air and eventually reaches terminal velocity. Which of the following is true once the skydiver is falling at terminal velocity?",
    ["The upward drag force on the skydiver equals the skydiver's weight.",
     "The upward drag force on the skydiver is greater than the skydiver's weight.",
     "Gravity no longer acts on the skydiver once terminal velocity is reached.",
     "The net force on the skydiver is directed downward and is constant."],
    "At terminal velocity the skydiver's velocity is constant, so the net force is zero (Newton's first law). The upward drag must therefore equal the downward weight. Gravity still acts; the drag force simply grows with speed until it balances gravity."),

  // ---------------- Unit 3: Work, Energy, and Power (8) ----------------
  S(3,
    "A 0.50 kg ball is thrown straight up with an initial speed of 12 m/s. Ignoring air resistance, what is the ball's kinetic energy when it is 4.0 m above its launch point?",
    ["6 J", "16 J", "20 J", "36 J"], 1,
    "The initial kinetic energy is ½(0.50)(12)² = 36 J. Rising 4.0 m increases the gravitational potential energy by mgh = (0.50)(10)(4.0) = 20 J, so the kinetic energy is 36 − 20 = 16 J. 20 J is the potential energy gained, and 36 J is the initial kinetic energy."),
  S(3,
    "A spring with force constant 200 N/m is compressed 0.30 m and then used to launch a 0.50 kg block across a frictionless horizontal surface. What is the speed of the block as it leaves the spring?",
    ["6 m/s", "9 m/s", "12 m/s", "18 m/s"], 0,
    "The spring's stored energy is ½kx² = ½(200)(0.30)² = 9.0 J, and all of it becomes the block's kinetic energy: ½(0.50)v² = 9.0, so v² = 36 and v = 6 m/s."),
  S(3,
    "A motor lifts a 1200 kg elevator car upward at a constant speed of 2.0 m/s. What power does the motor deliver to the car?",
    ["2,400 W", "12,000 W", "24,000 W", "48,000 W"], 2,
    "Constant speed means the lifting force equals the weight: F = mg = 12,000 N. The power is P = Fv = (12,000)(2.0) = 24,000 W. 12,000 W is the force itself, and 2,400 W comes from leaving out g."),
  S(3,
    "A 2.0 kg block slides along a rough horizontal surface. Its speed is 6.0 m/s, and it comes to rest after sliding 9.0 m. What is the magnitude of the average friction force on the block?",
    ["4.0 N", "6.0 N", "8.0 N", "12 N"], 0,
    "Friction removes all of the block's kinetic energy: f·d = ½mv². Since ½(2.0)(6.0)² = 36 J, f = 36/9.0 = 4.0 N. 8.0 N results from forgetting the factor of ½ in the kinetic energy."),
  S(3,
    "A 3.0 kg block slides down a rough incline, starting from rest at a height of 2.0 m above the bottom. It reaches the bottom with a speed of 4.0 m/s. How much mechanical energy is converted to thermal energy by friction?",
    ["36 J", "48 J", "60 J", "84 J"], 0,
    "The initial potential energy is mgh = (3.0)(10)(2.0) = 60 J, and the final kinetic energy is ½(3.0)(4.0)² = 24 J. The missing 60 − 24 = 36 J became thermal energy. 60 J would be the thermal energy only if the block ended at rest, and 84 J wrongly adds the final kinetic energy."),
  M(3,
    "A satellite moves in a circular orbit around Earth at constant speed. How much work does Earth's gravitational force do on the satellite during one-quarter of an orbit?",
    ["Zero, because the force is perpendicular to the satellite's displacement at every point.",
     "Positive, because the gravitational force points toward the center of the orbit.",
     "Negative, because the satellite's speed is reduced by the gravitational force.",
     "Positive, because the satellite accelerates toward Earth throughout its orbit."],
    "Work is W = Fd cos θ. At every point the gravitational force points toward Earth while the displacement is along the tangent, perpendicular to the force, so cos θ = 0 and the work is zero. This is why the kinetic energy and speed stay constant. The satellite does accelerate toward Earth, but that acceleration changes only the direction of its velocity."),
  S(3,
    "A 3.0 kg cart starts from rest on a horizontal frictionless track. A force directed along the track is 6.0 N from x = 0 to x = 2.0 m and then decreases linearly to zero at x = 6.0 m. What is the cart's speed at x = 6.0 m?",
    ["4 m/s", "6 m/s", "8 m/s", "12 m/s"], 0,
    "The work is the area under the force–position graph: a rectangle (6.0 N)(2.0 m) = 12 J plus a triangle ½(6.0 N)(4.0 m) = 12 J, for 24 J in total. Then W = ΔK gives 24 = ½(3.0)v², so v² = 16 and v = 4.0 m/s."),
  M(3,
    "Two identical blocks are released from rest at the same height. Block 1 falls vertically in free fall, and block 2 slides down a long frictionless ramp. How do the blocks' speeds compare when each has dropped to the ground?",
    ["They are equal, because both blocks lose the same gravitational potential energy.",
     "Block 1 is faster, because it travels the shorter path to the ground.",
     "Block 2 is faster, because it accelerates for a longer time on the ramp.",
     "Block 1 is faster, because the ramp exerts a force that opposes the motion."],
    "On both paths the only force doing work is gravity (the ramp's normal force is perpendicular to the motion and does no work). Both blocks drop the same height, so both gain the same kinetic energy: ½mv² = mgh and v = √(2gh). The ramp changes the time taken, not the final speed."),

  // ---------------- Unit 4: Linear Momentum (5) ----------------
  S(4,
    "A 0.15 kg ball moving horizontally at 20 m/s strikes a wall perpendicularly and rebounds horizontally at 12 m/s. The ball is in contact with the wall for 0.020 s. What is the magnitude of the average force the wall exerts on the ball?",
    ["60 N", "150 N", "240 N", "480 N"], 2,
    "Take the initial direction as positive: Δp = m(v_f − v_i) = 0.15(−12 − 20) = −4.8 kg·m/s. The average force is |Δp|/Δt = 4.8/0.020 = 240 N. 60 N results from subtracting the speeds (20 − 12) and forgetting that the ball reverses direction, and 150 N uses only the incoming momentum."),
  S(4,
    "A 2.0 kg cart moving at 3.0 m/s on a frictionless track collides with and sticks to a 4.0 kg cart that is initially at rest. What is the speed of the combined carts after the collision?",
    ["0.5 m/s", "1.0 m/s", "1.5 m/s", "3.0 m/s"], 1,
    "Momentum is conserved: (2.0)(3.0) = (6.0)v, so v = 1.0 m/s. 1.5 m/s is the average of the initial speeds, which has no physical basis here."),
  S(4,
    "Two carts, one of mass m and one of mass 3m, are at rest on a frictionless track with a compressed spring between them. When released, the carts push apart. What is the ratio of the kinetic energy of the cart of mass m to the kinetic energy of the cart of mass 3m just after release?",
    ["1/9", "1/3", "1", "3"], 3,
    "No external horizontal force acts on the system, so the carts have momenta of equal magnitude p. Kinetic energy is K = p²/(2m), which is inversely proportional to mass, so the lighter cart has 3 times the kinetic energy of the heavier cart. (Equivalently, the lighter cart moves 3 times faster: m(3v)² compared with 3mv² gives a ratio of 3.)"),
  S(4,
    "A 2.0 kg object is at x = 1.0 m and a 3.0 kg object is at x = 6.0 m on the x-axis. What is the x-coordinate of the center of mass of the two-object system?",
    ["3.5 m", "4.0 m", "5.0 m", "7.0 m"], 1,
    "x_cm = (m₁x₁ + m₂x₂)/(m₁ + m₂) = [(2.0)(1.0) + (3.0)(6.0)]/5.0 = 20/5.0 = 4.0 m. 3.5 m is the simple average of the two positions, which ignores that the masses are different."),
  M(4,
    "In a car crash, an airbag increases the time over which a passenger's body comes to rest, compared with striking the dashboard directly. Which of the following is true when the airbag deploys?",
    ["The average force on the passenger is smaller, because the same change in momentum occurs over a longer time.",
     "The impulse on the passenger is smaller, because the airbag absorbs part of the momentum.",
     "The average force on the passenger is the same, because the impulse delivered is larger.",
     "The change in the passenger's momentum is smaller, because the passenger slows down gradually."],
    "The passenger goes from the same initial velocity to rest either way, so the change in momentum, and therefore the impulse, is the same. Since J = F_avg Δt, a longer stopping time means a smaller average force."),

  // ---------------- Unit 5: Torque and Rotational Dynamics (5) ----------------
  S(5,
    "A uniform horizontal rod of mass 6.0 kg and length 2.0 m is attached to a wall by a hinge at one end. A vertical cable attached to the free end holds the rod in a horizontal position. What is the tension in the cable?",
    ["15 N", "30 N", "60 N", "120 N"], 1,
    "Take torques about the hinge so the unknown hinge force drops out. The rod's weight, 60 N, acts at its center, 1.0 m from the hinge, and the cable acts 2.0 m from the hinge. Equilibrium requires T(2.0) = (60)(1.0), so T = 30 N. 60 N would be the tension only if the cable were attached at the rod's center."),
  S(5,
    "A mechanic pulls with a 20 N force on a wrench at a point 0.40 m from the bolt. The force makes an angle of 30° with the wrench handle. What is the magnitude of the torque the force exerts about the bolt?",
    ["4.0 N·m", "6.9 N·m", "8.0 N·m", "12 N·m"], 0,
    "τ = rF sin θ = (0.40)(20)(sin 30°) = (0.40)(20)(0.50) = 4.0 N·m. 8.0 N·m forgets the sine factor, and 6.9 N·m uses cosine instead of sine."),
  S(5,
    "A wheel with rotational inertia 0.50 kg·m² is initially at rest. A constant net torque of 3.0 N·m is applied to it. What is the wheel's angular speed after 4.0 s?",
    ["1.5 rad/s", "6.0 rad/s", "12 rad/s", "24 rad/s"], 3,
    "The angular acceleration is α = τ/I = 3.0/0.50 = 6.0 rad/s². Starting from rest, ω = αt = (6.0)(4.0) = 24 rad/s. 6.0 is the angular acceleration (in rad/s²), not the angular speed after 4.0 s."),
  M(5,
    "A thin hoop and a solid disk have the same mass and the same radius, and each can rotate freely about its central axis. The same constant net torque is applied to each, starting from rest. Which statement is correct?",
    ["The disk has the greater angular acceleration, because its rotational inertia is smaller.",
     "The hoop has the greater angular acceleration, because its mass is farther from the axis.",
     "The two have the same angular acceleration, because they have equal mass and radius.",
     "The two have the same angular acceleration, because the net torque on each is the same."],
    "Angular acceleration is α = τ/I. The hoop (I = MR²) has greater rotational inertia than the disk (I = ½MR²) because all of its mass is at the maximum distance from the axis. For the same torque the disk therefore has twice the angular acceleration. Rotational inertia depends on how the mass is distributed, not only on the mass and radius."),
  S(5,
    "A uniform meterstick balances on a pivot at its 70 cm mark when a 0.30 kg mass is hung from the 100 cm end. What is the mass of the meterstick?",
    ["0.20 kg", "0.30 kg", "0.45 kg", "0.90 kg"], 2,
    "The stick's center of mass is at the 50 cm mark, 20 cm from the pivot on one side, and the hanging mass is 30 cm from the pivot on the other side. Balancing torques: m_stick(0.20) = (0.30)(0.30), so m_stick = 0.45 kg."),

  // ---------------- Unit 6: Energy and Momentum of Rotating Systems (3) ----------------
  M(6,
    "A horizontal disk rotates freely about a frictionless vertical axle. A small lump of clay is dropped onto the disk and sticks to it near the rim. Which statement correctly compares the disk-and-clay system just before and just after the clay sticks?",
    ["Angular momentum is conserved, but rotational kinetic energy decreases.",
     "Both angular momentum and rotational kinetic energy are conserved.",
     "Rotational kinetic energy is conserved, but angular momentum decreases.",
     "Both angular momentum and rotational kinetic energy decrease."],
    "No external torque acts about the axle, so the angular momentum of the system is conserved. The clay adds rotational inertia, so the angular speed decreases. Since K = L²/(2I), the kinetic energy decreases when I increases at constant L; mechanical energy is converted to thermal energy as the clay sticks."),
  S(6,
    "A 0.50 kg ball moves at a constant velocity of 4.0 m/s along a straight line. The line of motion passes at a perpendicular distance of 1.5 m from a point P. What is the magnitude of the ball's angular momentum about P?",
    ["0.75 kg·m²/s", "2.0 kg·m²/s", "3.0 kg·m²/s", "6.0 kg·m²/s"], 2,
    "L = mvr⊥ = (0.50)(4.0)(1.5) = 3.0 kg·m²/s. The value 2.0 is the ball's linear momentum mv and does not include the distance from P."),
  S(6,
    "A solid disk of mass 2.0 kg and radius 0.50 m (rotational inertia I = ½MR²) rotates about its central axis at an angular speed of 8.0 rad/s. What is its rotational kinetic energy?",
    ["2.0 J", "4.0 J", "6.0 J", "8.0 J"], 3,
    "The rotational inertia is I = ½(2.0)(0.50)² = 0.25 kg·m², so K = ½Iω² = ½(0.25)(8.0)² = 8.0 J."),

  // ---------------- Unit 7: Oscillations (3) ----------------
  S(7,
    "A simple pendulum of length 0.90 m swings through a small angle. What is its period?",
    ["0.6 s", "1.0 s", "1.5 s", "1.9 s"], 3,
    "The period of a simple pendulum is T = 2π√(L/g) = 2π√(0.90/10) = 2π(0.30) ≈ 1.9 s."),
  S(7,
    "A block on a spring oscillates in simple harmonic motion with amplitude A. When the block is at a displacement of A/2 from equilibrium, what fraction of the total mechanical energy is kinetic energy?",
    ["1/4", "1/2", "3/4", "1"], 2,
    "The total energy is E = ½kA². At x = A/2 the spring potential energy is ½k(A/2)² = ¼E, so the remaining 3/4 of the energy is kinetic. 1/4 is the potential-energy fraction at that point."),
  M(7,
    "A block oscillates on a horizontal spring along an x-axis with its equilibrium position at x = 0. At the instant the block's speed is greatest, which statement is true?",
    ["The block is at x = 0 and its acceleration is zero.",
     "The block is at x = 0 and its acceleration is at its maximum magnitude.",
     "The block is at maximum displacement and its acceleration is zero.",
     "The block is at maximum displacement and its acceleration is at its maximum magnitude."],
    "The speed is greatest at the equilibrium position, where all of the energy is kinetic. The restoring force F = −kx is zero there, so the acceleration is zero. At maximum displacement the speed is zero and the acceleration has its greatest magnitude."),

  // ---------------- Unit 8: Fluids (5) ----------------
  S(8,
    "A 60 kg person stands on one foot, which has a contact area of 0.020 m² with the floor. What pressure does the foot exert on the floor?",
    ["3,000 Pa", "12,000 Pa", "30,000 Pa", "300,000 Pa"], 2,
    "The force on the floor is the person's weight, mg = 600 N, so P = F/A = 600/0.020 = 30,000 Pa. Using the mass (60) instead of the weight gives a pressure ten times too small."),
  S(8,
    "Water flows through a horizontal pipe with a cross-sectional area of 0.040 m² at a speed of 2.0 m/s. The pipe then narrows to a cross-sectional area of 0.010 m². What is the water's speed in the narrow section?",
    ["0.50 m/s", "2.0 m/s", "8.0 m/s", "16 m/s"], 2,
    "By the continuity equation, A₁v₁ = A₂v₂, so v₂ = (0.040)(2.0)/0.010 = 8.0 m/s. The speed increases when the cross-sectional area decreases."),
  S(8,
    "A diver is 20 m below the surface of a lake. The atmospheric pressure is 1.0 × 10<sup>5</sup> Pa, and the density of water is 1000 kg/m³. What is the absolute pressure at the diver's depth?",
    ["1.2 × 10<sup>5</sup> Pa", "2.0 × 10<sup>5</sup> Pa", "2.5 × 10<sup>5</sup> Pa", "3.0 × 10<sup>5</sup> Pa"], 3,
    "P = P₀ + ρgh = 1.0 × 10<sup>5</sup> + (1000)(10)(20) = 1.0 × 10<sup>5</sup> + 2.0 × 10<sup>5</sup> = 3.0 × 10<sup>5</sup> Pa. The value 2.0 × 10<sup>5</sup> Pa is only the pressure added by the water; it leaves out the atmosphere."),
  S(8,
    "A 0.50 kg object with a volume of 3.0 × 10⁻⁴ m³ hangs from a string attached to a fixed support above it, completely underwater. The density of water is 1000 kg/m³. What is the tension in the string?",
    ["2.0 N", "3.0 N", "5.0 N", "8.0 N"], 0,
    "The buoyant force is B = ρVg = (1000)(3.0 × 10⁻⁴)(10) = 3.0 N upward. The object is in equilibrium with the string and the buoyant force both pulling up and the weight mg = 5.0 N pulling down: T + B = mg, so T = 5.0 − 3.0 = 2.0 N. 3.0 N is only the buoyant force, 5.0 N is the weight (the tension in air), and 8.0 N adds the buoyant force instead of subtracting it."),
  M(8,
    "Water flows steadily through a horizontal pipe that narrows. How do the water's speed and pressure in the narrow section compare with those in the wide section?",
    ["The speed is greater and the pressure is lower.",
     "The speed is greater and the pressure is higher.",
     "The speed is lower and the pressure is higher.",
     "The speed is lower and the pressure is lower."],
    "By continuity the speed is greater in the narrow section. For a horizontal pipe, Bernoulli's equation says P + ½ρv² is constant, so the greater speed corresponds to a lower pressure."),
];
