const S = (u, s, c, a, e) => ({ u, s, c, a, e, sorted: true });
const M = (u, s, c, e) => ({ u, s, c, a: 0, e, sorted: false });

export default [
  // ---------------- Unit 1: Kinematics (5) ----------------
  S(1,
    "A student walks 6.0 m east and then 8.0 m north. What is the magnitude of the student's displacement?",
    ["10 m", "14 m", "28 m", "48 m"], 0,
    "The displacement is the straight-line vector from start to finish. The two legs are perpendicular, so the magnitude is √(6.0² + 8.0²) = 10 m. The total distance traveled is 14 m, which is a different quantity, since distance is the total path length."),
  S(1,
    "A drone starts from rest and accelerates uniformly at 3.0 m/s² for 4.0 s. How far does the drone travel during this time?",
    ["12 m", "24 m", "48 m", "72 m"], 1,
    "Starting from rest, x = ½at² = ½(3.0)(4.0)² = 24 m. The drone's final speed is 12 m/s; multiplying that speed by the time (48 m) would be correct only if the drone had moved at its final speed the whole time."),
  S(1,
    "A ball is thrown straight up at 12 m/s from ground level. Ignoring air resistance, how long is the ball in the air before it returns to the ground?",
    ["0.6 s", "1.2 s", "2.4 s", "4.8 s"], 2,
    "The ball rises until its velocity is zero, which takes t = v₀/g = 1.2 s, and then takes the same time to fall back to the launch height. The total time is 2(1.2) = 2.4 s. 1.2 s is only the time to reach the top."),
  M(1,
    "Which of the following can be determined from the area between a velocity-versus-time graph and the time axis for a given time interval?",
    ["The displacement of the object during the interval",
     "The acceleration of the object at the end of the interval",
     "The average acceleration of the object during the interval",
     "The position of the object at the start of the interval"],
    "The area under a velocity–time graph is the product of velocity and time summed over the interval, which is the displacement. Acceleration is the slope of the graph, not the area, and the area says nothing about where the object started."),
  S(1,
    "A ball is launched from level ground with a speed of 20 m/s at an angle of 30° above the horizontal. What is the magnitude of the vertical component of the ball's initial velocity?",
    ["10 m/s", "14 m/s", "17 m/s", "20 m/s"], 0,
    "The vertical component is v₀ sin θ = (20)(sin 30°) = (20)(0.50) = 10 m/s. The 17 m/s value is the horizontal component, v₀ cos 30°."),

  // ---------------- Unit 2: Force and Translational Dynamics (8) ----------------
  S(2,
    "A 3.0 kg object on a frictionless horizontal surface is acted on by two horizontal forces: 12 N toward the east and 4.0 N toward the west. What is the magnitude of the object's acceleration?",
    ["1.3 m/s²", "2.0 m/s²", "2.7 m/s²", "5.3 m/s²"], 2,
    "The forces are in opposite directions, so the net force is 12 − 4.0 = 8.0 N toward the east. Then a = F/m = 8.0/3.0 ≈ 2.7 m/s². 5.3 m/s² comes from adding the magnitudes of the forces (16 N)."),
  S(2,
    "A 5.0 kg block rests on a rough incline that makes an angle of 37° with the horizontal (sin 37° = 0.60 and cos 37° = 0.80). The block does not slide. What is the magnitude of the friction force on the block?",
    ["20 N", "25 N", "30 N", "40 N"], 2,
    "The block is in equilibrium, so the static friction force balances the component of the weight along the incline: f = mg sin 37° = (50)(0.60) = 30 N. 40 N is the component of the weight perpendicular to the incline, mg cos 37°."),
  S(2,
    "The gravitational force between two small spheres separated by a distance d is F. What is the gravitational force between the spheres if the separation is reduced to d/2 and nothing else changes?",
    ["F/4", "F/2", "2F", "4F"], 3,
    "The gravitational force varies as 1/r². Halving the distance multiplies the force by (1/(1/2))² = 4, so the new force is 4F. Answering 2F treats the force as inversely proportional to the distance rather than to its square."),
  S(2,
    "A 2.0 kg block hangs at rest from an ideal spring with a force constant of 100 N/m. By how much is the spring stretched from its relaxed length?",
    ["0.020 m", "0.050 m", "0.10 m", "0.20 m"], 3,
    "The block is in equilibrium, so the spring force balances the weight: kx = mg, giving x = (2.0)(10)/100 = 0.20 m. 0.020 m results from using the mass instead of the weight."),
  M(2,
    "An elevator is moving downward and slowing down as it comes to a stop. How does the reading of a scale on which a passenger stands compare with the passenger's weight?",
    ["It is greater than the weight, because the elevator's acceleration is directed upward.",
     "It is less than the weight, because the elevator is moving downward.",
     "It is equal to the weight, because the elevator's velocity is directed downward.",
     "It is less than the weight, because the elevator's acceleration is directed upward."],
    "Because the elevator is moving downward and slowing, its acceleration is directed upward. Newton's second law then requires an upward net force on the passenger, so the scale's normal force must be greater than the weight: N − mg = ma with a > 0 upward. The direction of the velocity does not determine the scale reading — the direction of the acceleration does."),
  S(2,
    "A 6.0 kg block and a 4.0 kg block rest on a frictionless horizontal surface and are connected by a light string. A horizontal 30 N force pulls on the 6.0 kg block directly away from the 4.0 kg block, so the string stays taut. What is the tension in the string?",
    ["8 N", "12 N", "18 N", "30 N"], 1,
    "The blocks accelerate together: a = 30/(6.0 + 4.0) = 3.0 m/s². The string is the only horizontal force on the 4.0 kg block, so T = (4.0)(3.0) = 12 N. 18 N is the net force on the 6.0 kg block (30 − 12), and 30 N is the force applied to the whole system."),
  S(2,
    "A 1000 kg car traveling at 20 m/s brakes to a stop in 40 m with a constant braking force. What is the magnitude of the braking force?",
    ["2,500 N", "5,000 N", "10,000 N", "20,000 N"], 1,
    "From v² = 2ad, the deceleration is a = 400/80 = 5.0 m/s². The braking force is F = ma = (1000)(5.0) = 5000 N."),
  M(2,
    "A hockey puck slides across a frictionless, horizontal ice surface at a constant velocity. Which statement about the puck is correct?",
    ["The net force on the puck is zero.",
     "A forward force must act on the puck to keep it moving.",
     "The net force on the puck is directed along its motion.",
     "The puck's weight is the only force that acts on it."],
    "Constant velocity means zero acceleration, so by Newton's first and second laws the net force is zero. No forward force is needed to keep the puck moving. The puck's weight is balanced by the upward normal force from the ice, so weight is not the only force acting on it."),

  // ---------------- Unit 3: Work, Energy, and Power (8) ----------------
  S(3,
    "A 2.0 kg box slides down a frictionless ramp from a point 3.0 m above the bottom. How much work does gravity do on the box during the descent?",
    ["30 J", "60 J", "120 J", "180 J"], 1,
    "Gravity does work equal to the weight times the vertical drop: W = mgh = (2.0)(10)(3.0) = 60 J, independent of the ramp's length or angle."),
  S(3,
    "A spring with a force constant of 500 N/m is compressed 0.20 m from its relaxed length. How much elastic potential energy is stored in the spring?",
    ["5 J", "10 J", "20 J", "100 J"], 1,
    "U = ½kx² = ½(500)(0.20)² = 10 J. 20 J forgets the factor of ½, and 100 is the spring force kx in newtons, not an energy."),
  S(3,
    "A car traveling at speed v can stop in a distance d on a level road, using brakes that provide a constant friction force. If the car's initial speed is doubled to 2v, what is the stopping distance with the same braking force?",
    ["2d", "3d", "4d", "8d"], 2,
    "By the work–energy theorem, the braking force times the stopping distance equals the initial kinetic energy: Fd = ½mv². The distance is proportional to v², so doubling the speed makes the stopping distance 4 times as large."),
  S(3,
    "A car moves at a constant 20 m/s on a level road. The engine delivers 40 kW of power to the wheels, all of which is used to overcome a constant resistive force. What is the magnitude of the resistive force?",
    ["500 N", "1,000 N", "2,000 N", "8,000 N"], 2,
    "At constant speed, the power equals the force times the speed: P = Fv, so F = 40,000/20 = 2000 N."),
  S(3,
    "A 0.20 kg ball is dropped from a height of 5.0 m onto the floor and rebounds to a height of 3.2 m. How much mechanical energy is lost in the bounce?",
    ["1.8 J", "2.4 J", "3.2 J", "3.6 J"], 3,
    "The energy lost is the difference in gravitational potential energy: mg(h₁ − h₂) = (0.20)(10)(5.0 − 3.2) = 3.6 J. 1.8 is the difference in height (in meters), not an energy."),
  S(3,
    "A 50 kg sled is pulled 20 m up an incline that rises at 30° above the horizontal, moving at a constant speed. A constant friction force of 100 N opposes the motion. How much work does the rope do on the sled?",
    ["2,000 J", "5,000 J", "6,000 J", "7,000 J"], 3,
    "The sled rises (20)(sin 30°) = 10 m, so gravity requires work mgh = (500)(10) = 5000 J. Overcoming friction over 20 m requires (100)(20) = 2000 J. The rope must supply both: 5000 + 2000 = 7000 J, because the kinetic energy does not change."),
  S(3,
    "A 400 kg roller-coaster car starts from rest at the top of a hill that is 25 m higher than the bottom. Ignoring friction, what is the car's speed at the bottom?",
    ["12 m/s", "16 m/s", "20 m/s", "22 m/s"], 3,
    "Energy conservation gives mgh = ½mv², so v = √(2gh) = √(2 × 10 × 25) = √500 ≈ 22 m/s. The mass cancels."),
  M(3,
    "Which of the following graphs correctly shows how the kinetic energy of an object depends on the object's speed?",
    ["An upward-curving parabola that starts at the origin",
     "A straight line that starts at the origin",
     "A curve that starts at the origin and flattens out (concave down)",
     "A horizontal line"],
    "Kinetic energy is K = ½mv², so it is proportional to the square of the speed. Its graph against speed is a parabola opening upward that passes through the origin. A straight line would show a K that is proportional to v, such as the momentum."),

  // ---------------- Unit 4: Linear Momentum (5) ----------------
  M(4,
    "A moving billiard ball collides head-on and elastically with an identical ball that is initially at rest. Which of the following describes the motion immediately after the collision?",
    ["The first ball stops, and the second ball moves with the first ball's original velocity.",
     "The balls stick together and move at half the original speed of the first ball.",
     "The first ball rebounds with its original speed, and the second ball remains at rest.",
     "Both balls move forward, each with half of the original speed of the first ball."],
    "In an elastic collision both momentum and kinetic energy are conserved. For equal masses the balls exchange velocities, so the first ball stops and the second moves off with the first ball's original velocity. If the balls stuck together or each moved at half speed, momentum would be conserved but the kinetic energy would be cut in half. If the first ball rebounded with the second at rest, the momentum would change sign and would not be conserved."),
  S(4,
    "A 0.25 kg ball moving at 8.0 m/s toward a bat is hit and leaves the bat at 12 m/s in the opposite direction. What is the magnitude of the impulse the bat delivers to the ball?",
    ["1.0 N·s", "2.0 N·s", "3.0 N·s", "5.0 N·s"], 3,
    "Taking the initial direction as positive, Δp = m(v_f − v_i) = (0.25)(−12 − 8.0) = −5.0 kg·m/s, so the impulse has magnitude 5.0 N·s. 1.0 N·s results from subtracting the speeds without accounting for the reversal of direction."),
  S(4,
    "Two ice skaters, with masses of 60 kg and 40 kg, stand at rest on frictionless ice and push off from each other. The 60 kg skater moves backward at 2.0 m/s. What is the speed of the 40 kg skater?",
    ["1.3 m/s", "2.0 m/s", "3.0 m/s", "5.0 m/s"], 2,
    "The total momentum of the system stays zero, so the skaters move in opposite directions with equal-magnitude momenta: (60)(2.0) = (40)v, giving v = 3.0 m/s. The lighter skater moves faster."),
  M(4,
    "A graph shows the net force on an object as a function of time. Which of the following quantities is represented by the area under the graph?",
    ["The change in the object's momentum",
     "The change in the object's kinetic energy",
     "The work done on the object",
     "The object's acceleration"],
    "The area under a force–time graph is the impulse, and by the impulse–momentum theorem the impulse equals the change in momentum. The change in kinetic energy and the work are related to the area under a force–position graph instead."),
  S(4,
    "A constant net force of 20 N acts on a 5.0 kg object that is initially at rest. After 4.0 s, what is the object's speed?",
    ["4.0 m/s", "16 m/s", "20 m/s", "80 m/s"], 1,
    "The impulse is FΔt = (20)(4.0) = 80 N·s, which equals the change in momentum: (5.0)v = 80, so v = 16 m/s. 4.0 m/s is the acceleration (20/5.0), and 80 is the impulse in N·s."),

  // ---------------- Unit 5: Torque and Rotational Dynamics (5) ----------------
  S(5,
    "A uniform 3.0 m beam of mass 30 kg rests horizontally on two supports, one at each end. A 60 kg person stands 1.0 m from the left end. What is the magnitude of the force the left support exerts on the beam?",
    ["450 N", "550 N", "600 N", "900 N"], 1,
    "Take torques about the right end so the right support's force drops out. The beam's weight (300 N) acts at its center, 1.5 m from the right end, and the person's weight (600 N) acts 2.0 m from the right end. Equilibrium requires N_L(3.0) = (300)(1.5) + (600)(2.0) = 1650, so N_L = 550 N."),
  S(5,
    "A flywheel rotating at 10 rad/s slows down uniformly and comes to rest in 5.0 s. What is the magnitude of its angular acceleration?",
    ["2.0 rad/s²", "5.0 rad/s²", "10 rad/s²", "50 rad/s²"], 0,
    "α = Δω/Δt = 10/5.0 = 2.0 rad/s² in magnitude. 50 results from multiplying the angular speed by the time."),
  S(5,
    "A net torque of 20 N·m acts on a wheel that has a rotational inertia of 4.0 kg·m². What is the wheel's angular acceleration?",
    ["5.0 rad/s²", "10 rad/s²", "20 rad/s²", "80 rad/s²"], 0,
    "α = τ/I = 20/4.0 = 5.0 rad/s². 80 results from multiplying the torque by the rotational inertia instead of dividing."),
  S(5,
    "A solid disk of mass 4.0 kg and radius 0.50 m (rotational inertia I = ½MR²) rotates about its central axis. What constant net torque is required to give the disk an angular acceleration of 8.0 rad/s²?",
    ["0.5 N·m", "1.0 N·m", "2.0 N·m", "4.0 N·m"], 3,
    "The rotational inertia is I = ½(4.0)(0.50)² = 0.50 kg·m². Then τ = Iα = (0.50)(8.0) = 4.0 N·m. The value 0.5 is the rotational inertia itself, not the torque."),
  S(5,
    "A uniform rod of length 2.0 m can pivot about its center. A downward force of 8.0 N is applied at the left end of the rod, and a downward force of 5.0 N is applied at a point 0.60 m to the right of the pivot. What is the magnitude of the net torque about the pivot?",
    ["3.0 N·m", "5.0 N·m", "8.0 N·m", "11 N·m"], 1,
    "The 8.0 N force acts 1.0 m from the pivot and produces a counterclockwise torque of 8.0 N·m. The 5.0 N force acts 0.60 m from the pivot on the other side and produces a clockwise torque of 3.0 N·m. The net torque is 8.0 − 3.0 = 5.0 N·m. The rod's weight acts at the pivot and contributes no torque. 11 N·m comes from adding the torques instead of subtracting them."),

  // ---------------- Unit 6: Energy and Momentum of Rotating Systems (3) ----------------
  S(6,
    "A rotating disk has a rotational inertia of 0.20 kg·m² and an angular speed of 15 rad/s. What is the magnitude of the disk's angular momentum?",
    ["3.0 kg·m²/s", "7.5 kg·m²/s", "30 kg·m²/s", "45 kg·m²/s"], 0,
    "The angular momentum is L = Iω = (0.20)(15) = 3.0 kg·m²/s."),
  M(6,
    "A solid sphere and a thin hoop of equal mass and equal radius are released from rest at the top of the same incline and roll down without slipping. Which statement is correct?",
    ["The sphere reaches the bottom first, because it has less rotational inertia, so more of its energy becomes translational kinetic energy.",
     "The hoop reaches the bottom first, because it has more rotational inertia and therefore more total energy.",
     "They reach the bottom together, because they have equal mass and equal radius.",
     "They reach the bottom together, because gravity accelerates all objects equally."],
    "Both objects lose the same gravitational potential energy mgh. A hoop has the greater rotational inertia (MR² compared with (2/5)MR²), so a larger share of its energy goes into rotation and less into translation. The sphere therefore has the larger translational speed, a larger acceleration down the incline, and reaches the bottom first."),
  S(6,
    "A horizontal disk with a rotational inertia of 100 kg·m² rotates freely at 2.0 rad/s about a vertical axis. A 25 kg child who was standing at rest beside the disk steps onto it and stays at a distance of 2.0 m from the axis. How much rotational kinetic energy is lost in the process?",
    ["25 J", "50 J", "75 J", "100 J"], 3,
    "The child adds a rotational inertia of mr² = (25)(2.0)² = 100 kg·m², so the total becomes 200 kg·m². Angular momentum is conserved: (100)(2.0) = (200)ω, so ω = 1.0 rad/s. The kinetic energy changes from ½(100)(2.0)² = 200 J to ½(200)(1.0)² = 100 J, so 100 J is lost."),

  // ---------------- Unit 7: Oscillations (3) ----------------
  M(7,
    "A block oscillates on an ideal spring with amplitude A and period T. The same block is set oscillating on the same spring with an amplitude of 2A. What is the new period?",
    ["T, because the period of a mass–spring oscillator does not depend on amplitude.",
     "2T, because the block travels twice as far during each cycle.",
     "T/2, because the block moves faster when the amplitude is larger.",
     "4T, because the energy of the oscillator is four times as large."],
    "The period of a mass–spring system is T = 2π√(m/k), which depends only on the mass and the spring constant. With a larger amplitude the block travels farther but also reaches a proportionally larger maximum speed, so the time for one cycle is unchanged."),
  S(7,
    "An oscillator completes 10 full cycles in 5.0 s. What is the oscillator's frequency?",
    ["0.50 Hz", "1.0 Hz", "2.0 Hz", "10 Hz"], 2,
    "Frequency is the number of cycles per second: 10/5.0 = 2.0 Hz. The value 0.50 is the period in seconds."),
  S(7,
    "A 0.50 kg block attached to a spring oscillates with a period of 0.63 s. What is the force constant of the spring?",
    ["10 N/m", "25 N/m", "50 N/m", "200 N/m"], 2,
    "Rearranging T = 2π√(m/k) gives k = 4π²m/T² = 4π²(0.50)/(0.63)² ≈ 50 N/m."),

  // ---------------- Unit 8: Fluids (5) ----------------
  S(8,
    "A cube with sides of 0.10 m has a mass of 0.50 kg. What is the density of the cube?",
    ["500 kg/m³", "1,000 kg/m³", "5,000 kg/m³", "50,000 kg/m³"], 0,
    "The volume is (0.10)³ = 1.0 × 10⁻³ m³, so the density is ρ = m/V = 0.50/(1.0 × 10⁻³) = 500 kg/m³."),
  S(8,
    "The absolute pressure at a certain depth in a freshwater lake (density 1000 kg/m³) is 2.0 × 10<sup>5</sup> Pa. The atmospheric pressure is 1.0 × 10<sup>5</sup> Pa. At what depth is this pressure found?",
    ["5.0 m", "10 m", "20 m", "200 m"], 1,
    "The pressure due to the water is 2.0 × 10<sup>5</sup> − 1.0 × 10<sup>5</sup> = 1.0 × 10<sup>5</sup> Pa = ρgh, so h = 1.0 × 10<sup>5</sup>/(1000 × 10) = 10 m."),
  S(8,
    "Water (density 1000 kg/m³) flows through a horizontal pipe. Its speed is 2.0 m/s in a wide section and 6.0 m/s in a narrow section. What is the pressure difference between the two sections?",
    ["8,000 Pa", "12,000 Pa", "16,000 Pa", "18,000 Pa"], 2,
    "For a horizontal pipe, Bernoulli's equation gives ΔP = ½ρ(v₂² − v₁²) = ½(1000)(36 − 4.0) = 16,000 Pa. 8,000 Pa results from squaring the difference of the speeds instead of taking the difference of the squares."),
  S(8,
    "The radius of a horizontal pipe carrying an ideal fluid is reduced to half of its original value in a narrow section. By what factor does the fluid's speed increase in the narrow section?",
    ["2", "3", "4", "8"], 2,
    "By continuity, A₁v₁ = A₂v₂. The cross-sectional area is proportional to r², so halving the radius reduces the area to 1/4, and the speed increases by a factor of 4."),
  S(8,
    "A ball with a volume of 2.0 × 10⁻³ m³ is completely submerged in water (density 1000 kg/m³). What is the magnitude of the buoyant force on the ball?",
    ["2 N", "10 N", "20 N", "200 N"], 2,
    "The buoyant force equals the weight of the displaced water: B = ρVg = (1000)(2.0 × 10⁻³)(10) = 20 N."),
];
